// .gitignore emission for the codegen output directory.
//
// Distilled-doc §"Boundary helpers": "A `.gitignore` inside the
// output directory, covering sensitive emitted files by default and
// preserving user customizations." Two design points:
//
//   1. The entire output directory is engine-managed and the
//      pragmatic default is "ignore everything emitted here". The
//      `*` line lives at the top of the file with a comment
//      explaining the policy.
//   2. Sensitive files get an explicit second mention so the
//      `.gitignore` reads as documentation in addition to enforcing
//      the policy.
//   3. User customisations land in a tracked `# user:` block — any
//      content the user adds between the `# user:` and `# /user:`
//      markers is preserved verbatim across re-emits.
//
// The `.gitignore` is written OUTSIDE the stage-and-swap (distilled-
// doc §"Re-emit timing window for the gitignore"). The window is
// human-visible only — only git/humans read this file — and the
// alternative (writing the gitignore inside staging) means a fresh
// clone-and-run scenario sees no gitignore on first emit before the
// swap completes. Outside the swap, it's always present.

import { Effect, FileSystem } from 'effect';

import { emitOne } from './emit.ts';
import { CodegenWriteFailed } from './errors.ts';
import { NON_SENSITIVE_FILE_MODE } from './permissions.ts';

const USER_BLOCK_START = '# user: customisations below preserved across re-emits';
const USER_BLOCK_END = '# /user: do not edit below this line';

const DEFAULT_USER_BLOCK = `${USER_BLOCK_START}\n${USER_BLOCK_END}`;

const HEADER = [
	'# THIS FILE IS AUTO-GENERATED BY @mysten/devstack.',
	'# The codegen output directory is engine-managed; the whole tree is',
	'# ignored from git by default. Sensitive files have an explicit mention',
	'# below for documentation. Add user customisations inside the `# user:`',
	'# block; the rest is rewritten on every emit cycle.',
].join('\n');

export interface GitignoreInput {
	readonly path: string;
	/** Relative paths inside the output dir that are sensitive — get
	 *  an explicit gitignore line. Sorted lexicographically. */
	readonly sensitivePaths: ReadonlyArray<string>;
}

/**
 * Compose the gitignore content, preserving any user customisations
 * between the `# user:` markers in any existing file at `path`.
 */
export const composeGitignore = (existing: string | null, input: GitignoreInput): string => {
	const userBlock = existing !== null ? extractUserBlock(existing) : null;
	const sortedSensitive = [...input.sensitivePaths].sort();
	const lines: Array<string> = [];
	lines.push(HEADER);
	lines.push('');
	lines.push('# default policy: ignore the whole output directory.');
	lines.push('*');
	lines.push('# but keep this .gitignore tracked so cloners get the policy.');
	lines.push('!.gitignore');
	if (sortedSensitive.length > 0) {
		lines.push('');
		lines.push('# sensitive files — never commit even if you override the `*` above.');
		for (const p of sortedSensitive) lines.push(p);
	}
	lines.push('');
	lines.push(userBlock !== null ? userBlock : DEFAULT_USER_BLOCK);
	return lines.join('\n') + '\n';
};

/**
 * Write the gitignore. Idempotent via `emitOne`'s no-touch path.
 */
export const writeGitignore = (
	input: GitignoreInput,
): Effect.Effect<void, CodegenWriteFailed, FileSystem.FileSystem> =>
	Effect.gen(function* () {
		const fs = yield* FileSystem.FileSystem;
		const existing = yield* fs.readFileString(input.path).pipe(
			Effect.match({
				onSuccess: (text) => text,
				onFailure: () => null,
			}),
		);
		const content = composeGitignore(existing, input);
		yield* emitOne({
			path: input.path,
			content,
			mode: NON_SENSITIVE_FILE_MODE,
		}).pipe(
			Effect.mapError(
				(e) =>
					new CodegenWriteFailed({
						outputPath: input.path,
						stage: 'gitignore',
						cause: e,
					}),
			),
		);
	}).pipe(
		Effect.withSpan('codegen.writeGitignore', {
			attributes: { 'codegen.path': input.path },
		}),
	);

const extractUserBlock = (text: string): string | null => {
	const startIdx = text.indexOf(USER_BLOCK_START);
	const endIdx = text.indexOf(USER_BLOCK_END);
	if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) return null;
	// Include both markers in the returned block.
	const endLineEnd = text.indexOf('\n', endIdx);
	const stop = endLineEnd === -1 ? text.length : endLineEnd;
	return text.slice(startIdx, stop);
};
