[package]
name = "mock_weth"
edition = "2024"
version = "0.0.1"

# Sui, MoveStdlib, Bridge, DeepBook, SuiSystem are auto-added by sui-cli
# (the 2024 edition behavior). No explicit deps needed.
[dependencies]

[addresses]
mock_weth = "0x0"
