// Renderer unit tests.
//
// Covers: header banners, sensitive-file extra banner, identifier-
// safe keys, deterministic key ordering, bigint serialisation,
// generated-import safety, circular-ref refusal, unsupported-value
// refusal, no-trailing-blank.

import { describe, expect, it } from '@effect/vitest';

import { renderFile } from '../../../src/orchestrators/codegen/format.ts';
import { CodegenRenderError } from '../../../src/orchestrators/codegen/errors.ts';
import { ForNetworkBucket, rawExpr } from '../../../src/contracts/codegenable.ts';

const expectOk = (result: ReturnType<typeof renderFile>): string => {
	if (!result.ok) throw new Error(`expected ok render; got error: ${result.error.detail}`);
	return result.text;
};

const expectErr = (result: ReturnType<typeof renderFile>): CodegenRenderError => {
	if (result.ok) throw new Error(`expected render error; got success`);
	return result.error;
};

describe('format/renderFile', () => {
	it('emits a generated-header + one export per record entry', () => {
		const text = expectOk(
			renderFile({
				emitterName: 'sui-network',
				outputPath: 'sui/network.ts',
				sensitive: false,
				exports: {
					suiNetwork: {
						chain: 'sui:localnet',
						rpcUrl: 'http://localhost:9000',
					},
				},
			}),
		);
		expect(text).toContain('AUTO-GENERATED BY @mysten/devstack');
		expect(text).toContain('export const suiNetwork =');
		expect(text).toContain('"sui:localnet"');
		expect(text).toContain('"http://localhost:9000"');
		expect(text.endsWith('\n')).toBe(true);
	});

	it('adds the do-not-commit banner only when sensitive=true', () => {
		const safe = expectOk(
			renderFile({
				emitterName: 'account-map',
				outputPath: 'accounts/alice.ts',
				sensitive: false,
				exports: { alice: { address: '0xab' } },
			}),
		);
		expect(safe).not.toContain('DO NOT COMMIT');

		const sensitive = expectOk(
			renderFile({
				emitterName: 'dapp-kit-config',
				outputPath: 'dapp-kit/config.ts',
				sensitive: true,
				exports: { dappKitConfig: { walletUrl: 'http://x' } },
			}),
		);
		expect(sensitive).toContain('DO NOT COMMIT');
	});

	it('sorts keys deterministically', () => {
		const out = expectOk(
			renderFile({
				emitterName: 'x',
				outputPath: 'x.ts',
				sensitive: false,
				exports: {
					zeta: { z: 1, a: 2, m: 3 },
					alpha: 1,
				},
			}),
		);
		// alpha before zeta
		expect(out.indexOf('alpha')).toBeLessThan(out.indexOf('zeta'));
		// within zeta: a < m < z
		const a = out.indexOf('a:');
		const m = out.indexOf('m:');
		const z = out.indexOf('z:');
		expect(a).toBeLessThan(m);
		expect(m).toBeLessThan(z);
	});

	it('serialises bigint as a quoted decimal string consumable by BigInt()', () => {
		const out = expectOk(
			renderFile({
				emitterName: 'x',
				outputPath: 'x.ts',
				sensitive: false,
				exports: { v: { big: 12345678901234567890n } },
			}),
		);
		expect(out).toContain('"12345678901234567890"');
		expect(BigInt('12345678901234567890')).toBe(12345678901234567890n);
	});

	it('refuses imports from devstack source or package exports in generated files', () => {
		const fromPackage = expectErr(
			renderFile({
				emitterName: 'x',
				outputPath: 'x.ts',
				sensitive: false,
				imports: ["import { readStackContext } from '@mysten-incubation/devstack/runtime';"],
				exports: { v: 1 },
			}),
		);
		expect(fromPackage).toBeInstanceOf(CodegenRenderError);

		const fromSource = expectErr(
			renderFile({
				emitterName: 'x',
				outputPath: 'x.ts',
				sensitive: false,
				imports: ["import { x } from '../../src/substrate/runtime/manifest/index.ts';"],
				exports: { v: 1 },
			}),
		);
		expect(fromSource).toBeInstanceOf(CodegenRenderError);
	});

	it('refuses circular references', () => {
		const a: Record<string, unknown> = {};
		a['self'] = a;
		const err = expectErr(
			renderFile({
				emitterName: 'x',
				outputPath: 'x.ts',
				sensitive: false,
				exports: { v: a },
			}),
		);
		expect(err).toBeInstanceOf(CodegenRenderError);
	});

	it('refuses functions and symbols', () => {
		const fn = expectErr(
			renderFile({
				emitterName: 'x',
				outputPath: 'x.ts',
				sensitive: false,
				exports: { v: { f: () => 1 } },
			}),
		);
		expect(fn).toBeInstanceOf(CodegenRenderError);
		const sym = expectErr(
			renderFile({
				emitterName: 'x',
				outputPath: 'x.ts',
				sensitive: false,
				exports: { v: { s: Symbol('x') } },
			}),
		);
		expect(sym).toBeInstanceOf(CodegenRenderError);
	});

	it('refuses identifier-unsafe export keys', () => {
		const err = expectErr(
			renderFile({
				emitterName: 'x',
				outputPath: 'x.ts',
				sensitive: false,
				exports: { 'has-dash': 1 },
			}),
		);
		expect(err).toBeInstanceOf(CodegenRenderError);
	});

	it('produces byte-identical output on identical input', () => {
		const input = {
			emitterName: 'x',
			outputPath: 'x.ts',
			sensitive: false,
			exports: { v: { a: 1, b: [1, 2, 3], c: { nested: true } } },
		} as const;
		expect(expectOk(renderFile(input))).toBe(expectOk(renderFile(input)));
	});

	it('drops undefined record properties (skip-emit-explicit)', () => {
		const out = expectOk(
			renderFile({
				emitterName: 'x',
				outputPath: 'x.ts',
				sensitive: false,
				exports: { v: { present: 1, absent: undefined } },
			}),
		);
		expect(out).toContain('present');
		expect(out).not.toContain('absent');
	});

	it('wraps a ForNetworkBucket in a per-network forNetwork(network) accessor', () => {
		const out = expectOk(
			renderFile({
				emitterName: 'aggregate/coins',
				outputPath: 'coins.ts',
				sensitive: false,
				exports: {
					coins: new ForNetworkBucket(
						{
							managed_coin: {
								fullCoinType: rawExpr(
									'requireValue<string>(dep, "coin:managed_coin", "fullCoinType")',
								),
								source: 'registry',
								symbol: 'managed_coin',
							},
						},
						true,
					),
				},
				imports: ["import { loadDeployment, requireValue } from './config-runtime.js';"],
			}),
		);
		// The bucket exports a `forNetwork(network)` accessor whose body resolves
		// `dep` per-call (NOT a module-level default-network `dep`) and returns
		// the inner bucket object `as const`.
		expect(out).toContain('export const coins = {');
		expect(out).toContain('\tforNetwork(network: string) {');
		expect(out).toContain('\t\tconst dep = loadDeployment().forNetwork(network);');
		expect(out).toContain('\t\treturn {');
		expect(out).toContain('requireValue<string>(dep, "coin:managed_coin", "fullCoinType")');
		// No module-level `const dep = …forNetwork(defaultNetwork)` baked in.
		expect(out).not.toContain('defaultNetwork');
	});

	it('a pure-literal ForNetworkBucket omits the dep line and marks the param unused', () => {
		const out = expectOk(
			renderFile({
				emitterName: 'aggregate/seal',
				outputPath: 'seal.ts',
				sensitive: false,
				exports: {
					seal: new ForNetworkBucket(
						{ seal: { mode: 'live', name: 'seal', objectId: '0xabc' } },
						false,
					),
				},
			}),
		);
		// A literal-only bucket needs no `dep` — the accessor ignores `_network`
		// and carries no `loadDeployment` reference.
		expect(out).toContain('forNetwork(_network: string) {');
		expect(out).not.toContain('const dep =');
		expect(out).not.toContain('loadDeployment');
		expect(out).toContain('objectId: "0xabc"');
	});
});
