// Renderer unit tests.
//
// Covers: header banners, sensitive-file extra banner, identifier-
// safe keys, deterministic key ordering, bigint serialisation,
// generated-import safety, circular-ref refusal, unsupported-value
// refusal, no-trailing-blank.

import { describe, expect, it } from '@effect/vitest';

import { renderFile } from '../../../src/orchestrators/codegen/format.ts';
import { CodegenRenderError } from '../../../src/orchestrators/codegen/errors.ts';

describe('format/renderFile', () => {
	it('emits a generated-header + one export per record entry', () => {
		const out = renderFile({
			emitterName: 'sui-network',
			outputPath: 'sui/network.ts',
			sensitive: false,
			exports: {
				suiNetwork: {
					chain: 'sui:local',
					rpcUrl: 'http://localhost:9000',
				},
			},
		});
		expect(typeof out).toBe('string');
		const text = out as string;
		expect(text).toContain('AUTO-GENERATED BY @mysten/devstack');
		expect(text).toContain('export const suiNetwork =');
		expect(text).toContain('"sui:local"');
		expect(text).toContain('"http://localhost:9000"');
		expect(text.endsWith('\n')).toBe(true);
	});

	it('adds the do-not-commit banner only when sensitive=true', () => {
		const safe = renderFile({
			emitterName: 'account-map',
			outputPath: 'accounts/alice.ts',
			sensitive: false,
			exports: { alice: { address: '0xab' } },
		}) as string;
		expect(safe).not.toContain('DO NOT COMMIT');

		const sensitive = renderFile({
			emitterName: 'dapp-kit-config',
			outputPath: 'dapp-kit/config.ts',
			sensitive: true,
			exports: { dappKitConfig: { walletUrl: 'http://x' } },
		}) as string;
		expect(sensitive).toContain('DO NOT COMMIT');
	});

	it('sorts keys deterministically', () => {
		const out = renderFile({
			emitterName: 'x',
			outputPath: 'x.ts',
			sensitive: false,
			exports: {
				zeta: { z: 1, a: 2, m: 3 },
				alpha: 1,
			},
		}) as string;
		// alpha before zeta
		expect(out.indexOf('alpha')).toBeLessThan(out.indexOf('zeta'));
		// within zeta: a < m < z
		const a = out.indexOf('a:');
		const m = out.indexOf('m:');
		const z = out.indexOf('z:');
		expect(a).toBeLessThan(m);
		expect(m).toBeLessThan(z);
	});

	it('serialises bigint as a quoted decimal string consumable by BigInt()', () => {
		const out = renderFile({
			emitterName: 'x',
			outputPath: 'x.ts',
			sensitive: false,
			exports: { v: { big: 12345678901234567890n } },
		}) as string;
		expect(out).toContain('"12345678901234567890"');
		expect(BigInt('12345678901234567890')).toBe(12345678901234567890n);
	});

	it('refuses imports from devstack source or package exports in generated files', () => {
		const fromPackage = renderFile({
			emitterName: 'x',
			outputPath: 'x.ts',
			sensitive: false,
			imports: ["import { readStackContext } from '@mysten-incubation/devstack/runtime';"],
			exports: { v: 1 },
		});
		expect(fromPackage).toBeInstanceOf(CodegenRenderError);

		const fromSource = renderFile({
			emitterName: 'x',
			outputPath: 'x.ts',
			sensitive: false,
			imports: ["import { x } from '../../src/substrate/runtime/manifest/index.ts';"],
			exports: { v: 1 },
		});
		expect(fromSource).toBeInstanceOf(CodegenRenderError);
	});

	it('refuses circular references', () => {
		const a: Record<string, unknown> = {};
		a['self'] = a;
		const err = renderFile({
			emitterName: 'x',
			outputPath: 'x.ts',
			sensitive: false,
			exports: { v: a },
		});
		expect(err).toBeInstanceOf(CodegenRenderError);
	});

	it('refuses functions and symbols', () => {
		const fn = renderFile({
			emitterName: 'x',
			outputPath: 'x.ts',
			sensitive: false,
			exports: { v: { f: () => 1 } },
		});
		expect(fn).toBeInstanceOf(CodegenRenderError);
		const sym = renderFile({
			emitterName: 'x',
			outputPath: 'x.ts',
			sensitive: false,
			exports: { v: { s: Symbol('x') } },
		});
		expect(sym).toBeInstanceOf(CodegenRenderError);
	});

	it('refuses identifier-unsafe export keys', () => {
		const err = renderFile({
			emitterName: 'x',
			outputPath: 'x.ts',
			sensitive: false,
			exports: { 'has-dash': 1 },
		});
		expect(err).toBeInstanceOf(CodegenRenderError);
	});

	it('produces byte-identical output on identical input', () => {
		const input = {
			emitterName: 'x',
			outputPath: 'x.ts',
			sensitive: false,
			exports: { v: { a: 1, b: [1, 2, 3], c: { nested: true } } },
		} as const;
		const a = renderFile(input);
		const b = renderFile(input);
		expect(a).toBe(b);
	});

	it('drops undefined record properties (skip-emit-explicit)', () => {
		const out = renderFile({
			emitterName: 'x',
			outputPath: 'x.ts',
			sensitive: false,
			exports: { v: { present: 1, absent: undefined } },
		}) as string;
		expect(out).toContain('present');
		expect(out).not.toContain('absent');
	});
});
