/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'Account': { kind: 'OBJECT'; name: 'Account'; fields: { 'address': { name: 'address'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'funding': { name: 'funding'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'AccountFunding'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'key': { name: 'key'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'rowKey': { name: 'rowKey'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'scheme': { name: 'scheme'; type: { kind: 'ENUM'; name: 'AccountScheme'; ofType: null; } }; 'source': { name: 'source'; type: { kind: 'ENUM'; name: 'AccountSource'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'walletVisible': { name: 'walletVisible'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'AccountFunding': { kind: 'OBJECT'; name: 'AccountFunding'; fields: { 'balanceMist': { name: 'balanceMist'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'entries': { name: 'entries'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'FundingEntry'; ofType: null; }; }; }; } }; 'requestedMist': { name: 'requestedMist'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'FundingStatus'; ofType: null; }; } }; }; };
    'AccountScheme': { name: 'AccountScheme'; enumValues: 'ed25519' | 'secp256k1' | 'secp256r1'; };
    'AccountSource': { name: 'AccountSource'; enumValues: 'impersonate' | 'real'; };
    'Boolean': unknown;
    'BuildEntry': { kind: 'OBJECT'; name: 'BuildEntry'; fields: { 'phase': { name: 'phase'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'pluginKey': { name: 'pluginKey'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'progress': { name: 'progress'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'startedAt': { name: 'startedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; }; };
    'CoinCap': { kind: 'OBJECT'; name: 'CoinCap'; fields: { 'decimals': { name: 'decimals'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'fullCoinType': { name: 'fullCoinType'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'narrowingFault': { name: 'narrowingFault'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'packageId': { name: 'packageId'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'pluginKey': { name: 'pluginKey'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'source': { name: 'source'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'symbol': { name: 'symbol'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'treasuryCapId': { name: 'treasuryCapId'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'CommandResult': { kind: 'OBJECT'; name: 'CommandResult'; fields: { 'command': { name: 'command'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'message': { name: 'message'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'ok': { name: 'ok'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'Cycle': { kind: 'OBJECT'; name: 'Cycle'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'phase': { name: 'phase'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'startedAt': { name: 'startedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; }; };
    'DeepbookInfo': { kind: 'OBJECT'; name: 'DeepbookInfo'; fields: { 'adminCapId': { name: 'adminCapId'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'chain': { name: 'chain'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'deepTreasuryId': { name: 'deepTreasuryId'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'indexerUrl': { name: 'indexerUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'marketMakerRunning': { name: 'marketMakerRunning'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'mode': { name: 'mode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'DeepbookMode'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'narrowingFault': { name: 'narrowingFault'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'packageId': { name: 'packageId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'pluginKey': { name: 'pluginKey'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'pools': { name: 'pools'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DeepbookPool'; ofType: null; }; }; }; } }; 'registryId': { name: 'registryId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'serverUrl': { name: 'serverUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'DeepbookMode': { name: 'DeepbookMode'; enumValues: 'known' | 'local' | 'override'; };
    'DeepbookPool': { kind: 'OBJECT'; name: 'DeepbookPool'; fields: { 'baseCoinType': { name: 'baseCoinType'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'poolId': { name: 'poolId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'quoteCoinType': { name: 'quoteCoinType'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'Endpoint': { kind: 'OBJECT'; name: 'Endpoint'; fields: { 'displayUrl': { name: 'displayUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'endpointKey': { name: 'endpointKey'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'pluginKey': { name: 'pluginKey'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'registeredAt': { name: 'registeredAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'url': { name: 'url'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'wireProtocol': { name: 'wireProtocol'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'WireProtocol'; ofType: null; }; } }; }; };
    'ErrorSeverity': { name: 'ErrorSeverity'; enumValues: 'error' | 'fatal' | 'warn'; };
    'Float': unknown;
    'FundResult': { kind: 'OBJECT'; name: 'FundResult'; fields: { 'detail': { name: 'detail'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'ok': { name: 'ok'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'FundableCoin': { kind: 'OBJECT'; name: 'FundableCoin'; fields: { 'coinType': { name: 'coinType'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'honorsAmount': { name: 'honorsAmount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'requiresAccountSigner': { name: 'requiresAccountSigner'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'symbol': { name: 'symbol'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'FundingEntry': { kind: 'OBJECT'; name: 'FundingEntry'; fields: { 'amount': { name: 'amount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'coin': { name: 'coin'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'fullCoinType': { name: 'fullCoinType'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'FundingStatus': { name: 'FundingStatus'; enumValues: 'failed' | 'funded' | 'pending' | 'skipped' | 'unknown'; };
    'Health': { name: 'Health'; enumValues: 'active' | 'blocked' | 'empty' | 'ready'; };
    'HealthSummary': { kind: 'OBJECT'; name: 'HealthSummary'; fields: { 'active': { name: 'active'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'failed': { name: 'failed'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'health': { name: 'health'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'Health'; ofType: null; }; } }; 'ready': { name: 'ready'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'total': { name: 'total'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'waiting': { name: 'waiting'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'ID': unknown;
    'Identity': { kind: 'OBJECT'; name: 'Identity'; fields: { 'app': { name: 'app'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'network': { name: 'network'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'stack': { name: 'stack'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'Int': unknown;
    'LastEvent': { kind: 'OBJECT'; name: 'LastEvent'; fields: { 'at': { name: 'at'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'seq': { name: 'seq'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'LifecycleStatus': { name: 'LifecycleStatus'; enumValues: 'acquiring' | 'done' | 'failed' | 'pending' | 'ready' | 'stopped' | 'stopping'; };
    'LogFilter': { kind: 'INPUT_OBJECT'; name: 'LogFilter'; isOneOf: false; inputFields: [{ name: 'levels'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; defaultValue: null }, { name: 'limit'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'search'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'services'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; defaultValue: null }, { name: 'sinceMillis'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; defaultValue: null }]; };
    'LogLevel': { name: 'LogLevel'; enumValues: 'error' | 'info' | 'warn'; };
    'LogRecord': { kind: 'OBJECT'; name: 'LogRecord'; fields: { 'fieldsJson': { name: 'fieldsJson'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'level': { name: 'level'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'message': { name: 'message'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'seq': { name: 'seq'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'service': { name: 'service'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'timestampMillis': { name: 'timestampMillis'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; }; };
    'LogTail': { kind: 'OBJECT'; name: 'LogTail'; fields: { 'level': { name: 'level'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'LogLevel'; ofType: null; }; } }; 'lines': { name: 'lines'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; } }; 'truncated': { name: 'truncated'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'MintResult': { kind: 'OBJECT'; name: 'MintResult'; fields: { 'detail': { name: 'detail'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'digest': { name: 'digest'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'ok': { name: 'ok'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { 'advanceClock': { name: 'advanceClock'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CommandResult'; ofType: null; }; } }; 'apply': { name: 'apply'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CommandResult'; ofType: null; }; } }; 'captureSnapshot': { name: 'captureSnapshot'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CommandResult'; ofType: null; }; } }; 'codegen': { name: 'codegen'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CommandResult'; ofType: null; }; } }; 'deleteSnapshot': { name: 'deleteSnapshot'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SnapshotActionResult'; ofType: null; }; } }; 'fund': { name: 'fund'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'FundResult'; ofType: null; }; } }; 'mint': { name: 'mint'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'MintResult'; ofType: null; }; } }; 'prune': { name: 'prune'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CommandResult'; ofType: null; }; } }; 'restart': { name: 'restart'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CommandResult'; ofType: null; }; } }; 'restartPlugin': { name: 'restartPlugin'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CommandResult'; ofType: null; }; } }; 'restoreSnapshot': { name: 'restoreSnapshot'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SnapshotActionResult'; ofType: null; }; } }; 'shutdown': { name: 'shutdown'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CommandResult'; ofType: null; }; } }; 'wipe': { name: 'wipe'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CommandResult'; ofType: null; }; } }; }; };
    'MutationAdvanceClockInput': { kind: 'INPUT_OBJECT'; name: 'MutationAdvanceClockInput'; isOneOf: false; inputFields: [{ name: 'toMillis'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; }; defaultValue: null }]; };
    'MutationApplyInput': { kind: 'INPUT_OBJECT'; name: 'MutationApplyInput'; isOneOf: false; inputFields: [{ name: 'pluginKey'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'MutationCaptureSnapshotInput': { kind: 'INPUT_OBJECT'; name: 'MutationCaptureSnapshotInput'; isOneOf: false; inputFields: [{ name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'MutationDeleteSnapshotInput': { kind: 'INPUT_OBJECT'; name: 'MutationDeleteSnapshotInput'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'MutationFundInput': { kind: 'INPUT_OBJECT'; name: 'MutationFundInput'; isOneOf: false; inputFields: [{ name: 'amountBaseUnits'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'coinType'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'recipient'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'MutationMintInput': { kind: 'INPUT_OBJECT'; name: 'MutationMintInput'; isOneOf: false; inputFields: [{ name: 'amountBaseUnits'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'coinType'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'recipient'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'MutationRestartPluginInput': { kind: 'INPUT_OBJECT'; name: 'MutationRestartPluginInput'; isOneOf: false; inputFields: [{ name: 'pluginKey'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'MutationRestoreSnapshotInput': { kind: 'INPUT_OBJECT'; name: 'MutationRestoreSnapshotInput'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'Node': { kind: 'INTERFACE'; name: 'Node'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; possibleTypes: 'Account' | 'Endpoint' | 'Package' | 'Service'; };
    'Package': { kind: 'OBJECT'; name: 'Package'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'key': { name: 'key'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'kind': { name: 'kind'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'PackageKind'; ofType: null; }; } }; 'mvrPlaceholder': { name: 'mvrPlaceholder'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'packageId': { name: 'packageId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'rowKey': { name: 'rowKey'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'sourcePath': { name: 'sourcePath'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'upgradeCapId': { name: 'upgradeCapId'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'PackageKind': { name: 'PackageKind'; enumValues: 'known' | 'local'; };
    'PageInfo': { kind: 'OBJECT'; name: 'PageInfo'; fields: { 'endCursor': { name: 'endCursor'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'hasNextPage': { name: 'hasNextPage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'hasPreviousPage': { name: 'hasPreviousPage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'startCursor': { name: 'startCursor'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'PluginRole': { name: 'PluginRole'; enumValues: 'service' | 'task'; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'accounts': { name: 'accounts'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'QueryAccountsConnection'; ofType: null; }; } }; 'coinCaps': { name: 'coinCaps'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CoinCap'; ofType: null; }; }; }; } }; 'deepbookInfo': { name: 'deepbookInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DeepbookInfo'; ofType: null; }; }; }; } }; 'fundableCoins': { name: 'fundableCoins'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'FundableCoin'; ofType: null; }; }; }; } }; 'logServices': { name: 'logServices'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; } }; 'logs': { name: 'logs'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'LogRecord'; ofType: null; }; }; }; } }; 'mode': { name: 'mode'; type: { kind: 'ENUM'; name: 'StackMode'; ofType: null; } }; 'node': { name: 'node'; type: { kind: 'INTERFACE'; name: 'Node'; ofType: null; } }; 'nodes': { name: 'nodes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'INTERFACE'; name: 'Node'; ofType: null; }; }; } }; 'packages': { name: 'packages'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'QueryPackagesConnection'; ofType: null; }; } }; 'ping': { name: 'ping'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'sealInfo': { name: 'sealInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SealInfo'; ofType: null; }; }; }; } }; 'services': { name: 'services'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'QueryServicesConnection'; ofType: null; }; } }; 'snapshots': { name: 'snapshots'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SnapshotEntry'; ofType: null; }; }; }; } }; 'state': { name: 'state'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'StackState'; ofType: null; }; } }; }; };
    'QueryAccountsConnection': { kind: 'OBJECT'; name: 'QueryAccountsConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'QueryAccountsConnectionEdge'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PageInfo'; ofType: null; }; } }; }; };
    'QueryAccountsConnectionEdge': { kind: 'OBJECT'; name: 'QueryAccountsConnectionEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Account'; ofType: null; }; } }; }; };
    'QueryPackagesConnection': { kind: 'OBJECT'; name: 'QueryPackagesConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'QueryPackagesConnectionEdge'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PageInfo'; ofType: null; }; } }; }; };
    'QueryPackagesConnectionEdge': { kind: 'OBJECT'; name: 'QueryPackagesConnectionEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Package'; ofType: null; }; } }; }; };
    'QueryServicesConnection': { kind: 'OBJECT'; name: 'QueryServicesConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'QueryServicesConnectionEdge'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PageInfo'; ofType: null; }; } }; }; };
    'QueryServicesConnectionEdge': { kind: 'OBJECT'; name: 'QueryServicesConnectionEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Service'; ofType: null; }; } }; }; };
    'RowSection': { name: 'RowSection'; enumValues: 'account' | 'action' | 'app' | 'other' | 'package' | 'service'; };
    'SealInfo': { kind: 'OBJECT'; name: 'SealInfo'; fields: { 'keyServerUrl': { name: 'keyServerUrl'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'keyServers': { name: 'keyServers'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'SealKeyServer'; ofType: null; }; }; }; } }; 'mode': { name: 'mode'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'narrowingFault': { name: 'narrowingFault'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'objectId': { name: 'objectId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'pluginKey': { name: 'pluginKey'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'threshold': { name: 'threshold'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'SealKeyServer': { kind: 'OBJECT'; name: 'SealKeyServer'; fields: { 'objectId': { name: 'objectId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'weight': { name: 'weight'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'Service': { kind: 'OBJECT'; name: 'Service'; fields: { 'endpointSection': { name: 'endpointSection'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'RowSection'; ofType: null; }; } }; 'endpoints': { name: 'endpoints'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Endpoint'; ofType: null; }; }; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'key': { name: 'key'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'lastError': { name: 'lastError'; type: { kind: 'OBJECT'; name: 'StackError'; ofType: null; } }; 'logTail': { name: 'logTail'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'LogTail'; ofType: null; }; } }; 'phase': { name: 'phase'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'role': { name: 'role'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'PluginRole'; ofType: null; }; } }; 'section': { name: 'section'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'RowSection'; ofType: null; }; } }; 'selectiveRestartHighlight': { name: 'selectiveRestartHighlight'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'LifecycleStatus'; ofType: null; }; } }; }; };
    'SnapshotActionResult': { kind: 'OBJECT'; name: 'SnapshotActionResult'; fields: { 'detail': { name: 'detail'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'ok': { name: 'ok'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; }; };
    'SnapshotEntry': { kind: 'OBJECT'; name: 'SnapshotEntry'; fields: { 'app': { name: 'app'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'containerCount': { name: 'containerCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'corrupt': { name: 'corrupt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'label': { name: 'label'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'network': { name: 'network'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'participants': { name: 'participants'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; } }; 'stack': { name: 'stack'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'subtreeCount': { name: 'subtreeCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'StackError': { kind: 'OBJECT'; name: 'StackError'; fields: { 'at': { name: 'at'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'chain': { name: 'chain'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; } }; 'pluginKey': { name: 'pluginKey'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'severity': { name: 'severity'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'ErrorSeverity'; ofType: null; }; } }; 'summary': { name: 'summary'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'tag': { name: 'tag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'StackMode': { name: 'StackMode'; enumValues: 'fork' | 'live' | 'local'; };
    'StackState': { kind: 'OBJECT'; name: 'StackState'; fields: { 'accounts': { name: 'accounts'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Account'; ofType: null; }; }; }; } }; 'cycle': { name: 'cycle'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Cycle'; ofType: null; }; } }; 'endpoints': { name: 'endpoints'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Endpoint'; ofType: null; }; }; }; } }; 'errors': { name: 'errors'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'StackError'; ofType: null; }; }; }; } }; 'identity': { name: 'identity'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Identity'; ofType: null; }; } }; 'lastEvent': { name: 'lastEvent'; type: { kind: 'OBJECT'; name: 'LastEvent'; ofType: null; } }; 'packages': { name: 'packages'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Package'; ofType: null; }; }; }; } }; 'services': { name: 'services'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Service'; ofType: null; }; }; }; } }; 'stackBuild': { name: 'stackBuild'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'BuildEntry'; ofType: null; }; }; }; } }; 'summary': { name: 'summary'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'HealthSummary'; ofType: null; }; } }; }; };
    'String': unknown;
    'Subscription': { kind: 'OBJECT'; name: 'Subscription'; fields: { 'state': { name: 'state'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'StackState'; ofType: null; }; } }; }; };
    'WireProtocol': { name: 'WireProtocol'; enumValues: 'h2c' | 'http' | 'tcp'; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
	name: never;
	query: 'Query';
	mutation: 'Mutation';
	subscription: 'Subscription';
	types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
	interface setupSchema {
		introspection: introspection;
	}
}
