// Sui plugin — the Move toolchain it declares for codegen.
//
// Bindings must be generated by the same `sui` CLI that builds and
// publishes, so the sui member tells the codegen orchestrator which one
// that is (see `MoveToolchain` in contracts/codegenable.ts). Two sources:
//   - live boot: the exact image the mode resolved — no re-derivation;
//   - stack-free `codegen`: no image exists yet, so the declaration is
//     derived from the SAME plan the mode would boot with. The env var is
//     folded in here, through `configuredSuiToolsRef`, exactly where the
//     image plan folds it in — never independently downstream.

import type { MoveToolchain } from '../../contracts/codegenable.ts';
import type { ImageRef } from '../../contracts/container-runtime.ts';
import { planForkImage } from './mode/fork.ts';
import type { SuiOptions } from './mode/spec.ts';
import { configuredSuiToolsRef, DEFAULT_SUI_TOOLS_REF } from './move/index.ts';

/** Stack-free declaration, derived from the mode's image plan. `undefined`
 *  when the plan is a complete image devstack cannot reproduce without a
 *  stack (`image.pull`, a from-source or prebuilt fork). */
export const suiMoveToolchain = (opts: SuiOptions): MoveToolchain | undefined => {
	switch (opts.mode) {
		case 'local': {
			if (opts.image !== undefined && 'pull' in opts.image) {
				return undefined;
			}
			// Bundled image, or a caller Dockerfile fed the same SUI_TOOLS_IMAGE.
			const configured = configuredSuiToolsRef(opts.suiToolsRef);
			return {
				kind: 'sui-tools',
				suiToolsRef: configured ?? DEFAULT_SUI_TOOLS_REF,
				explicit: configured !== undefined,
			};
		}
		case 'fork': {
			const plan = planForkImage(opts);
			if (plan.kind === 'sui-tools') {
				return { kind: 'sui-tools', suiToolsRef: plan.ref, explicit: true };
			}
			if (plan.kind === 'custom-build' && plan.suiToolsRef !== undefined) {
				return { kind: 'sui-tools', suiToolsRef: plan.suiToolsRef, explicit: true };
			}
			return undefined;
		}
		case 'live':
		case 'local-rpc':
			return undefined;
	}
};

/** Live declaration: the resolved build image when the mode has one, else
 *  the stack-free derivation (live/local-rpc have no container). */
export const liveMoveToolchain = (
	buildImage: ImageRef | null,
	opts: SuiOptions,
): MoveToolchain | undefined =>
	buildImage === null ? suiMoveToolchain(opts) : { kind: 'image', image: buildImage };
