// DappKitEmitter — emit a generated TS module that wires up dapp-kit
// against the resolved devstack manifest. Replaces the runtime
// `createDevstackDappKit(...)` path so apps can keep devstack as a
// pure dev-dep (the generated module imports only `@mysten/sui`,
// `@mysten/dapp-kit-core` / `-react`, and `@mysten-incubation/dev-wallet`
// — never `@mysten-incubation/devstack` at runtime).
//
// Manifest-driven: at emit time the emitter reads the resolved
// `CodegenContext.packages` (any `Package` / `KnownPackage` ref in the
// stack that didn't opt out via `{ codegen: false }`) to derive MVR
// overrides. The localnet RPC URL is also baked in — re-emit whenever
// the supervisor restarts on a different port.
//
// Flavors:
//   - `'core'` — for `@mysten/dapp-kit-core` (vanilla DAppKit).
//   - `'react'` — for `@mysten/dapp-kit-react` (registers the type so
//     `useDAppKit()` infers correctly).
//
// The emitted file is byte-stable for a given manifest input — the
// emitter sorts MVR entries alphabetically and uses a single
// indentation style. Re-emitting after no manifest change writes the
// same bytes, so file-watchers in dev mode don't trip spurious
// HMR cycles.

import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { Effect } from 'effect';
import { discoverManifestPath } from '../../runtime/discover-manifest.js';
import { CodegenError } from '../errors.js';
import { defineEmitter, type CodegenContext, type Emitter } from '../define-emitter.js';

export type DappKitFlavor = 'core' | 'react';

export interface DappKitEmitterOptions {
	/** Which dapp-kit flavor to import from. Defaults to `'react'`. */
	readonly flavor?: DappKitFlavor;
	/** Localnet RPC URL to bake into the generated file. Defaults to
	 *  `'http://localhost:9000'` — matches the default sui-localnet
	 *  port. Override when the dev server proxies the RPC. */
	readonly localnetRpcUrl?: string;
	/** Enable the burner-wallet adapter wiring. Defaults to `true`.
	 *  Set `false` to emit a config that wires only the user's own
	 *  wallets. */
	readonly enableBurnerWallet?: boolean;
	/** Path to the manifest JSON that should be copied next to the
	 *  emitted `index.ts` so its `import './manifest.json'` resolves.
	 *  Defaults to `<DEVSTACK_STATE_DIR ?? '.devstack'>/stacks/<DEVSTACK_STACK
	 *  ?? 'main'>/manifest.json`, falling back to the legacy flat
	 *  `<state-dir>/manifest.json`. Only consulted when
	 *  `enableBurnerWallet: true` (the manifest import only appears in
	 *  that branch). */
	readonly manifestPath?: string;
}

const FLAVOR_IMPORTS: Record<DappKitFlavor, { core: string; module: string }> = {
	core: { core: '@mysten/dapp-kit-core', module: '@mysten/dapp-kit-core' },
	react: { core: '@mysten/dapp-kit-core', module: '@mysten/dapp-kit-react' },
};

const renderMvrOverrides = (ctx: CodegenContext): string => {
	const entries = ctx.packages
		.map((p) => ({ key: p.mvrPlaceholder, value: p.packageId }))
		.sort((a, b) => a.key.localeCompare(b.key));
	if (entries.length === 0) return '{}';
	const lines = entries.map((e) => `\t${JSON.stringify(e.key)}: ${JSON.stringify(e.value)}`);
	return `{\n${lines.join(',\n')},\n}`;
};

const renderFile = (ctx: CodegenContext, opts: Required<DappKitEmitterOptions>): string => {
	const flavor = FLAVOR_IMPORTS[opts.flavor];
	const mvrOverrides = renderMvrOverrides(ctx);
	const registerBlock =
		opts.flavor === 'react'
			? `
declare module '@mysten/dapp-kit-react' {
\tinterface Register {
\t\tdAppKit: typeof dAppKit;
\t}
}
`
			: '';
	const adapterBlock = opts.enableBurnerWallet
		? `import { devWalletInitializer } from '@mysten-incubation/dev-wallet';
import { createDevstackAdapterFromManifest } from '@mysten-incubation/dev-wallet/adapters';

// Manifest snapshot — re-emitted alongside the rest of this file.
import manifestJson from './manifest.json' with { type: 'json' };

const adapter = createDevstackAdapterFromManifest(manifestJson);
const walletInitializers = adapter ? [devWalletInitializer({ adapters: [adapter] })] : [];
`
		: 'const walletInitializers = [];';
	return `// Generated by @mysten-incubation/devstack — do not edit by hand.
// Re-run \`pnpm dev\` (or the devstack supervisor that emitted this) to
// regenerate.

import { createDAppKit } from '${flavor.core}';
import { SuiGrpcClient } from '@mysten/sui/grpc';
${adapterBlock}
const localnetRpcUrl = ${JSON.stringify(opts.localnetRpcUrl)};
const mvrOverrides = ${mvrOverrides};

export const dAppKit = createDAppKit({
\tdefaultNetwork: 'localnet',
\tnetworks: ['localnet'],
\tcreateClient: (network) =>
\t\tnew SuiGrpcClient({
\t\t\tnetwork,
\t\t\tbaseUrl: localnetRpcUrl,
\t\t\tmvr: Object.keys(mvrOverrides).length > 0
\t\t\t\t? { overrides: { packages: mvrOverrides } }
\t\t\t\t: undefined,
\t\t}),
\tenableBurnerWallet: ${opts.enableBurnerWallet},
\twalletInitializers,
});
${registerBlock}`;
};

const writeFile = (outputPath: string, contents: string): Effect.Effect<void, CodegenError> =>
	Effect.tryPromise({
		try: async () => {
			await fs.mkdir(path.dirname(outputPath), { recursive: true });
			// Skip the write when the bytes already match — keeps watchers
			// (Vite HMR, tsc -b) from tripping on no-op regenerations.
			let existing: string | undefined;
			try {
				existing = await fs.readFile(outputPath, 'utf-8');
			} catch {
				// missing — fall through and write
			}
			if (existing === contents) return;
			await fs.writeFile(outputPath, contents, 'utf-8');
		},
		catch: (cause) =>
			new CodegenError({
				emitter: 'dapp-kit',
				phase: 'write',
				message: `failed to write ${outputPath}: ${String(cause)}`,
				cause,
			}),
	});

/** Build a `DappKitEmitter` plug-in instance. Drop into
 *  `Codegen({ emitters: [DappKitEmitter()] })` or surface alongside
 *  `BindingsEmitter`. */
export const DappKitEmitter = (opts: DappKitEmitterOptions = {}): Emitter => {
	const resolved = {
		flavor: opts.flavor ?? 'react',
		localnetRpcUrl: opts.localnetRpcUrl ?? 'http://localhost:9000',
		enableBurnerWallet: opts.enableBurnerWallet ?? true,
		manifestPath: opts.manifestPath,
	} as const;
	return defineEmitter({
		name: 'dapp-kit',
		emit: (ctx) =>
			Effect.gen(function* () {
				const outDir = path.join(ctx.outputDir, 'dapp-kit');
				const filePath = path.join(outDir, 'index.ts');
				const contents = renderFile(ctx, {
					flavor: resolved.flavor,
					localnetRpcUrl: resolved.localnetRpcUrl,
					enableBurnerWallet: resolved.enableBurnerWallet,
					manifestPath: resolved.manifestPath ?? '',
				});
				yield* writeFile(filePath, contents);
				// C11: emit `<outDir>/manifest.json` as a sibling of
				// `index.ts` so the generated code's `import './manifest.json'`
				// resolves at TS-build time. Only required when burner
				// wallet wiring is enabled (only that branch emits the
				// import). Best-effort: if the manifest can't be located
				// (e.g. emit ran before the supervisor wrote it on a
				// truly fresh stack), skip with a warning so the
				// generated TS still compiles when the manifest lands
				// later in the same dev session.
				if (resolved.enableBurnerWallet) {
					const manifestSrc = yield* Effect.sync(() =>
						discoverManifestPath({ override: resolved.manifestPath }),
					);
					if (manifestSrc === undefined) {
						yield* Effect.logWarning(
							`DappKitEmitter: manifest not found yet — generated dapp-kit/index.ts ` +
								`will fail to compile until the supervisor writes ` +
								`<DEVSTACK_STATE_DIR>/stacks/<stack>/manifest.json. ` +
								`Pass \`manifestPath\` explicitly to silence this warning.`,
						);
						return;
					}
					const manifestDst = path.join(outDir, 'manifest.json');
					yield* Effect.tryPromise({
						try: async () => {
							await fs.mkdir(outDir, { recursive: true });
							const body = await fs.readFile(manifestSrc, 'utf-8');
							let existing: string | undefined;
							try {
								existing = await fs.readFile(manifestDst, 'utf-8');
							} catch {
								// missing — fall through to write
							}
							if (existing !== body) {
								await fs.writeFile(manifestDst, body, 'utf-8');
							}
						},
						catch: (cause) =>
							new CodegenError({
								emitter: 'dapp-kit',
								phase: 'write',
								message: `failed to copy manifest from ${manifestSrc} to ${manifestDst}: ${String(cause)}`,
								cause,
							}),
					});
				}
			}),
	});
};
