// DappKitConfigEmitter — covers the generated `dapp-kit-config.ts`
// shape: network/rpcUrl/mvrOverrides propagation, the
// `walletInitializers` toggle, and the skip-emit branch when sui isn't
// in the manifest yet (which the supervisor relies on during cold
// boot).

import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join as joinPath } from 'node:path';
import { Effect, Layer } from 'effect';
import { afterEach, beforeEach, describe, expect } from 'vitest';
import { it } from '@effect/vitest';
import { Identity } from '../../engine/identity.js';
import {
	AccountRegistry,
	AccountRegistryLive,
	CoinRegistryLive,
	EndpointRegistry,
	EndpointRegistryLive,
	PackageRegistry,
	PackageRegistryLive,
} from '../../engine/registries.js';
import { ExtrasLive } from '../../runtime/extras.js';
import { DappKitConfigEmitter } from './dapp-kit-config.js';
import type { CodegenContext } from '../define-emitter.js';

const IdentityLive = Layer.succeed(Identity, {
	app: 'test-app',
	stack: 'main',
	network: 'localnet',
});

const RegistriesLive = Layer.mergeAll(
	PackageRegistryLive,
	EndpointRegistryLive,
	AccountRegistryLive,
	CoinRegistryLive,
);

const seedSuiAndPackages = Effect.gen(function* () {
	const eps = yield* EndpointRegistry;
	const pkgs = yield* PackageRegistry;
	yield* eps.register({ name: 'sui-rpc', url: 'http://sui.test-app.localhost:9000', kind: 'rpc' });
	yield* pkgs.register({
		name: 'connect_four',
		packageId: '0xabc',
		mvrPlaceholder: '@local/connect_four',
	});
	yield* pkgs.register({
		name: 'arena',
		packageId: '0xdef',
		mvrPlaceholder: '@local/arena',
	});
});

const seedWalletEndpoint = Effect.gen(function* () {
	const eps = yield* EndpointRegistry;
	const accts = yield* AccountRegistry;
	yield* eps.register({ name: 'wallet-app', url: 'http://wallet.test-app.localhost:5180' });
	yield* accts.register({ name: 'alice', address: '0x1' });
});

describe('DappKitConfigEmitter', () => {
	let outputDir: string;
	beforeEach(() => {
		outputDir = mkdtempSync(joinPath(tmpdir(), 'devstack-dapp-kit-config-'));
	});
	afterEach(() => {
		rmSync(outputDir, { recursive: true, force: true });
	});

	const ctx = (): CodegenContext => ({ packages: [], outputDir });

	it.effect('emits dapp-kit-config.ts with network, rpcUrl, and sorted mvrOverrides', () =>
		Effect.gen(function* () {
			yield* seedSuiAndPackages;
			yield* DappKitConfigEmitter().emit(ctx());

			const body = readFileSync(joinPath(outputDir, 'dapp-kit-config.ts'), 'utf-8');
			expect(body).toContain('Generated by @mysten-incubation/devstack');
			expect(body).toContain("const network = \"localnet\" as const");
			expect(body).toContain("const rpcUrl = \"http://sui.test-app.localhost:9000\"");
			// mvr overrides sorted alphabetically by placeholder key
			const arenaIdx = body.indexOf('"@local/arena"');
			const connectFourIdx = body.indexOf('"@local/connect_four"');
			expect(arenaIdx).toBeGreaterThan(-1);
			expect(connectFourIdx).toBeGreaterThan(arenaIdx);
			expect(body).toContain('export const devstackDappKitConfig');
		}).pipe(Effect.provide(Layer.mergeAll(RegistriesLive, IdentityLive, ExtrasLive(undefined)))),
	);

	it.effect('embeds the wallet manifest when a wallet-app endpoint is registered', () =>
		Effect.gen(function* () {
			yield* seedSuiAndPackages;
			yield* seedWalletEndpoint;
			yield* DappKitConfigEmitter().emit(ctx());

			const body = readFileSync(joinPath(outputDir, 'dapp-kit-config.ts'), 'utf-8');
			// The adapter receives `app.wallet` with the URL we registered.
			expect(body).toContain('"url": "http://wallet.test-app.localhost:5180"');
			expect(body).toContain('createDevstackAdapterFromManifest');
			expect(body).toContain('devstackWalletInitializer');
		}).pipe(Effect.provide(Layer.mergeAll(RegistriesLive, IdentityLive, ExtrasLive(undefined)))),
	);

	it.effect('with enableBurnerWallet=false, emits an empty walletInitializers array', () =>
		Effect.gen(function* () {
			yield* seedSuiAndPackages;
			yield* DappKitConfigEmitter({ enableBurnerWallet: false }).emit(ctx());

			const body = readFileSync(joinPath(outputDir, 'dapp-kit-config.ts'), 'utf-8');
			expect(body).toContain('const walletInitializers: Array<never> = []');
			// Don't pull in dev-wallet imports if the wiring is off — apps
			// using their own wallets shouldn't transitively depend on it.
			expect(body).not.toContain('@mysten-incubation/dev-wallet');
		}).pipe(Effect.provide(Layer.mergeAll(RegistriesLive, IdentityLive, ExtrasLive(undefined)))),
	);

	it.effect('skips emit when no sui-rpc endpoint is registered yet (cold-boot path)', () =>
		Effect.gen(function* () {
			// Deliberately don't seed sui — the emitter must skip rather
			// than write a file that would fail at runtime.
			yield* DappKitConfigEmitter().emit(ctx());
			expect(existsSync(joinPath(outputDir, 'dapp-kit-config.ts'))).toBe(false);
		}).pipe(Effect.provide(Layer.mergeAll(RegistriesLive, IdentityLive, ExtrasLive(undefined)))),
	);
});
