// DappKitEmitter — emit a generated TS module that wires up dapp-kit
// against the resolved devstack manifest. Replaces the runtime
// `createDevstackDappKit(...)` path so apps can keep devstack as a
// pure dev-dep (the generated module imports only `@mysten/sui`,
// `@mysten/dapp-kit-core` / `-react`, and `@mysten-incubation/dev-wallet`
// — never `@mysten-incubation/devstack` at runtime).
//
// Manifest-driven: at emit time the emitter reads the resolved
// `CodegenContext.packages` (any `Package` / `KnownPackage` ref in the
// stack that didn't opt out via `{ codegen: false }`) to derive MVR
// overrides. The localnet RPC URL is also baked in — re-emit whenever
// the supervisor restarts on a different port.
//
// Flavors:
//   - `'core'` — for `@mysten/dapp-kit-core` (vanilla DAppKit).
//   - `'react'` — for `@mysten/dapp-kit-react` (registers the type so
//     `useDAppKit()` infers correctly).
//
// The emitted file is byte-stable for a given manifest input — the
// emitter sorts MVR entries alphabetically and uses a single
// indentation style. Re-emitting after no manifest change writes the
// same bytes, so file-watchers in dev mode don't trip spurious
// HMR cycles.

import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { Effect } from 'effect';
import { CodegenError } from '../errors.js';
import { defineEmitter, type CodegenContext, type Emitter } from '../define-emitter.js';

export type DappKitFlavor = 'core' | 'react';

export interface DappKitEmitterOptions {
	/** Which dapp-kit flavor to import from. Defaults to `'react'`. */
	readonly flavor?: DappKitFlavor;
	/** Localnet RPC URL to bake into the generated file. Defaults to
	 *  `'http://localhost:9000'` — matches the default sui-localnet
	 *  port. Override when the dev server proxies the RPC. */
	readonly localnetRpcUrl?: string;
	/** Enable the burner-wallet adapter wiring. Defaults to `true`.
	 *  Set `false` to emit a config that wires only the user's own
	 *  wallets. */
	readonly enableBurnerWallet?: boolean;
}

const FLAVOR_IMPORTS: Record<DappKitFlavor, { core: string; module: string }> = {
	core: { core: '@mysten/dapp-kit-core', module: '@mysten/dapp-kit-core' },
	react: { core: '@mysten/dapp-kit-core', module: '@mysten/dapp-kit-react' },
};

const renderMvrOverrides = (ctx: CodegenContext): string => {
	const entries = ctx.packages
		.map((p) => ({ key: p.mvrPlaceholder, value: p.packageId }))
		.sort((a, b) => a.key.localeCompare(b.key));
	if (entries.length === 0) return '{}';
	const lines = entries.map((e) => `\t${JSON.stringify(e.key)}: ${JSON.stringify(e.value)}`);
	return `{\n${lines.join(',\n')},\n}`;
};

const renderFile = (
	ctx: CodegenContext,
	opts: Required<DappKitEmitterOptions>,
): string => {
	const flavor = FLAVOR_IMPORTS[opts.flavor];
	const mvrOverrides = renderMvrOverrides(ctx);
	const registerBlock =
		opts.flavor === 'react'
			? `
declare module '@mysten/dapp-kit-react' {
\tinterface Register {
\t\tdAppKit: typeof dAppKit;
\t}
}
`
			: '';
	const adapterBlock = opts.enableBurnerWallet
		? `import { devWalletInitializer } from '@mysten-incubation/dev-wallet';
import { createDevstackAdapterFromManifest } from '@mysten-incubation/dev-wallet/adapters';

// Manifest snapshot — re-emitted alongside the rest of this file.
import manifestJson from './manifest.json' with { type: 'json' };

const adapter = createDevstackAdapterFromManifest(manifestJson);
const walletInitializers = adapter ? [devWalletInitializer({ adapters: [adapter] })] : [];
`
		: 'const walletInitializers = [];';
	return `// Generated by @mysten-incubation/devstack — do not edit by hand.
// Re-run \`pnpm dev\` (or the devstack supervisor that emitted this) to
// regenerate.

import { createDAppKit } from '${flavor.core}';
import { SuiGrpcClient } from '@mysten/sui/grpc';
${adapterBlock}
const localnetRpcUrl = ${JSON.stringify(opts.localnetRpcUrl)};
const mvrOverrides = ${mvrOverrides};

export const dAppKit = createDAppKit({
\tdefaultNetwork: 'localnet',
\tnetworks: ['localnet'],
\tcreateClient: (network) =>
\t\tnew SuiGrpcClient({
\t\t\tnetwork,
\t\t\tbaseUrl: localnetRpcUrl,
\t\t\tmvr: Object.keys(mvrOverrides).length > 0
\t\t\t\t? { overrides: { packages: mvrOverrides } }
\t\t\t\t: undefined,
\t\t}),
\tenableBurnerWallet: ${opts.enableBurnerWallet},
\twalletInitializers,
});
${registerBlock}`;
};

const writeFile = (
	outputPath: string,
	contents: string,
): Effect.Effect<void, CodegenError> =>
	Effect.tryPromise({
		try: async () => {
			await fs.mkdir(path.dirname(outputPath), { recursive: true });
			// Skip the write when the bytes already match — keeps watchers
			// (Vite HMR, tsc -b) from tripping on no-op regenerations.
			let existing: string | undefined;
			try {
				existing = await fs.readFile(outputPath, 'utf-8');
			} catch {
				// missing — fall through and write
			}
			if (existing === contents) return;
			await fs.writeFile(outputPath, contents, 'utf-8');
		},
		catch: (cause) =>
			new CodegenError({
				emitter: 'dapp-kit',
				phase: 'write',
				message: `failed to write ${outputPath}: ${String(cause)}`,
				cause,
			}),
	});

/** Build a `DappKitEmitter` plug-in instance. Drop into
 *  `Codegen({ emitters: [DappKitEmitter()] })` or surface alongside
 *  `BindingsEmitter`. */
export const DappKitEmitter = (opts: DappKitEmitterOptions = {}): Emitter => {
	const resolved: Required<DappKitEmitterOptions> = {
		flavor: opts.flavor ?? 'react',
		localnetRpcUrl: opts.localnetRpcUrl ?? 'http://localhost:9000',
		enableBurnerWallet: opts.enableBurnerWallet ?? true,
	};
	return defineEmitter({
		name: 'dapp-kit',
		emit: (ctx) =>
			Effect.gen(function* () {
				const outDir = path.join(ctx.outputDir, 'dapp-kit');
				const filePath = path.join(outDir, 'index.ts');
				const contents = renderFile(ctx, resolved);
				yield* writeFile(filePath, contents);
			}),
	});
};
