// DeepbookConfigEmitter — emits a typed `deepbookConfig` object the app
// spreads into `client.$extend(deepbook(deepbookConfig))`:
//
//   // src/transactions.ts (user code)
//   import { deepbook } from '@mysten/deepbook-v3';
//   import { deepbookConfig } from './generated/deepbook-config.js';
//
//   const client = new SuiGrpcClient({ ... }).$extend(deepbook({
//       ...deepbookConfig,
//       address: sender,
//   }));
//
// What's in the config:
//   - `packageIds`    — SCREAMING_SNAKE_CASE view consumed verbatim by
//                       `@mysten/deepbook-v3`'s `DeepBookOptions.packageIds`:
//                       DEEPBOOK_PACKAGE_ID, REGISTRY_ID, DEEP_TREASURY_ID,
//                       MARGIN_PACKAGE_ID, MARGIN_REGISTRY_ID,
//                       LIQUIDATION_PACKAGE_ID.
//   - `coins`         — symbol-keyed CoinMap. SUI + DEEP land first; the
//                       rest of the entries come from the CoinRegistry's
//                       sdkCoin projection. Margin-aware coins additionally
//                       carry `feed` + `currencyId` + `priceInfoObjectId`
//                       sourced from the PythStateRegistry.
//   - `pools`         — alias-keyed PoolMap. Each entry resolves
//                       base/quote coin types to their SDK symbol so
//                       the SDK can dial the coin map.
//   - `marginPools`   — symbol-keyed map from DeepbookMarginStateRegistry
//                       (each entry: `{ address, type }`).
//   - `pyth`          — `{ pythStateId, wormholeStateId }` from
//                       PythStateRegistry (when present).
//
// Skip-emit branch: when `services.deepbook` is absent from the manifest
// (cold boot, or a stack that simply doesn't run deepbook), nothing is
// written. Apps that don't need deepbook never see the file.
//
// Data sources: `gatherManifest()` only — no extras read, no chain RPC.
// Byte-stable output for the same input: re-emits hit the no-op write
// path in `writeIfChanged` and don't trip Vite's HMR.

import * as path from 'node:path';
import { Effect } from 'effect';
import { ExtrasResolved } from '../../engine/extras.js';
import { gatherManifest } from '../../runtime/service.js';
import { defineEmitter, type Emitter } from '../define-emitter.js';
import { writeIfChanged } from '../helpers.js';

const HEADER = `// Generated by @mysten-incubation/devstack — do not edit by hand.
// Re-run \`pnpm dev\` (or the devstack supervisor that emitted this) to
// regenerate.
`;

interface CoinView {
	readonly symbol: string;
	readonly address: string;
	readonly type: string;
	readonly scalar: number;
	readonly feed?: string;
	readonly priceInfoObjectId?: string;
	readonly currencyId?: string;
}

interface PoolView {
	readonly alias: string;
	readonly address: string;
	readonly baseCoin: string;
	readonly quoteCoin: string;
}

interface MarginPoolView {
	readonly symbol: string;
	readonly address: string;
	readonly type: string;
}

const SUI_COIN_TYPE = '0x2::sui::SUI';

/** Derive the SDK symbol for a coin entry. Prefers the published
 *  `symbol` (set by the coin-auto-discovery path or by callers who pin
 *  it); falls back to the registry `name` upper-cased when the entry
 *  lacks a chain-derived symbol. */
const symbolFromCoinEntry = (name: string, symbol?: string): string =>
	(symbol ?? name).toUpperCase();

/** Render a single CoinMap entry. The optional Pyth fields are emitted
 *  only when present so the output stays compact for non-margin coins. */
const renderCoin = (coin: CoinView): string => {
	const lines: Array<string> = [
		`\t\taddress: ${JSON.stringify(coin.address)},`,
		`\t\ttype: ${JSON.stringify(coin.type)},`,
		`\t\tscalar: ${coin.scalar},`,
	];
	if (coin.feed !== undefined) lines.push(`\t\tfeed: ${JSON.stringify(coin.feed)},`);
	if (coin.currencyId !== undefined)
		lines.push(`\t\tcurrencyId: ${JSON.stringify(coin.currencyId)},`);
	if (coin.priceInfoObjectId !== undefined)
		lines.push(`\t\tpriceInfoObjectId: ${JSON.stringify(coin.priceInfoObjectId)},`);
	return `\t${JSON.stringify(coin.symbol)}: {\n${lines.join('\n')}\n\t}`;
};

const renderCoins = (coins: ReadonlyArray<CoinView>): string => {
	if (coins.length === 0) return '{}';
	return `{\n${coins.map(renderCoin).join(',\n')},\n}`;
};

const renderPool = (pool: PoolView): string =>
	`\t${JSON.stringify(pool.alias)}: { address: ${JSON.stringify(pool.address)}, baseCoin: ${JSON.stringify(pool.baseCoin)}, quoteCoin: ${JSON.stringify(pool.quoteCoin)} }`;

const renderPools = (pools: ReadonlyArray<PoolView>): string => {
	if (pools.length === 0) return '{}';
	return `{\n${pools.map(renderPool).join(',\n')},\n}`;
};

const renderMarginPool = (mp: MarginPoolView): string =>
	`\t${JSON.stringify(mp.symbol)}: { address: ${JSON.stringify(mp.address)}, type: ${JSON.stringify(mp.type)} }`;

const renderMarginPools = (marginPools: ReadonlyArray<MarginPoolView>): string => {
	if (marginPools.length === 0) return '{}';
	return `{\n${marginPools.map(renderMarginPool).join(',\n')},\n}`;
};

interface ConfigRenderArgs {
	readonly packageIds: {
		readonly DEEPBOOK_PACKAGE_ID: string;
		readonly REGISTRY_ID: string;
		readonly DEEP_TREASURY_ID: string;
		readonly MARGIN_PACKAGE_ID?: string;
		readonly MARGIN_REGISTRY_ID?: string;
		readonly LIQUIDATION_PACKAGE_ID?: string;
	};
	readonly coins: ReadonlyArray<CoinView>;
	readonly pools: ReadonlyArray<PoolView>;
	readonly marginPools: ReadonlyArray<MarginPoolView>;
	readonly pyth?: { readonly pythStateId: string; readonly wormholeStateId: string };
}

const renderPackageIds = (ids: ConfigRenderArgs['packageIds']): string => {
	const lines: Array<string> = [
		`\t\tDEEPBOOK_PACKAGE_ID: ${JSON.stringify(ids.DEEPBOOK_PACKAGE_ID)},`,
		`\t\tREGISTRY_ID: ${JSON.stringify(ids.REGISTRY_ID)},`,
		`\t\tDEEP_TREASURY_ID: ${JSON.stringify(ids.DEEP_TREASURY_ID)},`,
	];
	if (ids.MARGIN_PACKAGE_ID !== undefined)
		lines.push(`\t\tMARGIN_PACKAGE_ID: ${JSON.stringify(ids.MARGIN_PACKAGE_ID)},`);
	if (ids.MARGIN_REGISTRY_ID !== undefined)
		lines.push(`\t\tMARGIN_REGISTRY_ID: ${JSON.stringify(ids.MARGIN_REGISTRY_ID)},`);
	if (ids.LIQUIDATION_PACKAGE_ID !== undefined)
		lines.push(`\t\tLIQUIDATION_PACKAGE_ID: ${JSON.stringify(ids.LIQUIDATION_PACKAGE_ID)},`);
	return `{\n${lines.join('\n')}\n\t}`;
};

const renderConfig = (args: ConfigRenderArgs): string => {
	const pythBlock =
		args.pyth !== undefined
			? `\n\tpyth: {\n\t\tpythStateId: ${JSON.stringify(args.pyth.pythStateId)},\n\t\twormholeStateId: ${JSON.stringify(args.pyth.wormholeStateId)},\n\t},`
			: '';

	return `${HEADER}
// Typed deepbook configuration. Spread into \`deepbook({...})\` from
// \`@mysten/deepbook-v3\` and pass to \`client.$extend(...)\`:
//
//   import { deepbook } from '@mysten/deepbook-v3';
//   import { deepbookConfig } from './generated/deepbook-config.js';
//
//   const dbk = client.$extend(deepbook({ ...deepbookConfig, address: sender }));
//
// The shapes mirror \`@mysten/deepbook-v3\`'s \`CoinMap\` / \`PoolMap\` /
// \`MarginPoolMap\` / \`DeepbookPackageIds\` exports verbatim — pass any
// individual field through to \`DeepBookClient\` if the spread isn't the
// right ergonomic fit for the call site.

export const deepbookConfig = {
\tpackageIds: ${renderPackageIds(args.packageIds)},
\tcoins: ${renderCoins(args.coins)},
\tpools: ${renderPools(args.pools)},
\tmarginPools: ${renderMarginPools(args.marginPools)},${pythBlock}
} as const;

export type DeepbookConfig = typeof deepbookConfig;
`;
};

/** Build a `DeepbookConfigEmitter` plug-in instance. Drop into
 *  `Codegen({ emitters: [DeepbookConfigEmitter()] })` or — typically —
 *  let `Codegen()`'s defaults register it.
 *
 *  Skips emit when the resolved manifest has no `services.deepbook`
 *  entry (cold boot, or a stack that doesn't run deepbook). The
 *  emitter is safe to keep in the default emitter list for every
 *  consumer; non-deepbook stacks just produce no file. */
export const DeepbookConfigEmitter = (): Emitter =>
	defineEmitter({
		name: 'deepbook-config',
		emit: (ctx) =>
			Effect.gen(function* () {
				const extras = yield* yield* ExtrasResolved;
				const data = yield* gatherManifest(extras);

				const deepbook = data.services.deepbook;
				if (deepbook === undefined) {
					// Stacks without deepbook don't get a `deepbook-config.ts`.
					// Logged at info — not a warning — because the absence is
					// the expected steady state for non-deepbook consumers.
					yield* Effect.logInfo(
						`DeepbookConfigEmitter: no services.deepbook in manifest; skipping emit.`,
					);
					return;
				}

				// packageIds: required (DEEPBOOK / REGISTRY / DEEP_TREASURY)
				// + optional (MARGIN / LIQUIDATION) when the margin facade
				// is in the stack. The local-deploy primitive captures the
				// minted DEEP TreasuryCap and exposes its id as
				// `pkg.captured.deepTreasuryId`; the manifest's deepbook
				// package entry surfaces it via captured.
				const deepbookPkg = data.packages.deepbook as
					| { id: string; captured?: Record<string, unknown> }
					| undefined;
				const deepTreasuryId =
					typeof deepbookPkg?.captured?.deepTreasuryId === 'string'
						? (deepbookPkg.captured.deepTreasuryId as string)
						: undefined;
				if (deepTreasuryId === undefined) {
					// Mirrors the dapp-kit-config skip-emit pattern: emit
					// nothing rather than write a file that would fail at
					// runtime. The next supervisor cycle will catch up once
					// the local-deploy publish captures the DEEP TreasuryCap.
					yield* Effect.logWarning(
						`DeepbookConfigEmitter: skipping emit — services.deepbook is set but ` +
							`packages.deepbook.captured.deepTreasuryId is missing. Will retry on the next cycle.`,
					);
					return;
				}

				const packageIds: ConfigRenderArgs['packageIds'] = {
					DEEPBOOK_PACKAGE_ID: deepbook.packageId,
					REGISTRY_ID:
						deepbook.registryId ??
						// Fallback to the captured registry id (the local-deploy
						// publish captures it under `pkg.captured.registryId`).
						(typeof deepbookPkg?.captured?.registryId === 'string'
							? (deepbookPkg.captured.registryId as string)
							: ''),
					DEEP_TREASURY_ID: deepTreasuryId,
					...(deepbook.margin !== undefined
						? {
								MARGIN_PACKAGE_ID: deepbook.margin.packageId,
								MARGIN_REGISTRY_ID: deepbook.margin.registryId,
								LIQUIDATION_PACKAGE_ID: deepbook.margin.liquidationPackageId,
							}
						: {}),
				};

				// Coins: project the CoinRegistry's symbol-aware shape into
				// the SDK CoinMap. SUI ships in every stack and isn't in the
				// CoinRegistry by default, so we seed it explicitly. DEEP
				// comes from the local-deploy publish (the deepbook package
				// re-exports the token sub-package; its address is the
				// deepbook package id itself).
				const coinEntries: Array<CoinView> = [];
				const pythPriceInfoIds = data.services.pyth?.priceInfoObjectIds ?? {};
				const pythFeedsByLabel = data.services.pyth?.feeds ?? {};

				const findFeedForLabel = (label: string): string | undefined => pythFeedsByLabel[label];
				const findPriceInfoForFeed = (feedId: string | undefined): string | undefined =>
					feedId !== undefined ? pythPriceInfoIds[feedId] : undefined;

				// SUI first.
				const suiFeed = findFeedForLabel('SUI');
				coinEntries.push({
					symbol: 'SUI',
					address: '0x0000000000000000000000000000000000000000000000000000000000000002',
					type: SUI_COIN_TYPE,
					scalar: 1_000_000_000,
					...(suiFeed !== undefined ? { feed: suiFeed } : {}),
					...(findPriceInfoForFeed(suiFeed) !== undefined
						? { priceInfoObjectId: findPriceInfoForFeed(suiFeed)! }
						: {}),
				});

				// DEEP — local-deploy bakes the `token` sub-package under the
				// deepbook package address. Same as wallet's existing manual
				// projection. Only emitted when we have a deepbook package id.
				const deepFeed = findFeedForLabel('DEEP');
				coinEntries.push({
					symbol: 'DEEP',
					address: deepbook.packageId,
					type: `${deepbook.packageId}::deep::DEEP`,
					scalar: 1_000_000,
					...(deepFeed !== undefined ? { feed: deepFeed } : {}),
					...(findPriceInfoForFeed(deepFeed) !== undefined
						? { priceInfoObjectId: findPriceInfoForFeed(deepFeed)! }
						: {}),
				});

				// Then the rest of the user-published coins. Skip SUI/DEEP
				// duplicates if they slipped through. Symbol resolution:
				// prefer the registry's `symbol` field; fall back to
				// `name.toUpperCase()`.
				const seenSymbols = new Set<string>(['SUI', 'DEEP']);
				for (const [registryName, c] of Object.entries(data.coins)) {
					if (c.type === SUI_COIN_TYPE) continue;
					if (c.type === `${deepbook.packageId}::deep::DEEP`) continue;
					const symbol = symbolFromCoinEntry(registryName, c.symbol);
					if (seenSymbols.has(symbol)) continue;
					seenSymbols.add(symbol);
					const address = c.type.split('::')[0] ?? c.sdkCoin.address;
					const feed = findFeedForLabel(symbol);
					const priceInfo = findPriceInfoForFeed(feed);
					coinEntries.push({
						symbol,
						address,
						type: c.type,
						scalar: c.sdkCoin.scalar,
						...(feed !== undefined ? { feed } : {}),
						...(priceInfo !== undefined ? { priceInfoObjectId: priceInfo } : {}),
					});
				}

				// Pools: alias-keyed. The pool entry's baseType/quoteType are
				// fully-qualified Move types; resolve each to the SDK symbol
				// we just folded into `coinEntries`. A pool whose base/quote
				// coin isn't in the coin map is a manifest-projection bug —
				// skip the pool (rather than crash) and log so the next
				// codegen cycle sees the remaining entries even if one is
				// malformed.
				const symbolByType = new Map<string, string>();
				for (const c of coinEntries) symbolByType.set(c.type, c.symbol);
				const poolEntries: Array<PoolView> = [];
				for (const [alias, p] of Object.entries(deepbook.pools)) {
					const baseSymbol = symbolByType.get(p.baseType);
					const quoteSymbol = symbolByType.get(p.quoteType);
					if (baseSymbol === undefined || quoteSymbol === undefined) {
						yield* Effect.logWarning(
							`DeepbookConfigEmitter: pool '${alias}' has base/quote types not in the coin map (${p.baseType} / ${p.quoteType}); skipping.`,
						);
						continue;
					}
					poolEntries.push({
						alias,
						address: p.poolId,
						baseCoin: baseSymbol,
						quoteCoin: quoteSymbol,
					});
				}

				// Margin pools: symbol-keyed via the margin pool's asset type
				// reverse-mapped through the coin map. A margin pool whose
				// asset isn't in the coin map is also a projection bug — same
				// log-and-skip treatment as pools above.
				const marginPoolEntries: Array<MarginPoolView> = [];
				if (deepbook.margin !== undefined) {
					for (const mp of deepbook.margin.marginPools) {
						const symbol = symbolByType.get(mp.assetType);
						if (symbol === undefined) {
							yield* Effect.logWarning(
								`DeepbookConfigEmitter: margin pool '${mp.label}' has assetType not in the coin map (${mp.assetType}); skipping.`,
							);
							continue;
						}
						marginPoolEntries.push({
							symbol,
							address: mp.marginPoolId,
							type: mp.assetType,
						});
					}
				}

				const pyth = data.services.pyth;
				const pythBlock =
					pyth?.pythStateId !== undefined && pyth.wormholeStateId !== undefined
						? { pythStateId: pyth.pythStateId, wormholeStateId: pyth.wormholeStateId }
						: undefined;

				const contents = renderConfig({
					packageIds,
					coins: coinEntries,
					pools: poolEntries,
					marginPools: marginPoolEntries,
					...(pythBlock !== undefined ? { pyth: pythBlock } : {}),
				});

				yield* writeIfChanged(path.join(ctx.outputDir, 'deepbook-config.ts'), contents, {
					emitter: 'deepbook-config',
				});
			}),
	});
