// StackHandleEmitter — emits typed handles the app imports from
// generated code instead of consuming the raw manifest:
//
//   <outputDir>/accounts.ts   — `export const accounts = { alice: '0x…', … } as const`
//   <outputDir>/services.ts   — `export const services = { sui: {...}, … } as const`
//   <outputDir>/extras.ts     — `export const extras = { … } as const`  (literal-typed)
//   <outputDir>/captured.ts   — `export const captured = { mock_usdc: { treasuryCapId: '0x…', … }, … } as const`
//   <outputDir>/packages.ts   — `export const packages = { connect_four: { id: '0x…', mvr?: '@local/…' } } as const`
//                                Escape hatch: prefer MVR-resolved targets (which dApp-Kit
//                                handles transparently) and Move bindings over raw ids.
//                                Reach for `packages.<name>.id` only for things MVR can't
//                                express (struct type strings, error labels).
//   <outputDir>/coins.ts      — `export const coins = { mUSDC: { type, symbol, decimals, treasuryCapId?, metadataId?, ... } } as const`
//                                Populated by coin auto-discovery on every publish. Apps
//                                read `coins.mUSDC.treasuryCapId` for mint flows, `coins.mUSDC.type`
//                                for tx-builder typeArguments, `coins.mUSDC.decimals` for UI
//                                formatting.
//
// Why these handles instead of `import { manifest } from ...`:
//   - Apps reach for semantically-named values (`accounts.alice`,
//     `services.sui.rpc.url`, `extras.openLobbyId`,
//     `captured.mock_usdc.treasuryCapId`), not raw manifest traversals.
//   - The values are literal-typed (`as const`), so TS narrows
//     `accounts.alice` to its exact string at every consumer.
//   - The manifest stays a dev-only artifact — never imported by app
//     code, never bundled into a production build.
//
// Data sources: `gatherManifest()` (PackageRegistry, EndpointRegistry,
// AccountRegistry, CoinRegistry, Identity) plus the `Extras` service
// (resolved on each emit). Byte-stable output for the same input —
// re-emits hit the no-op write path and don't trip Vite's HMR.

import * as path from 'node:path';
import { Effect } from 'effect';
import { ExtrasResolved } from '../../engine/extras.js';
import { gatherManifest } from '../../runtime/service.js';
import { jsonBigintReplacer } from '../../engine/json-bigint.js';
import { defineEmitter, type Emitter } from '../define-emitter.js';
import { writeIfChanged } from '../helpers.js';

const HEADER = `// Generated by @mysten-incubation/devstack — do not edit by hand.
// Re-run \`pnpm dev\` (or the devstack supervisor that emitted this) to
// regenerate.
`;

const jsonLiteral = (value: unknown): string => JSON.stringify(value, jsonBigintReplacer, '\t');

const EXTRAS_BANNER = `// generated — DO NOT COMMIT (contains app.extras values)`;

const renderAccounts = (accounts: Record<string, { address: string }>): string => {
	const lines = Object.entries(accounts)
		.sort(([a], [b]) => a.localeCompare(b))
		.map(([name, { address }]) => `\t${JSON.stringify(name)}: ${JSON.stringify(address)},`);
	const body = lines.length === 0 ? '{}' : `{\n${lines.join('\n')}\n}`;
	return `${HEADER}
// Named account → address. Populated from \`Account('name')\` refs in
// devstack.config.ts.

export const accounts = ${body} as const;

export type AccountName = keyof typeof accounts;
`;
};

const renderServices = (services: Record<string, unknown>): string => {
	const body = jsonLiteral(services);
	return `${HEADER}
// Resolved service endpoints (sui, walrus, seal, deepbook) keyed by
// service name. Surfaced as the input to dapp-kit / walrus-client /
// seal-client wiring in user code.

export const services = ${body} as const;

export type Services = typeof services;
`;
};

const renderExtras = (extras: Record<string, unknown>): string => {
	const body = jsonLiteral(extras);
	return `${EXTRAS_BANNER}
${HEADER}
// App extras — whatever the user surfaced via \`devstack({ extras })\`.
// Literal-typed so consumers see the exact shape, not
// \`Record<string, unknown>\`.

export const extras = ${body} as const;

export type Extras = typeof extras;
`;
};

const renderCaptured = (
	packages: Record<string, { captured?: Record<string, unknown> }>,
): string => {
	const entries = Object.entries(packages)
		.filter(([, p]) => p.captured !== undefined && Object.keys(p.captured).length > 0)
		.sort(([a], [b]) => a.localeCompare(b));
	const body =
		entries.length === 0
			? '{}'
			: `{\n${entries
					.map(([name, p]) => `\t${JSON.stringify(name)}: ${jsonLiteral(p.captured)},`)
					.join('\n')}\n}`;
	return `${HEADER}
// Per-package \`captured\` ids — TreasuryCap, MetadataId, BalanceManager,
// etc., surfaced via \`Package({ capture: { … } })\` in
// devstack.config.ts. Use when an app needs to reach for a specific
// object id rather than expressing the call through MVR.

export const captured = ${body} as const;
`;
};

const renderCoins = (
	coins: Record<string, Record<string, unknown>>,
): string => {
	const entries = Object.entries(coins).sort(([a], [b]) => a.localeCompare(b));
	const body =
		entries.length === 0
			? '{}'
			: `{\n${entries.map(([name, entry]) => `\t${JSON.stringify(name)}: ${jsonLiteral(entry)},`).join('\n')}\n}`;
	return `${HEADER}
// Per-coin metadata — coin type + decimals + sdkCoin + optional discovery
// fields (\`symbol\`, \`displayName\`, \`iconUrl\`, \`treasuryCapId\`,
// \`metadataId\`, \`packageId\`). Populated by coin auto-discovery on every
// \`Package(...)\` publish; the symbol key matches what \`Coin('SYMBOL')\`
// resolves to at runtime.

export const coins = ${body} as const;

export type CoinName = keyof typeof coins;
`;
};

const renderPackages = (
	packages: Record<string, { id: string; upgradeCapId?: string; mvr?: string }>,
): string => {
	const entries = Object.entries(packages).sort(([a], [b]) => a.localeCompare(b));
	const body =
		entries.length === 0
			? '{}'
			: `{\n${entries
					.map(([name, p]) => {
						const fields: Array<string> = [`id: ${JSON.stringify(p.id)}`];
						if (p.upgradeCapId !== undefined)
							fields.push(`upgradeCapId: ${JSON.stringify(p.upgradeCapId)}`);
						if (p.mvr !== undefined) fields.push(`mvr: ${JSON.stringify(p.mvr)}`);
						return `\t${JSON.stringify(name)}: { ${fields.join(', ')} },`;
					})
					.join('\n')}\n}`;
	return `${HEADER}
// Per-package metadata — \`id\`, optional \`upgradeCapId\`, optional \`mvr\`
// placeholder. Escape hatch for code that needs raw ids (struct type
// strings, error labels, raw RPC calls). The preferred paths are MVR
// targets (\`tx.moveCall({ target: '@local/foo::bar::baz' })\` — dApp-Kit
// resolves via the baked-in mvr overrides) and Move bindings from
// \`./bindings/<pkg>/\`.

export const packages = ${body} as const;

export type PackageName = keyof typeof packages;
`;
};

/** Build a `StackHandleEmitter` plug-in instance. Drop into
 *  `Codegen({ emitters: [StackHandleEmitter()] })` or — typically —
 *  let `Codegen()`'s defaults register it. */
export const StackHandleEmitter = (): Emitter =>
	defineEmitter({
		name: 'stack-handle',
		emit: (ctx) =>
			Effect.gen(function* () {
				const extras = yield* yield* ExtrasResolved;
				const data = yield* gatherManifest(extras);

				yield* writeIfChanged(
					path.join(ctx.outputDir, 'accounts.ts'),
					renderAccounts(data.accounts),
					{ emitter: 'stack-handle' },
				);
				yield* writeIfChanged(
					path.join(ctx.outputDir, 'services.ts'),
					renderServices(data.services),
					{ emitter: 'stack-handle' },
				);
				yield* writeIfChanged(
					path.join(ctx.outputDir, 'extras.ts'),
					renderExtras(data.app.extras),
					{ emitter: 'stack-handle', mode: 0o600 },
				);
				yield* writeIfChanged(
					path.join(ctx.outputDir, 'captured.ts'),
					renderCaptured(data.packages),
					{ emitter: 'stack-handle' },
				);
				yield* writeIfChanged(
					path.join(ctx.outputDir, 'packages.ts'),
					renderPackages(data.packages),
					{ emitter: 'stack-handle' },
				);
				yield* writeIfChanged(
					path.join(ctx.outputDir, 'coins.ts'),
					renderCoins(data.coins as Record<string, Record<string, unknown>>),
					{ emitter: 'stack-handle' },
				);
			}),
	});
