// StackHandleEmitter — covers the `extras.ts` propagation surface that
// last week's fix (commit 1daec503) corrected, plus the byte-stable
// re-emit invariant the file's docstring promises ("re-emits hit the
// no-op write path and don't trip Vite's HMR"). The render branches
// (renderAccounts / renderExtras / renderCaptured / renderPackages) are
// private, so we drive the emitter end-to-end via `emit(ctx)` against a
// tmpdir and inspect the written files.

import { mkdtempSync, readFileSync, rmSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join as joinPath } from 'node:path';
import { Effect, Layer } from 'effect';
import { afterEach, beforeEach, describe, expect } from 'vitest';
import { it } from '@effect/vitest';
import { Identity } from '../../engine/identity.js';
import {
	AccountRegistry,
	AccountRegistryLive,
	CoinRegistryLive,
	EndpointRegistryLive,
	PackageRegistry,
	PackageRegistryLive,
} from '../../engine/registries.js';
import { ExtrasLive } from '../../runtime/extras.js';
import { StackHandleEmitter } from './stack-handle.js';
import type { CodegenContext } from '../define-emitter.js';

const IdentityLive = Layer.succeed(Identity, {
	app: 'test-app',
	stack: 'main',
	network: 'localnet',
});

const RegistriesLive = Layer.mergeAll(
	PackageRegistryLive,
	EndpointRegistryLive,
	AccountRegistryLive,
	CoinRegistryLive,
);

const seedRegistries = Effect.gen(function* () {
	const pkgs = yield* PackageRegistry;
	const accts = yield* AccountRegistry;
	yield* pkgs.register({
		name: 'connect_four',
		packageId: '0xabc',
		mvrPlaceholder: '@local/connect_four',
		captured: { treasuryCap: '0x111', metadataId: '0x222' },
	});
	yield* pkgs.register({
		name: 'arena',
		packageId: '0xdef',
		// no mvr placeholder, no captured — exercise the optional branches
	});
	yield* accts.register({ name: 'alice', address: '0x1' });
	yield* accts.register({ name: 'bob', address: '0x2' });
});

describe('StackHandleEmitter', () => {
	let outputDir: string;
	beforeEach(() => {
		outputDir = mkdtempSync(joinPath(tmpdir(), 'devstack-stack-handle-'));
	});
	afterEach(() => {
		rmSync(outputDir, { recursive: true, force: true });
	});

	const ctx = (): CodegenContext => ({ packages: [], outputDir });

	it.effect('emits accounts.ts, services.ts, extras.ts, captured.ts, packages.ts', () =>
		Effect.gen(function* () {
			yield* seedRegistries;
			yield* StackHandleEmitter().emit(ctx());

			const accountsPath = joinPath(outputDir, 'accounts.ts');
			const servicesPath = joinPath(outputDir, 'services.ts');
			const extrasPath = joinPath(outputDir, 'extras.ts');
			const capturedPath = joinPath(outputDir, 'captured.ts');
			const packagesPath = joinPath(outputDir, 'packages.ts');

			const accounts = readFileSync(accountsPath, 'utf-8');
			const services = readFileSync(servicesPath, 'utf-8');
			const extras = readFileSync(extrasPath, 'utf-8');
			const captured = readFileSync(capturedPath, 'utf-8');
			const packages = readFileSync(packagesPath, 'utf-8');

			// Each file carries the generated-header marker so a cleanup tool
			// (and a reader scanning the file) can see it's machine-written.
			for (const body of [accounts, services, extras, captured, packages]) {
				expect(body).toContain('Generated by @mysten-incubation/devstack');
			}

			expect(accounts).toContain('"alice": "0x1"');
			expect(accounts).toContain('"bob": "0x2"');
			expect(accounts).toContain('as const');
			expect(accounts).toContain('export type AccountName = keyof typeof accounts');

			expect(packages).toContain('"arena": { id: "0xdef" }');
			// connect_four has mvr; arena does not — keep the mvr field
			// conditional so consumers see the exact present-only shape.
			expect(packages).toContain('mvr: "@local/connect_four"');
			expect(packages.includes('"arena": { id: "0xdef", mvr:')).toBe(false);

			expect(captured).toContain('"connect_four"');
			expect(captured).toContain('"treasuryCap": "0x111"');
			// arena has no captured — must NOT appear in captured.ts.
			expect(captured).not.toContain('"arena"');

			// `extras.ts` is sensitive (carries user-supplied app.extras).
			// Chmod 0o600 + DO-NOT-COMMIT banner. The non-sensitive
			// siblings keep 0o644.
			expect(extras.startsWith('// generated — DO NOT COMMIT (contains app.extras values)')).toBe(
				true,
			);
			expect(statSync(extrasPath).mode & 0o777).toBe(0o600);
			for (const p of [accountsPath, servicesPath, capturedPath, packagesPath]) {
				expect(statSync(p).mode & 0o777).toBe(0o644);
			}
		}).pipe(Effect.provide(Layer.mergeAll(RegistriesLive, IdentityLive, ExtrasLive(undefined)))),
	);

	it.effect('propagates the resolved Extras blob into extras.ts (literal-typed)', () =>
		Effect.gen(function* () {
			yield* seedRegistries;
			yield* StackHandleEmitter().emit(ctx());

			const extras = readFileSync(joinPath(outputDir, 'extras.ts'), 'utf-8');
			// The fix in commit 1daec503 — extras must arrive in the emitted
			// file. Before the fix, the resolution happened in the wrong
			// scope and the value was dropped.
			expect(extras).toContain('"openLobbyId": "0xfeed"');
			expect(extras).toContain('"matchmaker": "0xbeef"');
			expect(extras).toContain('as const');
			expect(extras).toContain('export type Extras = typeof extras');
		}).pipe(
			Effect.provide(
				Layer.mergeAll(
					RegistriesLive,
					IdentityLive,
					ExtrasLive({ openLobbyId: '0xfeed', matchmaker: '0xbeef' }),
				),
			),
		),
	);

	it.live('re-emit with identical inputs leaves file mtime untouched (no-op write)', () =>
		Effect.gen(function* () {
			yield* seedRegistries;
			yield* StackHandleEmitter().emit(ctx());

			// First emit landed — capture mtime of one file we'd re-emit.
			const accountsPath = joinPath(outputDir, 'accounts.ts');
			const beforeMtime = statSync(accountsPath).mtimeMs;

			// Wait a beat so a write would produce a measurably different
			// mtime. 50ms is enough on every filesystem we ship to.
			// `it.live` uses the real Clock so sleep actually advances.
			yield* Effect.sleep('50 millis');

			yield* StackHandleEmitter().emit(ctx());
			const afterMtime = statSync(accountsPath).mtimeMs;

			expect(afterMtime).toBe(beforeMtime);
		}).pipe(Effect.provide(Layer.mergeAll(RegistriesLive, IdentityLive, ExtrasLive(undefined)))),
	);

	it.effect('renders an empty accounts.ts when no accounts are registered', () =>
		Effect.gen(function* () {
			yield* StackHandleEmitter().emit(ctx());
			const accounts = readFileSync(joinPath(outputDir, 'accounts.ts'), 'utf-8');
			expect(accounts).toContain('export const accounts = {} as const');
		}).pipe(Effect.provide(Layer.mergeAll(RegistriesLive, IdentityLive, ExtrasLive(undefined)))),
	);
});
