// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

import { defineChain } from 'viem';
import type { Chain as ViemChain } from 'viem';
import { FINALITY_BY_CHAIN } from './finality.js';
import type { ChainKey, EvmChainDefinition } from './types.js';

/**
 * CCTP v2 EVM contract addresses. Circle deploys the same addresses on every EVM chain,
 * with EDGE mainnet as the documented exception.
 * Source: https://developers.circle.com/cctp/evm-smart-contracts (fetched 2026-10-01).
 */
const MAINNET_TOKEN_MESSENGER_V2 = '0x28b5a0e9C621a5BadaA536219b3a228C8168cf5d' as const;
const MAINNET_MESSAGE_TRANSMITTER_V2 = '0x81D40F21F12A8F0E3252Bccb954D722d4c464B64' as const;
const TESTNET_TOKEN_MESSENGER_V2 = '0x8FE6B999Dc680CcFDD5Bf7EB0974218be2542DAA' as const;
const TESTNET_MESSAGE_TRANSMITTER_V2 = '0xE737e5cEBEEBa77EFE34D4aa090756590b1CE275' as const;

interface EvmSpec {
	key: ChainKey;
	name: string;
	domain: number;
	chainId: number;
	usdc: `0x${string}`;
	rpcUrls: string[];
	explorerUrl: string;
	nativeCurrency: { name: string; symbol: string; decimals: number };
	fastTransferAsSource: boolean;
	isTestnet: boolean;
	tokenMessengerV2?: `0x${string}`;
	messageTransmitterV2?: `0x${string}`;
}

const ETH = { name: 'Ether', symbol: 'ETH', decimals: 18 };

function evm(spec: EvmSpec): EvmChainDefinition {
	const viemChain: ViemChain = defineChain({
		id: spec.chainId,
		name: spec.name,
		nativeCurrency: spec.nativeCurrency,
		rpcUrls: { default: { http: spec.rpcUrls } },
		blockExplorers: { default: { name: 'Explorer', url: spec.explorerUrl } },
		testnet: spec.isTestnet,
	});

	return {
		ecosystem: 'evm',
		key: spec.key,
		name: spec.name,
		domain: spec.domain,
		chainId: spec.chainId,
		isTestnet: spec.isTestnet,
		fastTransferAsSource: spec.fastTransferAsSource,
		explorerUrl: spec.explorerUrl,
		rpcUrls: spec.rpcUrls,
		finality: FINALITY_BY_CHAIN[spec.key],
		viemChain,
		usdcAddress: spec.usdc,
		tokenMessengerV2:
			spec.tokenMessengerV2 ??
			(spec.isTestnet ? TESTNET_TOKEN_MESSENGER_V2 : MAINNET_TOKEN_MESSENGER_V2),
		messageTransmitterV2:
			spec.messageTransmitterV2 ??
			(spec.isTestnet ? TESTNET_MESSAGE_TRANSMITTER_V2 : MAINNET_MESSAGE_TRANSMITTER_V2),
	};
}

/**
 * Mainnet registry. Chain ids, USDC addresses and RPC endpoints were verified against
 * Circle's docs and live `eth_getCode` probes on 2026-10-01. BNB Smart Chain (domain 17)
 * is intentionally absent: it only carries USYC on CCTP v2, not USDC.
 */
export const EVM_MAINNET_CHAINS: EvmChainDefinition[] = [
	evm({
		key: 'ethereum',
		name: 'Ethereum',
		domain: 0,
		chainId: 1,
		usdc: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
		rpcUrls: [
			'https://ethereum-rpc.publicnode.com',
			'https://eth.drpc.org',
			'https://eth-mainnet.g.alchemy.com/public',
		],
		explorerUrl: 'https://etherscan.io',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: false,
	}),
	evm({
		key: 'avalanche',
		name: 'Avalanche',
		domain: 1,
		chainId: 43114,
		usdc: '0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E',
		rpcUrls: ['https://api.avax.network/ext/bc/C/rpc', 'https://1rpc.io/avax/c'],
		explorerUrl: 'https://snowtrace.io',
		nativeCurrency: { name: 'Avalanche', symbol: 'AVAX', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: false,
	}),
	evm({
		key: 'optimism',
		name: 'OP Mainnet',
		domain: 2,
		chainId: 10,
		usdc: '0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85',
		rpcUrls: [
			'https://mainnet.optimism.io',
			'https://optimism.drpc.org',
			'https://optimism-rpc.publicnode.com',
		],
		explorerUrl: 'https://optimistic.etherscan.io',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: false,
	}),
	evm({
		key: 'arbitrum',
		name: 'Arbitrum',
		domain: 3,
		chainId: 42161,
		usdc: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831',
		rpcUrls: ['https://arb1.arbitrum.io/rpc', 'https://arbitrum.drpc.org'],
		explorerUrl: 'https://arbiscan.io',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: false,
	}),
	evm({
		key: 'base',
		name: 'Base',
		domain: 6,
		chainId: 8453,
		usdc: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
		rpcUrls: ['https://mainnet.base.org', 'https://1rpc.io/base', 'https://base.drpc.org'],
		explorerUrl: 'https://basescan.org',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: false,
	}),
	evm({
		key: 'polygon',
		name: 'Polygon PoS',
		domain: 7,
		chainId: 137,
		usdc: '0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359',
		rpcUrls: ['https://polygon-bor-rpc.publicnode.com', 'https://polygon.drpc.org'],
		explorerUrl: 'https://polygonscan.com',
		nativeCurrency: { name: 'POL', symbol: 'POL', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: false,
	}),
	evm({
		key: 'unichain',
		name: 'Unichain',
		domain: 10,
		chainId: 130,
		usdc: '0x078D782b760474a361dDA0AF3839290b0EF57AD6',
		rpcUrls: ['https://mainnet.unichain.org', 'https://unichain-rpc.publicnode.com'],
		explorerUrl: 'https://uniscan.xyz',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: false,
	}),
	evm({
		key: 'linea',
		name: 'Linea',
		domain: 11,
		chainId: 59144,
		usdc: '0x176211869cA2b568f2A7D4EE941E073a821EE1ff',
		rpcUrls: [
			'https://rpc.linea.build',
			'https://linea-rpc.publicnode.com',
			'https://1rpc.io/linea',
		],
		explorerUrl: 'https://lineascan.build',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: false,
	}),
	evm({
		key: 'codex',
		name: 'Codex',
		domain: 12,
		chainId: 81224,
		usdc: '0xd996633a415985DBd7D6D12f4A4343E31f5037cf',
		rpcUrls: ['https://rpc.codex.xyz'],
		explorerUrl: 'https://explorer.codex.xyz',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: false,
	}),
	evm({
		key: 'sonic',
		name: 'Sonic',
		domain: 13,
		chainId: 146,
		usdc: '0x29219dd400f2Bf60E5a23d13Be72B486D4038894',
		rpcUrls: ['https://rpc.soniclabs.com', 'https://sonic-rpc.publicnode.com'],
		explorerUrl: 'https://sonicscan.org',
		nativeCurrency: { name: 'Sonic', symbol: 'S', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: false,
	}),
	evm({
		key: 'worldchain',
		name: 'World Chain',
		domain: 14,
		chainId: 480,
		usdc: '0x79A02482A880bCE3F13e09Da970dC34db4CD24d1',
		rpcUrls: ['https://worldchain-mainnet.g.alchemy.com/public', 'https://480.rpc.thirdweb.com'],
		explorerUrl: 'https://worldscan.org',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: false,
	}),
	evm({
		key: 'monad',
		name: 'Monad',
		domain: 15,
		chainId: 143,
		usdc: '0x754704Bc059F8C67012fEd69BC8A327a5aafb603',
		rpcUrls: ['https://rpc.monad.xyz', 'https://rpc1.monad.xyz'],
		explorerUrl: 'https://monadvision.com',
		nativeCurrency: { name: 'Monad', symbol: 'MON', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: false,
	}),
	evm({
		key: 'sei',
		name: 'Sei',
		domain: 16,
		chainId: 1329,
		usdc: '0xe15fC38F6D8c56aF07bbCBe3BAf5708A2Bf42392',
		rpcUrls: ['https://evm-rpc.sei-apis.com', 'https://sei-evm-rpc.publicnode.com'],
		explorerUrl: 'https://seiscan.io',
		nativeCurrency: { name: 'Sei', symbol: 'SEI', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: false,
	}),
	evm({
		key: 'xdc',
		name: 'XDC',
		domain: 18,
		chainId: 50,
		usdc: '0xfA2958CB79b0491CC627c1557F441eF849Ca8eb1',
		rpcUrls: ['https://rpc.xdcrpc.com', 'https://rpc.xdc.network', 'https://rpc.ankr.com/xdc'],
		explorerUrl: 'https://xdcscan.com',
		nativeCurrency: { name: 'XDC', symbol: 'XDC', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: false,
	}),
	evm({
		key: 'hyperevm',
		name: 'HyperEVM',
		domain: 19,
		chainId: 999,
		usdc: '0xb88339CB7199b77E23DB6E890353E22632Ba630f',
		rpcUrls: ['https://rpc.hyperliquid.xyz/evm', 'https://hyperliquid.drpc.org'],
		explorerUrl: 'https://hyperscan.com',
		nativeCurrency: { name: 'HYPE', symbol: 'HYPE', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: false,
	}),
	evm({
		key: 'ink',
		name: 'Ink',
		domain: 21,
		chainId: 57073,
		usdc: '0x2D270e6886d130D724215A266106e6832161EAEd',
		rpcUrls: ['https://rpc-gel.inkonchain.com', 'https://rpc-qnd.inkonchain.com'],
		explorerUrl: 'https://explorer.inkonchain.com',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: false,
	}),
	evm({
		key: 'plume',
		name: 'Plume',
		domain: 22,
		chainId: 98866,
		usdc: '0x222365EF19F7947e5484218551B56bb3965Aa7aF',
		rpcUrls: ['https://rpc.plume.org'],
		explorerUrl: 'https://explorer.plume.org',
		nativeCurrency: { name: 'Plume', symbol: 'PLUME', decimals: 18 },
		fastTransferAsSource: true,
		isTestnet: false,
	}),
	evm({
		key: 'arc',
		name: 'Arc',
		domain: 26,
		chainId: 5042,
		usdc: '0x3600000000000000000000000000000000000000',
		rpcUrls: ['https://rpc.mainnet.arc.io', 'https://rpc.drpc.mainnet.arc.io'],
		explorerUrl: 'https://explorer.arc.io',
		nativeCurrency: { name: 'USDC', symbol: 'USDC', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: false,
	}),
	evm({
		key: 'edge',
		name: 'EDGE',
		domain: 28,
		chainId: 3343,
		usdc: '0x98d2919b9A214E6Fa5384AC81E6864bA686Ad74c',
		rpcUrls: ['https://edge-mainnet.g.alchemy.com/public'],
		explorerUrl: 'https://pro.edgex.exchange/en-US/explorer',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: false,
		tokenMessengerV2: '0x98706A006bc632Df31CAdFCBD43F38887ce2ca5c',
		messageTransmitterV2: '0x5b61381Fc9e58E70EfC13a4A97516997019198ee',
	}),
	evm({
		key: 'injective',
		name: 'Injective',
		domain: 29,
		chainId: 1776,
		usdc: '0xa00C59fF5a080D2b954d0c75e46E22a0c371235a',
		rpcUrls: ['https://sentry.evm-rpc.injective.network', 'https://injectiveevm-rpc.polkachu.com'],
		explorerUrl: 'https://blockscout.injective.network',
		nativeCurrency: { name: 'Injective', symbol: 'INJ', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: false,
	}),
	evm({
		key: 'morph',
		name: 'Morph',
		domain: 30,
		chainId: 2818,
		usdc: '0xCfb1186F4e93D60E60a8bDd997427D1F33bc372B',
		rpcUrls: ['https://rpc.morphl2.io', 'https://rpc-quicknode.morphl2.io'],
		explorerUrl: 'https://explorer.morph.network',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: false,
	}),
	evm({
		key: 'pharos',
		name: 'Pharos',
		domain: 31,
		chainId: 1672,
		usdc: '0xC879C018dB60520F4355C26eD1a6D572cdAC1815',
		rpcUrls: ['https://rpc.pharos.xyz'],
		explorerUrl: 'https://pharos.socialscan.io',
		nativeCurrency: { name: 'Pharos', symbol: 'PHRS', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: false,
	}),
	evm({
		key: 'cronos',
		name: 'Cronos',
		domain: 32,
		chainId: 25,
		usdc: '0x3D7F2C478aAfdB65542BCB44bCeeC05849999d2D',
		rpcUrls: ['https://cronos-evm-rpc.publicnode.com', 'https://1rpc.io/cro'],
		explorerUrl: 'https://explorer.cronos.org',
		nativeCurrency: { name: 'Cronos', symbol: 'CRO', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: false,
	}),
	evm({
		key: 'plasma',
		name: 'Plasma',
		domain: 33,
		chainId: 9745,
		usdc: '0x2d661C89D812261039AF9764eceaAee884f5F67F',
		rpcUrls: ['https://rpc.plasma.to'],
		explorerUrl: 'https://plasmascan.to',
		nativeCurrency: { name: 'Plasma', symbol: 'XPL', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: false,
	}),
	evm({
		key: 'xlayer',
		name: 'X Layer',
		domain: 37,
		chainId: 196,
		usdc: '0xB6CEceAB302E2E4948951eE7843FC24E92933061',
		rpcUrls: ['https://xlayerrpc.okx.com', 'https://xlayer.drpc.org'],
		explorerUrl: 'https://www.okx.com/web3/explorer/xlayer',
		nativeCurrency: { name: 'OKB', symbol: 'OKB', decimals: 18 },
		fastTransferAsSource: true,
		isTestnet: false,
	}),
];

/**
 * Testnet registry (Circle's designated testnet per mainnet chain). Pharos Testnet is
 * omitted because its chain id could not be verified.
 */
export const EVM_TESTNET_CHAINS: EvmChainDefinition[] = [
	evm({
		key: 'ethereum',
		name: 'Ethereum Sepolia',
		domain: 0,
		chainId: 11155111,
		usdc: '0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238',
		rpcUrls: ['https://ethereum-sepolia-rpc.publicnode.com', 'https://1rpc.io/sepolia'],
		explorerUrl: 'https://sepolia.etherscan.io',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: true,
	}),
	evm({
		key: 'avalanche',
		name: 'Avalanche Fuji',
		domain: 1,
		chainId: 43113,
		usdc: '0x5425890298aed601595a70AB815c96711a31Bc65',
		rpcUrls: [
			'https://api.avax-test.network/ext/bc/C/rpc',
			'https://avalanche-fuji-c-chain-rpc.publicnode.com',
		],
		explorerUrl: 'https://testnet.snowtrace.io',
		nativeCurrency: { name: 'Avalanche', symbol: 'AVAX', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: true,
	}),
	evm({
		key: 'optimism',
		name: 'OP Sepolia',
		domain: 2,
		chainId: 11155420,
		usdc: '0x5fd84259d66Cd46123540766Be93DFE6D43130D7',
		rpcUrls: ['https://sepolia.optimism.io', 'https://optimism-sepolia-rpc.publicnode.com'],
		explorerUrl: 'https://sepolia-optimism.etherscan.io',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: true,
	}),
	evm({
		key: 'arbitrum',
		name: 'Arbitrum Sepolia',
		domain: 3,
		chainId: 421614,
		usdc: '0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d',
		rpcUrls: [
			'https://sepolia-rollup.arbitrum.io/rpc',
			'https://arbitrum-sepolia-rpc.publicnode.com',
		],
		explorerUrl: 'https://sepolia.arbiscan.io',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: true,
	}),
	evm({
		key: 'base',
		name: 'Base Sepolia',
		domain: 6,
		chainId: 84532,
		usdc: '0x036CbD53842c5426634e7929541eC2318f3dCF7e',
		rpcUrls: ['https://sepolia.base.org', 'https://base-sepolia-rpc.publicnode.com'],
		explorerUrl: 'https://sepolia.basescan.org',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: true,
	}),
	evm({
		key: 'polygon',
		name: 'Polygon Amoy',
		domain: 7,
		chainId: 80002,
		usdc: '0x41E94Eb019C0762f9Bfcf9Fb1E58725BfB0e7582',
		rpcUrls: ['https://polygon-amoy-bor-rpc.publicnode.com', 'https://polygon-amoy.drpc.org'],
		explorerUrl: 'https://amoy.polygonscan.com',
		nativeCurrency: { name: 'POL', symbol: 'POL', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: true,
	}),
	evm({
		key: 'unichain',
		name: 'Unichain Sepolia',
		domain: 10,
		chainId: 1301,
		usdc: '0x31d0220469e10c4E71834a79b1f276d740d3768F',
		rpcUrls: ['https://sepolia.unichain.org', 'https://unichain-sepolia-rpc.publicnode.com'],
		explorerUrl: 'https://unichain-sepolia.blockscout.com',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: true,
	}),
	evm({
		key: 'linea',
		name: 'Linea Sepolia',
		domain: 11,
		chainId: 59141,
		usdc: '0xFEce4462D57bD51A6A552365A011b95f0E16d9B7',
		rpcUrls: ['https://rpc.sepolia.linea.build', 'https://linea-sepolia-rpc.publicnode.com'],
		explorerUrl: 'https://sepolia.lineascan.build',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: true,
	}),
	evm({
		key: 'codex',
		name: 'Codex Testnet',
		domain: 12,
		chainId: 812242,
		usdc: '0x6d7f141b6819C2c9CC2f818e6ad549E7Ca090F8f',
		rpcUrls: ['https://rpc.codex-stg.xyz'],
		explorerUrl: 'https://explorer.codex-stg.xyz',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: true,
	}),
	evm({
		key: 'sonic',
		name: 'Sonic Testnet',
		domain: 13,
		chainId: 14601,
		usdc: '0x0BA304580ee7c9a980CF72e55f5Ed2E9fd30Bc51',
		rpcUrls: ['https://rpc.testnet.soniclabs.com'],
		explorerUrl: 'https://testnet.sonicscan.org',
		nativeCurrency: { name: 'Sonic', symbol: 'S', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: true,
	}),
	evm({
		key: 'worldchain',
		name: 'World Chain Sepolia',
		domain: 14,
		chainId: 4801,
		usdc: '0x66145f38cBAC35Ca6F1Dfb4914dF98F1614aeA88',
		rpcUrls: ['https://worldchain-sepolia.g.alchemy.com/public', 'https://4801.rpc.thirdweb.com'],
		explorerUrl: 'https://sepolia.worldscan.org',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: true,
	}),
	evm({
		key: 'monad',
		name: 'Monad Testnet',
		domain: 15,
		chainId: 10143,
		usdc: '0x534b2f3A21130d7a60830c2Df862319e593943A3',
		rpcUrls: ['https://testnet-rpc.monad.xyz', 'https://monad-testnet.drpc.org'],
		explorerUrl: 'https://testnet.monadexplorer.com',
		nativeCurrency: { name: 'Monad', symbol: 'MON', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: true,
	}),
	evm({
		key: 'sei',
		name: 'Sei Testnet',
		domain: 16,
		chainId: 1328,
		usdc: '0x4fCF1784B31630811181f670Aea7A7bEF803eaED',
		rpcUrls: ['https://evm-rpc-testnet.sei-apis.com', 'https://sei-testnet.drpc.org'],
		explorerUrl: 'https://testnet.seiscan.io',
		nativeCurrency: { name: 'Sei', symbol: 'SEI', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: true,
	}),
	evm({
		key: 'xdc',
		name: 'XDC Apothem',
		domain: 18,
		chainId: 51,
		usdc: '0xb5AB69F7bBada22B28e79C8FFAECe55eF1c771D4',
		rpcUrls: ['https://erpc.apothem.network', 'https://rpc.apothem.network'],
		explorerUrl: 'https://testnet.xdcscan.com',
		nativeCurrency: { name: 'XDC', symbol: 'XDC', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: true,
	}),
	evm({
		key: 'hyperevm',
		name: 'HyperEVM Testnet',
		domain: 19,
		chainId: 998,
		usdc: '0x2B3370eE501B4a559b57D449569354196457D8Ab',
		rpcUrls: ['https://rpc.hyperliquid-testnet.xyz/evm'],
		explorerUrl: 'https://testnet.purrsec.com',
		nativeCurrency: { name: 'HYPE', symbol: 'HYPE', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: true,
	}),
	evm({
		key: 'ink',
		name: 'Ink Sepolia',
		domain: 21,
		chainId: 763373,
		usdc: '0xFabab97dCE620294D2B0b0e46C68964e326300Ac',
		rpcUrls: ['https://rpc-gel-sepolia.inkonchain.com', 'https://rpc-qnd-sepolia.inkonchain.com'],
		explorerUrl: 'https://explorer-sepolia.inkonchain.com',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: true,
	}),
	evm({
		key: 'plume',
		name: 'Plume Testnet',
		domain: 22,
		chainId: 98867,
		usdc: '0xcB5f30e335672893c7eb944B374c196392C19D18',
		rpcUrls: ['https://testnet-rpc.plume.org'],
		explorerUrl: 'https://testnet-explorer.plume.org',
		nativeCurrency: { name: 'Plume', symbol: 'PLUME', decimals: 18 },
		fastTransferAsSource: true,
		isTestnet: true,
	}),
	evm({
		key: 'arc',
		name: 'Arc Testnet',
		domain: 26,
		chainId: 5042002,
		usdc: '0x3600000000000000000000000000000000000000',
		rpcUrls: ['https://rpc.testnet.arc.network', 'https://rpc.quicknode.testnet.arc.network'],
		explorerUrl: 'https://explorer.testnet.arc.io',
		nativeCurrency: { name: 'USDC', symbol: 'USDC', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: true,
	}),
	evm({
		key: 'edge',
		name: 'EDGE Testnet',
		domain: 28,
		chainId: 33431,
		usdc: '0x2d9F7CAD728051AA35Ecdc472a14cf8cDF5CFD6B',
		rpcUrls: ['https://edge-testnet.g.alchemy.com/public'],
		explorerUrl: 'https://edge-testnet.explorer.alchemy.com',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: true,
	}),
	evm({
		key: 'injective',
		name: 'Injective Testnet',
		domain: 29,
		chainId: 1439,
		usdc: '0x0C382e685bbeeFE5d3d9C29e29E341fEE8E84C5d',
		rpcUrls: [
			'https://k8s.testnet.json-rpc.injective.network',
			'https://injectiveevm-testnet-rpc.polkachu.com',
		],
		explorerUrl: 'https://testnet.blockscout.injective.network',
		nativeCurrency: { name: 'Injective', symbol: 'INJ', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: true,
	}),
	evm({
		key: 'morph',
		name: 'Morph Hoodi',
		domain: 30,
		chainId: 2910,
		usdc: '0x7433b41C6c5e1d58D4Da99483609520255ab661B',
		rpcUrls: ['https://rpc-hoodi.morphl2.io'],
		explorerUrl: 'https://explorer-hoodi.morph.network',
		nativeCurrency: ETH,
		fastTransferAsSource: true,
		isTestnet: true,
	}),
	evm({
		key: 'cronos',
		name: 'Cronos Testnet',
		domain: 32,
		chainId: 338,
		usdc: '0xEb33dc5fac03833e132593659e1dE7256aB59794',
		rpcUrls: ['https://evm-t3.cronos.org', 'https://cronos-testnet.drpc.org'],
		explorerUrl: 'https://explorer.cronos.org/testnet',
		nativeCurrency: { name: 'Cronos', symbol: 'TCRO', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: true,
	}),
	evm({
		key: 'plasma',
		name: 'Plasma Testnet',
		domain: 33,
		chainId: 9746,
		usdc: '0xE67Fb267022cBA8064Dd388CC2FED724F3120D9D',
		rpcUrls: ['https://testnet-rpc.plasma.to'],
		explorerUrl: 'https://testnet.plasmascan.to',
		nativeCurrency: { name: 'Plasma', symbol: 'XPL', decimals: 18 },
		fastTransferAsSource: false,
		isTestnet: true,
	}),
	evm({
		key: 'xlayer',
		name: 'X Layer Testnet',
		domain: 37,
		chainId: 1952,
		usdc: '0xDec90b78111Ba2fc6FC6d84d8B9ec159A2d4b9B3',
		rpcUrls: ['https://xlayertestrpc.okx.com'],
		explorerUrl: 'https://www.okx.com/web3/explorer/xlayer-test',
		nativeCurrency: { name: 'OKB', symbol: 'OKB', decimals: 18 },
		fastTransferAsSource: true,
		isTestnet: true,
	}),
];
