// Codegen(opts) — the canonical codegen LayeredTag. Runs a list of emitter
// plug-ins against the resolved Package set at acquire time.
//
// Architecture:
//   - User declares `Codegen({ packages })` (or just `Codegen()`) in
//     their devstack.config.ts. The defaults
//     (`[BindingsEmitter(), StackHandleEmitter(), DappKitConfigEmitter(),
//     DeepbookConfigEmitter()]`) emit Move bindings, typed stack
//     handles (`accounts.ts`, `services.ts`, `extras.ts`,
//     `captured.ts`), a partial dapp-kit config, and a typed
//     `deepbookConfig` — everything an app needs to wire up against a
//     localnet without consuming the raw manifest at runtime.
//   - For per-emitter options, pass them explicitly:
//     `Codegen({ ..., emitters: [BindingsEmitter(),
//     DappKitConfigEmitter({ flavor: 'core' })] })`.
//   - Each Package(...) the stack contains feeds into Codegen's
//     context (unless it sets `{ codegen: false }`).
//   - Each emitter sees the same `{ packages, outputDir }` context.
//
// Built-in emitters:
//   - `BindingsEmitter`     → `<outputDir>/bindings/<pkg>/...`
//                              (Move → TS via `@mysten/codegen`)
//   - `StackHandleEmitter`  → `<outputDir>/accounts.ts`,
//                              `services.ts`, `extras.ts`, `captured.ts`
//   - `DappKitConfigEmitter` → `<outputDir>/dapp-kit-config.ts`
//                              (partial config the user's `dapp-kit.ts`
//                               spreads into `createDAppKit(...)`)
//   - `DeepbookConfigEmitter` → `<outputDir>/deepbook-config.ts`
//                              (typed deepbookConfig the user spreads
//                               into `client.$extend(deepbook(...))`;
//                               no-op for stacks without deepbook)
//
// User emitters drop in alongside via `defineEmitter({ name, emit })`.

import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { Effect } from 'effect';
import { tag, setPhase, type LayeredTag } from '../advanced/tag.js';
import type { Emitter, CodegenContext, CodegenPackage } from '../codegen/define-emitter.js';
import { BindingsEmitter } from '../codegen/emitters/bindings.js';
import { DappKitConfigEmitter } from '../codegen/emitters/dapp-kit-config.js';
import { DeepbookConfigEmitter } from '../codegen/emitters/deepbook-config.js';
import { StackHandleEmitter } from '../codegen/emitters/stack-handle.js';
import { CodegenError } from '../codegen/errors.js';
import { displayPath } from '../engine/display-path.js';
import { stageAndSwap, StageAndSwapError } from '../engine/stage-and-swap.js';
import { writeFileAtomic } from '../engine/atomic-write.js';
import type { Package, LocalPackage } from './package.js';

const GITIGNORE_BODY = `# generated by @mysten-incubation/devstack — do not commit
# contains a wallet bearer token + user-supplied extras
dapp-kit-config.ts
extras.ts
`;

/** Read the existing `.gitignore` at `outputDir`, returning `undefined`
 *  if missing. Used by the atomic-swap pipeline to preserve a user-
 *  customized `.gitignore` across the rename — otherwise the swap would
 *  promote staging (no `.gitignore`) and destroy the user's edits. */
const readExistingGitignore = (outputDir: string): Effect.Effect<string | undefined> =>
	Effect.promise(async () => {
		try {
			return await fs.readFile(path.join(outputDir, '.gitignore'), 'utf-8');
		} catch {
			return undefined;
		}
	});

/** Write `<outputDir>/.gitignore`. When `existing` is supplied the
 *  caller has already established the user's pre-existing content
 *  (typically from a `readExistingGitignore` pass before the atomic
 *  swap); we write that back so user customizations survive. When
 *  `existing` is undefined we drop the default body so the sensitive
 *  emitter outputs (`dapp-kit-config.ts` carries a wallet bearer token,
 *  `extras.ts` carries user-supplied secrets) don't land in a
 *  consumer's git history. */
const writeGitignore = (
	outputDir: string,
	existing: string | undefined,
): Effect.Effect<void, CodegenError> =>
	Effect.tryPromise({
		try: async () => {
			await writeFileAtomic(path.join(outputDir, '.gitignore'), existing ?? GITIGNORE_BODY);
		},
		catch: (cause) =>
			new CodegenError({
				emitter: 'codegen',
				phase: 'write',
				message: `failed to write .gitignore under ${outputDir}: ${String(cause)}`,
				cause,
			}),
	});

/* eslint-disable @typescript-eslint/no-explicit-any */

/** Canonical default output directory for `Codegen({})`. Imported by
 *  app code (`import ... from './generated/bindings/...'`) so it lives in
 *  a normal `src/`-typed source dir, NOT under the `.devstack/` dot-dir
 *  (which is reserved for non-importable runtime state — see the
 *  invariant comment in `engine/service-paths.ts`). The relative form
 *  resolves against the example app's `process.cwd()` at codegen time. */
export const DEFAULT_CODEGEN_OUTPUT = './src/generated';

export interface CodegenOptions {
	/** Output directory. Resolved relative to `process.cwd()` if not
	 *  absolute. Each emitter writes under a subdirectory of this path
	 *  (`<output>/bindings/`, `<output>/dapp-kit/`, …) so multiple
	 *  emitters coexist without collision.
	 *
	 *  Defaults to `./src/generated` — a normal source dir picked up by
	 *  TypeScript's `include` patterns and Vite's resolve graph, so app
	 *  code can `import { useFoo } from './generated/dapp-kit/foo.js'`
	 *  without extra wiring. The `.devstack/` dot-dir is intentionally
	 *  NOT used here: that path is reserved for non-importable runtime
	 *  state (account keys, wallet tokens, walrus deploy outputs, etc.). */
	readonly output?: string;
	/** Package refs to emit for. `Package(...)` refs emit fully;
	 *  `KnownPackage(...)` refs are silently skipped at emit time by
	 *  emitters that need Move source (e.g. `BindingsEmitter`). The
	 *  type is loose because TS treats the shape parameter as invariant
	 *  on `LayeredTag`; the emitter validates package shape at runtime.
	 *
	 *  Defaults to `[]` — Phase-6 default-provider auto-includes every
	 *  `Package(...)` in the stack that doesn't opt out via
	 *  `{ codegen: false }`, so most users omit this. */
	readonly packages?: ReadonlyArray<LayeredTag<any, any, any, any>>;
	/** Emitter plug-ins to run. Run in declaration order; one emitter's
	 *  output isn't visible to another (each emitter is independent).
	 *  Defaults to `[BindingsEmitter(), StackHandleEmitter(),
	 *  DappKitConfigEmitter(), DeepbookConfigEmitter()]` — Move → TS
	 *  bindings, typed stack handles (`accounts.ts`, `services.ts`,
	 *  `extras.ts`, `captured.ts`), a partial dApp-Kit config the user's
	 *  hand-written `dapp-kit.ts` spreads into `createDAppKit(...)`, and
	 *  a typed `deepbookConfig` consumers spread into
	 *  `client.$extend(deepbook(...))`. The deepbook emitter is a no-op
	 *  on stacks without `services.deepbook` in the manifest. Override
	 *  to add custom emitters or swap per-emitter options. */
	readonly emitters?: ReadonlyArray<Emitter>;
	/** Override tag name. Defaults to `'codegen'`. */
	readonly name?: string;
}

/** Resolve a Package LayeredTag's value into the `CodegenPackage` shape every
 *  emitter consumes. Local packages carry `sourcePath`; remote/known
 *  packages don't (emitters that need source filter to entries where
 *  it's defined). */
const toCodegenPackage = (pkg: Package | LocalPackage): CodegenPackage => {
	const base: { name: string; packageId: string; mvrPlaceholder: string } = {
		name: pkg.name,
		packageId: pkg.packageId,
		mvrPlaceholder:
			'mvrPlaceholder' in pkg && pkg.mvrPlaceholder !== undefined ? pkg.mvrPlaceholder : pkg.name,
	};
	const local = 'sourcePath' in pkg ? (pkg as LocalPackage) : undefined;
	if (local !== undefined) {
		const withSource: CodegenPackage = {
			...base,
			sourcePath: local.sourcePath,
			...(local.captured !== undefined ? { captured: local.captured } : {}),
		};
		return withSource;
	}
	return base;
};

/** The Codegen LayeredTag. Returns a tag whose value is the resolved
 *  `CodegenContext` (after every emitter has run).
 *
 *  Zero-config: `Codegen({})` (or just `Codegen()`) uses every default —
 *  `output: './src/generated'`, `packages: []` (auto-fill TBD), and
 *  `emitters: [BindingsEmitter()]`. Most stacks should call it that
 *  way and let the defaults do their job. */
export const Codegen = (opts: CodegenOptions = {}) => {
	const name = opts.name ?? 'codegen';
	const packageRefs = opts.packages ?? [];
	const emitters = opts.emitters ?? [
		BindingsEmitter(),
		StackHandleEmitter(),
		DappKitConfigEmitter(),
		DeepbookConfigEmitter(),
	];
	const output = opts.output ?? DEFAULT_CODEGEN_OUTPUT;
	return tag(
		`codegen/${name}` as const,
		Effect.gen(function* () {
			const outputDir = path.isAbsolute(output) ? output : path.resolve(process.cwd(), output);

			// Snapshot any user-customized `.gitignore` so we can put it
			// back at the same path after the atomic swap below. If the
			// user previously hand-edited `.gitignore` it lives at
			// `outputDir/.gitignore`; the swap is going to rename
			// `outputDir` aside and would otherwise destroy that file.
			const existingGitignore = yield* readExistingGitignore(outputDir);

			yield* setPhase('resolving packages');
			const resolved: Array<CodegenPackage> = [];
			const seen = new Set<string>();
			for (const ref of packageRefs) {
				// Skip refs that opted out of codegen at construction time
				// via `Package(..., { codegen: false })`. The flag is stamped
				// onto the LayeredTag itself so we can read it without acquiring.
				if ((ref as { __codegenExclude?: boolean }).__codegenExclude === true) continue;
				const pkg = yield* ref;
				if (seen.has(pkg.name)) continue;
				seen.add(pkg.name);
				resolved.push(toCodegenPackage(pkg));
			}

			// Collision detection: each emitter conventionally writes
			// under `<outputDir>/<emitter.name>/`. Two emitters with the
			// same `name` would clobber each other's output (and which
			// one wins depends on iteration order, which is fragile).
			// Fail loudly at acquire time so the conflict surfaces with
			// the user's `Codegen({ emitters: [...] })` site in the
			// stack trace, not as a mysterious missing-file error
			// during a downstream consumer's TS build.
			const emitterNamesSeen = new Set<string>();
			for (const emitter of emitters) {
				if (emitterNamesSeen.has(emitter.name)) {
					return yield* Effect.fail(
						new CodegenError({
							emitter: emitter.name,
							phase: 'generate',
							message:
								`Codegen('${name}'): duplicate emitter name '${emitter.name}'. ` +
								`Each emitter writes under <outputDir>/<emitter.name>/; two ` +
								`emitters with the same name would clobber each other.`,
						}),
					);
				}
				emitterNamesSeen.add(emitter.name);
			}

			yield* Effect.annotateCurrentSpan({
				'codegen.output': outputDir,
				'codegen.packages': resolved.map((p) => p.name).join(','),
				'codegen.emitters': emitters.map((e) => e.name).join(','),
			});

			// All emitters write into a staging dir; on success
			// `stageAndSwap` atomically promotes it into `outputDir`
			// (rename existing aside, rename staging in, drop the
			// displaced tree). On ANY emitter failure the staging dir is
			// removed and `outputDir` is left untouched — no partial
			// state ever lands in the consumer's source tree. POSIX
			// same-FS rename(2) is atomic, so a Vite dev server watching
			// `outputDir` never observes a half-emitted tree.
			//
			// Serial emit (concurrency: 1). Per-emitter locking is on
			// the long-tail wishlist; until then, serial avoids the
			// `~/.move` and bind-mount races between concurrent
			// `sui move {build,summary}` invocations.
			yield* stageAndSwap({
				target: outputDir,
				stage: (stagingDir) =>
					Effect.gen(function* () {
						const ctx: CodegenContext = { packages: resolved, outputDir: stagingDir };
						for (const emitter of emitters) {
							yield* setPhase(`emit: ${emitter.name}`);
							yield* emitter.emit(ctx).pipe(
								Effect.mapError((cause) => {
									if (cause instanceof CodegenError) {
										// Preserve the emitter's `phase` rather
										// than re-wrapping into 'generate' — the
										// original classification (e.g. 'write'
										// for atomic dir-swap failures) is more
										// diagnostic.
										return cause;
									}
									return new CodegenError({
										emitter: emitter.name,
										phase: 'generate',
										message: `emitter '${emitter.name}' failed`,
										cause,
									});
								}),
							);
						}
					}),
			}).pipe(
				Effect.catchTag('StageAndSwapError', (err: StageAndSwapError) =>
					Effect.fail(
						new CodegenError({
							emitter: 'codegen',
							phase: 'write',
							message: err.message,
							cause: err.cause,
						}),
					),
				),
			);

			// Drop a `.gitignore` next to the emitter outputs so the
			// sensitive files (`dapp-kit-config.ts` carries a wallet
			// bearer token, `extras.ts` carries user-supplied secrets)
			// don't end up in a consumer's git history. Written AFTER
			// the atomic swap so the `.gitignore` lives at the final
			// `outputDir` and doesn't ride the staging-tree promotion.
			// Preserves a user-customized `.gitignore` by writing back
			// the snapshot we captured before the swap.
			yield* writeGitignore(outputDir, existingGitignore);

			return { outputDir, emitters: emitters.map((e) => e.name) };
		}).pipe(Effect.withSpan(`Codegen(${name})`)),
		{
			kind: 'app',
			plugin: 'codegen',
			displayTitle: `codegen.${name}`,
			display: (s: { readonly outputDir: string; readonly emitters: ReadonlyArray<string> }) => ({
				title: `codegen.${name}`,
				primary: displayPath(s.outputDir),
				extras: [`${s.emitters.length} emitter${s.emitters.length === 1 ? '' : 's'}`],
			}),
			// Negation-only watch declaration: codegen WRITES to `output` each
			// cycle via an atomic rename, so any watcher set up by some OTHER
			// primitive (or `config.watch`) that happens to be an ancestor of
			// `output` must NOT trigger a hot-restart from those writes — that
			// would loop. `output` is resolved eagerly so the supervisor sees
			// the absolute path. (The `generated` basename is also in
			// DEFAULT_WATCH_EXCLUDES, so the default `./src/generated` works
			// without this; the negation here covers users who override
			// `output:` to a different basename.)
			watch: [`!${path.isAbsolute(output) ? output : path.resolve(process.cwd(), output)}/**`],
			// The body iterates `packageRefs`, yielding each Package ref
			// to read its packageId + coin shape. Lift them into
			// upstreams so the
			// topological scheduler places codegen strictly after every
			// referenced package's publish — otherwise it lands in level
			// 0 and the first `yield* ref` fails with
			// "Service not found: <pkg-name>".
			upstreamKeys: packageRefs,
		},
	);
};
