// Composer for the scaffolder — selects plugins by composition, not text
// parsing.
//
// The authored template is a superset whose two GENERATED barrels
// (`src/app-panels.ts`, `src/devstack/plugins.ts`) list every optional plugin.
// Composition for a selected subset is three plain filesystem ops, with NO
// text parsing of authored source:
//
//   1. Delete each unselected plugin's owned files/dirs (`rm -rf` semantics).
//   2. Regenerate the two barrels from the SELECTED plugins only (whole-file
//      writes from a fixed template literal).
//   3. Delete each unselected plugin's deps/devDeps from package.json.
//
// Because the barrels are regenerated (not spliced) and each plugin's files are
// self-contained, every subset is clean by construction: a barrel only ever
// imports modules that still exist, and no authored file references a removed
// plugin. A defensive guard re-asserts this after composing.

import { existsSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

import { OPTIONAL_PLUGINS, PLUGIN_MANIFEST, type PluginId } from './plugin-manifest.js';

/** Posix-join template-relative segments (manifest paths are posix). */
function tjoin(appDir: string, rel: string): string {
	return join(appDir, ...rel.split('/'));
}

/** Optional plugins kept, in canonical order. `core` is implicit. */
function selectedOptional(
	selected: ReadonlySet<PluginId>,
): ReadonlyArray<Exclude<PluginId, 'core'>> {
	return OPTIONAL_PLUGINS.filter((id) => selected.has(id));
}

/** Render `src/app-panels.ts` for the selected optional plugins. Core
 *  `CounterPanel` is always present and first. */
export function renderPanelsBarrel(selected: ReadonlySet<PluginId>): string {
	const opt = selectedOptional(selected);
	const imports = [
		"import { CounterPanel } from './panels/CounterPanel.js';",
		...opt.map((id) => {
			const s = PLUGIN_MANIFEST[id];
			return `import { ${s.panel} } from './${s.panelModule}.js';`;
		}),
	];
	const list = ['CounterPanel', ...opt.map((id) => PLUGIN_MANIFEST[id].panel)];
	return [
		'// GENERATED by create-devstack-app: which demo panels this app renders.',
		'// Core CounterPanel is always present; optional plugin panels follow.',
		'',
		"import type { ComponentType } from 'react';",
		'',
		...imports,
		'',
		'/** Each panel takes a single `connected` prop. */',
		'export const PANELS: ReadonlyArray<ComponentType<{ connected: boolean }>> = [',
		...list.map((p) => `\t${p},`),
		'];',
		'',
	].join('\n');
}

/** Render `src/devstack/plugins.ts` for the selected optional plugins. */
export function renderPluginsBarrel(selected: ReadonlySet<PluginId>): string {
	const opt = selectedOptional(selected);
	const imports = opt.map((id) => {
		const s = PLUGIN_MANIFEST[id];
		return `import { ${s.configModule} } from './${s.configModuleSpecifier}.js';`;
	});
	const list = opt.map((id) => PLUGIN_MANIFEST[id].configModule);
	return [
		'// GENERATED by create-devstack-app: which optional plugin modules this app',
		'// includes. Core `devstack.config.ts` spreads each module’s contribution.',
		'',
		...(imports.length > 0 ? [...imports, ''] : []),
		"import type { PluginModule } from './contribution.js';",
		'',
		`export const OPTIONAL_PLUGINS: ReadonlyArray<PluginModule> = [${
			list.length > 0 ? `\n${list.map((m) => `\t${m},`).join('\n')}\n` : ''
		}];`,
		'',
	].join('\n');
}

/** Walk a directory tree yielding absolute file paths. */
function* walkFiles(dir: string): IterableIterator<string> {
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const full = join(dir, entry.name);
		if (entry.isDirectory()) {
			yield* walkFiles(full);
		} else if (entry.isFile()) {
			yield full;
		}
	}
}

const TEXT_EXTS = new Set(['.ts', '.tsx', '.move', '.js', '.mjs', '.cts', '.mts']);

function hasTextExt(path: string): boolean {
	const dot = path.lastIndexOf('.');
	return dot >= 0 && TEXT_EXTS.has(path.slice(dot));
}

interface PkgJson {
	dependencies?: Record<string, string>;
	devDependencies?: Record<string, string>;
	[k: string]: unknown;
}

/**
 * Compose a scaffolded app directory down to the selected plugin subset,
 * in place.
 *
 * `selected` must always contain `core`; the caller guarantees this, but we
 * assert it defensively.
 */
export function composePlugins(appDir: string, selected: ReadonlySet<PluginId>): void {
	if (!selected.has('core')) {
		throw new Error("composePlugins: 'core' must always be selected.");
	}

	// (1) Remove unselected plugins' owned files/dirs.
	for (const id of OPTIONAL_PLUGINS) {
		if (selected.has(id)) continue;
		const spec = PLUGIN_MANIFEST[id];
		for (const f of spec.files) {
			rmSync(tjoin(appDir, f), { force: true });
		}
		for (const d of spec.dirs) {
			rmSync(tjoin(appDir, d), { recursive: true, force: true });
		}
	}

	// (2) Regenerate the two barrels from the selected plugins.
	writeFileSync(tjoin(appDir, 'src/app-panels.ts'), renderPanelsBarrel(selected));
	writeFileSync(tjoin(appDir, 'src/devstack/plugins.ts'), renderPluginsBarrel(selected));

	// (3) Structurally delete unselected deps/devDeps from package.json.
	const pkgPath = join(appDir, 'package.json');
	if (existsSync(pkgPath)) {
		const json = JSON.parse(readFileSync(pkgPath, 'utf8')) as PkgJson;
		let changed = false;
		for (const id of OPTIONAL_PLUGINS) {
			if (selected.has(id)) continue;
			const spec = PLUGIN_MANIFEST[id];
			for (const dep of spec.deps) {
				if (json.dependencies?.[dep] !== undefined) {
					delete json.dependencies[dep];
					changed = true;
				}
			}
			for (const dep of spec.devDeps ?? []) {
				if (json.devDependencies?.[dep] !== undefined) {
					delete json.devDependencies[dep];
					changed = true;
				}
			}
		}
		if (changed) {
			writeFileSync(pkgPath, `${JSON.stringify(json, null, '\t')}\n`);
		}
	}

	// (4) Defensive guard: no surviving file imports a removed plugin module.
	assertNoDanglingRefs(appDir, selected);
}

/** Throw if any surviving text file imports a removed plugin's panel/lib/
 *  wiring module, or a removed Move package path. Composition is clean by
 *  construction (barrels regenerated, files self-contained); this guard is a
 *  cheap backstop that turns any future authoring mistake into a clear error
 *  instead of a broken scaffold. */
function assertNoDanglingRefs(appDir: string, selected: ReadonlySet<PluginId>): void {
	const removedKeys: string[] = [];
	for (const id of OPTIONAL_PLUGINS) {
		if (selected.has(id)) continue;
		const spec = PLUGIN_MANIFEST[id];
		for (const f of spec.files) {
			removedKeys.push(moduleKey(f));
		}
		for (const d of spec.dirs) {
			removedKeys.push(d.replace(/\\/g, '/'));
		}
	}
	if (removedKeys.length === 0) return;

	for (const file of walkFiles(appDir)) {
		if (!hasTextExt(file)) continue;
		const text = readFileSync(file, 'utf8');
		for (const key of removedKeys) {
			// Match an import/path string ending in the removed module key,
			// bounded by a path separator before and a quote/extension after, so
			// substrings don't false-positive.
			const re = new RegExp(`['"\`][^'"\`]*/${escapeRegExp(key)}(\\.[a-z]+)?['"\`]`);
			if (re.test(text)) {
				throw new Error(
					`composePlugins guard: ${relative(appDir, file)} still references removed module '${key}'.`,
				);
			}
		}
	}
}

/** Derive an import-key from a template-relative source path:
 *  `src/lib/walrus.ts` -> `lib/walrus`, `src/devstack/walrus.ts` ->
 *  `devstack/walrus`, `e2e/walrus.spec.ts` -> `walrus.spec`. */
function moduleKey(relPath: string): string {
	let p = relPath.replace(/\\/g, '/');
	if (p.startsWith('src/')) p = p.slice('src/'.length);
	return p.replace(/\.(tsx?|m?[jt]s|cts|mts)$/, '');
}

function escapeRegExp(s: string): string {
	return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
