import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, resolve } from 'node:path';
import type { Dep } from '../engine/types.js';
import { define } from '../factories/define.js';
import type { Account, Endpoint, Package } from '../shapes/index.js';

export interface ManifestOptions {
	/** Output path relative to `env.appDir` (or absolute).
	 * Default: `src/generated/manifest.ts`. */
	output?: string;
	/** Logical name. Default: `manifest`. Override when an app needs
	 * multiple manifest emissions (rare). */
	name?: string;
	/** Packages to project into the manifest. Each Dep returns a Package
	 * shape; emission order matches array order. */
	packages?: Dep<void, Package>[];
	/** Endpoints (RPC URLs, faucets, walrus nodes, …). */
	endpoints?: Dep<void, Endpoint>[];
	/** Accounts (signer addresses keyed by logical name). */
	accounts?: Dep<void, Account>[];
}

export interface ManifestState {
	outputPath: string;
	contentHash: string;
}

interface ResolvedDeps {
	packages: Package[];
	endpoints: Endpoint[];
	accounts: Account[];
}

// `manifest` emits a typed manifest TypeScript file under `<appDir>/<output>`.
// The file re-projects upstream Dep values so app code can `import { manifest }`
// without re-typing the four registry-style categories at every call site.
// Move bindings live in a separate `bindings` plugin — this plugin owns
// only the small, stable manifest projection.
//
// Cross-plugin fan-in works via `deps: { packages: [...], endpoints: [...] }`
// — each array's items are Deps. The engine walks the structure, resolves
// each Dep to its projected shape, and hands `run()` a flat object:
// `deps.packages: Package[]`, etc. Re-fires whenever any upstream's
// identity changes (input-hash includes resolved deps).
//
// `getStatus` returns ok when the on-disk file matches what we'd emit, so
// re-runs after a no-op restart skip the write (and the Vite HMR churn it
// would otherwise cause).
export function manifest(opts: ManifestOptions = {}) {
	const output = opts.output ?? 'src/generated/manifest.ts';
	const name = opts.name ?? 'manifest';

	const deps = {
		packages: opts.packages ?? [],
		endpoints: opts.endpoints ?? [],
		accounts: opts.accounts ?? [],
	};

	return define<ManifestState, {}, typeof deps>({
		name,
		deps,
		inputs: ({ deps }) => ({
			output,
			body: renderManifest(deps as unknown as ResolvedDeps),
		}),
		getStatus: async ({ env, deps }) => {
			const path = resolveOutput(env.appDir, output);
			const expected = renderManifest(deps as unknown as ResolvedDeps);
			try {
				const actual = await readFile(path, 'utf8');
				return { ok: actual === expected };
			} catch {
				return { ok: false };
			}
		},
		run: async ({ env, deps, prior }) => {
			const path = resolveOutput(env.appDir, output);
			const body = renderManifest(deps as unknown as ResolvedDeps);
			const contentHash = hashOf(body);
			// Skip the write if the file already matches. Costs one
			// stat+read per cycle but keeps Vite HMR quiet on no-op
			// re-runs (and the file mtime stable, useful for downstream
			// staleness checks).
			let existing: string | undefined;
			try {
				existing = await readFile(path, 'utf8');
			} catch {
				// fall through — file missing, write fresh
			}
			if (existing === body) {
				return prior ?? { outputPath: path, contentHash };
			}
			await mkdir(dirname(path), { recursive: true });
			await writeFile(path, body, 'utf8');
			return { outputPath: path, contentHash };
		},
	});
}

function resolveOutput(appDir: string, output: string): string {
	return isAbsolute(output) ? output : resolve(appDir, output);
}

// Emitted file body. Stable shape — sort keys, sort entries — so diffs
// only show when actual content changes.
export function renderManifest(deps: ResolvedDeps): string {
	const sorted: ResolvedDeps = {
		packages: dedupeAndSort(deps.packages, (p) => p.name).map(stripHostFields),
		endpoints: dedupeAndSort(deps.endpoints, (e) => e.name),
		accounts: dedupeAndSort(deps.accounts, (a) => a.name),
	};
	const json = JSON.stringify(sorted, null, '\t');
	return `// AUTO-GENERATED by @mysten-incubation/devstack-next manifest — do not edit.
// Re-emitted whenever any upstream package / endpoint / account changes.

import type { Account, Endpoint, Package } from '@mysten-incubation/devstack-next/shapes';

export interface Manifest {
\tpackages: Package[];
\tendpoints: Endpoint[];
\taccounts: Account[];
}

export const manifest: Manifest = ${json};
`;
}

// Drop host-only fields from Package before serialization. The `path`
// field is an absolute on-host filesystem location used by the
// in-process bindings runtime; baking it into the committed manifest
// would leak one developer's home dir into every other developer's diff
// (and is meaningless after `git clone` to a different machine anyway).
function stripHostFields(pkg: Package): Package {
	if (pkg.path === undefined) return pkg;
	const { path: _path, ...rest } = pkg;
	return rest;
}

function dedupeAndSort<T>(items: T[], keyFn: (item: T) => string): T[] {
	const map = new Map<string, T>();
	for (const item of items) map.set(keyFn(item), item);
	return [...map.values()].sort((a, b) => keyFn(a).localeCompare(keyFn(b)));
}

// FNV-1a 32-bit. Cheap, deterministic, no crypto dep — fine for
// content-equality short-circuiting.
function hashOf(s: string): string {
	let h = 0x811c9dc5;
	for (let i = 0; i < s.length; i++) {
		h ^= s.charCodeAt(i);
		h = Math.imul(h, 0x01000193);
	}
	return (h >>> 0).toString(16).padStart(8, '0');
}
