// The FIXED `config-runtime.ts` source the codegen verb emits into the
// committed `src/generated` tree.
//
// This is NOT routed through the literal renderer (`format.ts`) — it is a
// constant string, emitted verbatim. It is the loud-failing id resolver
// the committed `config.ts` calls: `config.ts` carries NO on-chain id
// (those are LOADED CONFIG DATA, not codegen output), so each id is a
// `resolveId('@local/<slug>')` call into this module, which reads the
// build-time-injected `__DEVSTACK_IDS__` global and THROWS a clear,
// actionable error when the id is absent or the all-zero sentinel.
//
// `__DEVSTACK_IDS__` is injected synchronously by the devstack Vite plugin
// (`build-integrations/vite/index.ts`) via `define`:
//   - dev (stack up): the live `.devstack/stacks/<stack>/devstack-ids.json`.
//   - prod build:     a committed id-config FILE (same schema) — the Vite
//                     plugin `ids` option or a `DEVSTACK_IDS_FILE` path.
//   - neither:        `null` → `resolveId` throws at access time.

/** Output path (relative to the generated tree) of the emitted resolver. */
export const CONFIG_RUNTIME_OUTPUT_PATH = 'config-runtime.ts';

/** The verbatim source emitted as `src/generated/config-runtime.ts`. */
export const CONFIG_RUNTIME_SOURCE = `// THIS FILE IS AUTO-GENERATED BY @mysten/devstack.
// Do not edit by hand — your changes will be overwritten by the next
// \`devstack codegen\`. Apps consume codegen output; codegen output never
// imports from devstack.
//
// Loud-failing on-chain id resolver. The committed \`config.ts\` carries no
// ids; it resolves each id through \`resolveId(...)\` here, which reads the
// build-time-injected \`__DEVSTACK_IDS__\` global. Run \`devstack up\` for
// local dev (the Vite plugin injects the live ids), or point the build at a
// committed id-config file for a real deployment.

const UNRESOLVED_ID =
	'0x0000000000000000000000000000000000000000000000000000000000000000';

/** One network connection entry — \`rpc\` is the load-bearing field the app
 *  reads synchronously; \`chainId\`/\`faucet\`/\`graphql\` are optional
 *  diagnostics (mirrors \`IdConfigNetworkSchema\`). */
export interface DevstackNetworkEntry {
	readonly rpc: string;
	readonly chainId?: string;
	readonly faucet?: string | null;
	readonly graphql?: string | null;
}

/** Shape of the injected ids. \`null\` when no stack is running and no
 *  id-config file was supplied at build time. */
export interface DevstackIds {
	readonly network: string;
	readonly networks: { readonly [name: string]: DevstackNetworkEntry };
	readonly packages: {
		readonly [name: string]: { readonly id: string; readonly objects?: { readonly [k: string]: string } };
	};
	readonly accounts: { readonly [name: string]: string };
	readonly mvrOverrides: { readonly [mvrPlaceholder: string]: string };
	/** Generic resolver channel: \`values[namespace][key]\` carries
	 *  arbitrary plugin JSON the typed fields above can't (deepbook pool
	 *  ids, coin types, walrus/seal endpoints). Optional — an older
	 *  injected blob (no \`values\`) still satisfies the typed resolvers. */
	readonly values?: { readonly [namespace: string]: { readonly [key: string]: unknown } };
}

declare global {
	// Injected by the devstack Vite plugin via \`define\`. \`null\` when no
	// ids are available (no stack up + no id-config file).
	const __DEVSTACK_IDS__: DevstackIds | null | undefined;
}

/** Thrown when a generated config value needs an on-chain id but none was
 *  injected — actionable, not a silent zero. */
export class DevstackConfigMissingError extends Error {
	constructor(detail: string) {
		super(
			\`[devstack] \${detail}\\n\` +
				\`No on-chain ids are available. For local dev, run \\\`devstack up\\\` \` +
				\`(the Vite dev server injects the live ids). For a production build, \` +
				\`point the build at the known deployment's committed id-config file \` +
				\`(the Vite plugin \\\`ids\\\` option, or \\\`DEVSTACK_IDS_FILE\\\`) before \` +
				\`\\\`pnpm build\\\`. See your example README's "Deploy to a real network" \` +
				\`section.\`,
		);
		this.name = 'DevstackConfigMissingError';
	}
}

const ids = (): DevstackIds => {
	const injected = typeof __DEVSTACK_IDS__ === 'undefined' ? null : __DEVSTACK_IDS__;
	if (injected === null || injected === undefined) {
		throw new DevstackConfigMissingError('on-chain ids were never injected');
	}
	return injected;
};

/** Resolve the active-network id for an MVR placeholder (\`@local/<slug>\`).
 *  Throws \`DevstackConfigMissingError\` when the id is absent or the
 *  all-zero sentinel. */
export const resolveId = (mvrPlaceholder: string): string => {
	const id = ids().mvrOverrides[mvrPlaceholder];
	if (id === undefined || id === UNRESOLVED_ID) {
		throw new DevstackConfigMissingError(\`id for "\${mvrPlaceholder}" is unresolved\`);
	}
	return id;
};

/** Resolve the active network name (the \`networks.<name>\` key the app
 *  reads). Environment/live data — the local stack picks a dynamic value
 *  and a real deployment names a different network — so it is injected,
 *  never baked into the committed tree. Throws when no ids were injected. */
export const resolveNetwork = (): string => ids().network;

/** Resolve the network connection map (\`{ [name]: DevstackNetworkEntry }\`).
 *  The local rpc carries a dynamic port; a real deployment supplies its own —
 *  so this is injected, never baked. Throws when no ids were injected. */
export const resolveNetworks = (): { readonly [name: string]: DevstackNetworkEntry } =>
	ids().networks;

/** Resolve a generic plugin value (\`values[namespace][key]\`). The committed
 *  \`config.ts\` calls this for any live plugin value that isn't a package id
 *  or the network — deepbook pool ids, coin types, walrus/seal endpoints.
 *  Throws \`DevstackConfigMissingError\` when no ids were injected, the value
 *  is missing, or it is the all-zero sentinel. */
export const resolveValue = <T = unknown>(namespace: string, key: string): T => {
	const values = ids().values ?? {};
	const namespaceValues = values[namespace];
	const value = namespaceValues === undefined ? undefined : namespaceValues[key];
	if (value === undefined || value === UNRESOLVED_ID) {
		throw new DevstackConfigMissingError(
			\`value "\${namespace}.\${key}" is unresolved\`,
		);
	}
	return value as T;
};
`;
