// The APP-SPECIFIC strict deployment type — emitted as
// `src/generated/deployment.ts`.
//
// Unlike `config-runtime.ts` (a verbatim constant string), THIS file is
// RENDERED FROM DATA: it narrows the generic `NetworkDeployment` (from
// `config-runtime.ts`) to exactly the package names + MVR placeholders the
// app declares, and enumerates the live networks the app ships from the
// `deployments/` directory filenames.
//
// Four exported types/values:
//   - `AppPackages`           — exhaustive over THIS app's declared package
//                               names.
//   - `AppNetworkDeployment`  — the per-network shape a prod author hand-
//                               writes in `deployments/<net>.ts`: a
//                               `NetworkDeployment` with `packages: AppPackages`
//                               and `mvrOverrides` requiring the declared
//                               `@local/*` placeholder keys. NO `accounts`
//                               (those ride the runtime envelope, dev-only).
//   - `ProvidedNetwork`       — a union of the LIVE network names (the
//                               `deployments/*.ts` filenames, local excluded);
//                               `never` when none.
//   - `ProvidedDeployments`   — `Partial<Record<ProvidedNetwork,
//                               AppNetworkDeployment>>`.
//   - `NETWORK_NAMES`         — a literal `as const` tuple
//                               `[<localNetworkName>, ...<deployments files>]`
//                               for dapp-kit's typed `switchNetwork` (D2).
//
// Types-only + zero runtime: on a clean clone (no `deployments/` dir) this is
// the local network alone — `ProvidedNetwork = never`, `ProvidedDeployments`
// empty — so `tsc` stays green.

/** Input the renderer derives the strict types from. All values are
 *  CONFIG-known (no chain / no live resolution): the declared package names
 *  + MVR placeholders come from the `config.ts` aggregate bucket, the local
 *  network name from the sui binding, the live network names from the
 *  `deployments/*.ts` filenames. */
export interface DeploymentStrictInput {
	/** The local (dev-stack) network name — the sui binding's `network`
	 *  field. Always the head of `NETWORK_NAMES`. */
	readonly localNetworkName: string;
	/** This app's declared package names (the `config.packages.<name>`
	 *  keys), in stable order. */
	readonly packageNames: ReadonlyArray<string>;
	/** This app's declared MVR placeholders (the `@local/<slug>` keys an app
	 *  feeds dapp-kit's `mvr.overrides`), in stable order. */
	readonly mvrPlaceholders: ReadonlyArray<string>;
	/** The LIVE network names — `deployments/*.ts` filenames (sans `.ts`),
	 *  with the local network name excluded. Empty on a clean clone. */
	readonly providedNetworks: ReadonlyArray<string>;
}

/** Output path (relative to the generated tree) of the emitted strict type. */
export const DEPLOYMENT_STRICT_OUTPUT_PATH = 'deployment.ts';

/** Render the app-specific strict deployment type from data. Pure +
 *  deterministic (stable key ordering), types-only output. */
export const renderDeploymentStrict = (input: DeploymentStrictInput): string => {
	const { localNetworkName, packageNames, mvrPlaceholders, providedNetworks } = input;

	// `AppPackages` — exhaustive over the declared package names. Each entry
	// carries `{ id; objects? }`. An app with no packages still declares the
	// interface (empty), so `AppNetworkDeployment.packages` stays a concrete
	// type.
	const packagesBody =
		packageNames.length > 0
			? packageNames
					.map(
						(name) =>
							`\treadonly ${JSON.stringify(name)}: { readonly id: string; readonly objects?: Record<string, string> };`,
					)
					.join('\n')
			: '\treadonly [packageName: string]: never;';

	// `mvrOverrides` requires every declared `@local/<slug>` placeholder key.
	const mvrBody =
		mvrPlaceholders.length > 0
			? mvrPlaceholders.map((mvr) => `\t\t${JSON.stringify(mvr)}: string;`).join('\n')
			: '\t\t// (this app declares no MVR placeholders)';

	// `ProvidedNetwork` — the live (committed) network union; `never` when
	// the app ships none (a clean clone with no `deployments/` dir).
	const providedUnion =
		providedNetworks.length > 0
			? providedNetworks.map((n) => JSON.stringify(n)).join(' | ')
			: 'never';

	// `NETWORK_NAMES` — `[<local>, ...<provided>]` as a literal tuple.
	const networkNamesTuple = [localNetworkName, ...providedNetworks]
		.map((n) => JSON.stringify(n))
		.join(', ');

	return `// THIS FILE IS AUTO-GENERATED BY @mysten/devstack.
// Do not edit by hand — your changes will be overwritten by the next
// \`devstack codegen\`. Apps consume codegen output; codegen output never
// imports from devstack.
//
// The APP-SPECIFIC strict deployment type. A prod author writes a
// \`deployments/<net>.ts\` that \`satisfies AppNetworkDeployment\` — the type
// is exhaustive over this app's declared packages + MVR placeholders, so a
// missing/typo'd id fails \`tsc\`. The live network set
// (\`ProvidedNetwork\` / \`NETWORK_NAMES\`) is derived from the
// \`deployments/*.ts\` filenames. Types-only — zero runtime — except the
// \`NETWORK_NAMES\` literal tuple (for dapp-kit's typed \`switchNetwork\`).

import type { NetworkDeployment } from './config-runtime.js';

/** Exhaustive over THIS app's declared package names. */
export interface AppPackages {
${packagesBody}
}

/** The per-network shape a prod author hand-writes in
 *  \`deployments/<net>.ts\`: a \`NetworkDeployment\` narrowed so \`packages\` is
 *  exhaustive over this app's packages and \`mvrOverrides\` requires every
 *  declared \`@local/<slug>\` placeholder. NO \`accounts\` — dev accounts ride
 *  the runtime envelope, never the per-network authoring surface. */
export interface AppNetworkDeployment extends Omit<NetworkDeployment, 'packages' | 'mvrOverrides'> {
	readonly packages: AppPackages;
	readonly mvrOverrides: {
${mvrBody}
	} & { readonly [mvrPlaceholder: string]: string };
}

/** The LIVE network names this app ships — the \`deployments/*.ts\` filenames
 *  (local excluded). \`never\` when the app ships no committed deployments. */
export type ProvidedNetwork = ${providedUnion};

/** The committed per-network deployments map a prod build / dev serve loads.
 *  Partial — an app need not ship every live network at once. */
export type ProvidedDeployments = Partial<Record<ProvidedNetwork, AppNetworkDeployment>>;

/** The full network-name set, local-first: \`[<local>, ...<provided>]\`.
 *  dapp-kit's \`networks\` / \`switchNetwork\` type-check against this tuple
 *  (D2). */
export const NETWORK_NAMES = [${networkNamesTuple}] as const;
`;
};
