// TypeScript source rendering for codegen-emitted files.
//
// Distilled-doc § "Hand-rolled TS-object-literal rendering ... drifts
// subtly between emitters; a small shared renderer would absorb the
// variation and own the bigint policy in one place." This module IS
// that shared renderer.
//
// Output shape (one emitted file):
//
//   <generated-header>
//   <do-not-commit-banner if sensitive>
//   <imports?>
//   <one `export const <name> = <literal> as const;` per export>
//   <trailing newline>
//
// The renderer:
//   - sorts object keys (deterministic re-emit, distilled-doc
//     invariant "Deterministic re-emit"),
//   - quotes identifier-unsafe keys with double-quoted strings,
//   - serialises bigints as quoted decimal strings for
//     `BigInt(<string>)` consumers,
//   - refuses functions / symbols / undefined / circular refs with a
//     typed render error,
//   - emits arrays and records as readonly literal forms.
//
// The renderer does NOT format with prettier; it aims for
// prettier-compatible spacing (two-space indent, trailing commas,
// double-quoted strings, semicolons) so a prettier-on-write user
// hook is a no-op on emitted bytes — that's load-bearing for the
// "no mtime touch on identical content" idempotency invariant.

import { CodegenRenderError } from './errors.ts';

// -----------------------------------------------------------------------------
// Headers
// -----------------------------------------------------------------------------

const GENERATED_HEADER = [
	'// THIS FILE IS AUTO-GENERATED BY @mysten/devstack.',
	'// Do not edit by hand — your changes will be overwritten on the next',
	'// `devstack up` cycle. Apps consume codegen output; codegen output never',
	'// imports from devstack.',
].join('\n');

const SENSITIVE_HEADER = [
	'// !!! DO NOT COMMIT THIS FILE !!!',
	'// This file carries sensitive material (wallet pair token, database',
	'// credentials, or user extras). The output directory ships a .gitignore',
	'// covering it; this banner is a belt-and-braces reminder.',
].join('\n');

// -----------------------------------------------------------------------------
// Public render entry
// -----------------------------------------------------------------------------

export interface RenderInput {
	readonly emitterName: string;
	readonly outputPath: string;
	readonly sensitive: boolean;
	/** The declarations written by `Codegenable.emit(ctx)`. Each entry
	 *  becomes one `export const <key> = <literal> as const;`. */
	readonly exports: { readonly [key: string]: unknown };
	/** Optional import lines the emitter wants prepended (e.g. a
	 *  type import from `@mysten/dapp-kit` for the wallet config).
	 *  Each entry is a raw import statement string. */
	readonly imports?: ReadonlyArray<string>;
}

/** Result of a render attempt. Discriminated so callers can dispatch
 *  on `ok` without resorting to `instanceof` checks (STYLE_GUIDE §2). */
export type RenderResult =
	| { readonly ok: true; readonly text: string }
	| { readonly ok: false; readonly error: CodegenRenderError };

const renderErr = (
	input: RenderInput,
	detail: string,
): { readonly ok: false; readonly error: CodegenRenderError } => ({
	ok: false,
	error: new CodegenRenderError({
		emitterName: input.emitterName,
		outputPath: input.outputPath,
		detail,
	}),
});

/** Render an emitted file to a TS source string. Returns a discriminated
 *  `RenderResult` — `{ok: true, text}` on success, `{ok: false, error}`
 *  when the value is unserialisable or imports forbidden paths. */
export const renderFile = (input: RenderInput): RenderResult => {
	const lines: Array<string> = [];
	lines.push(GENERATED_HEADER);
	if (input.sensitive) {
		lines.push('');
		lines.push(SENSITIVE_HEADER);
	}
	lines.push('');
	if (input.imports && input.imports.length > 0) {
		for (const imp of input.imports) {
			if (isForbiddenGeneratedImport(imp)) {
				return renderErr(input, `generated files must not import devstack source: ${imp}`);
			}
			lines.push(imp);
		}
		lines.push('');
	}
	// Stable export order: keys lexicographically sorted.
	const keys = Object.keys(input.exports).sort();
	for (const key of keys) {
		const value = input.exports[key];
		const rendered = tryRender(value, new Set());
		if (!rendered.ok) {
			return renderErr(input, `export '${key}': ${rendered.detail}`);
		}
		if (!isIdentifier(key)) {
			return renderErr(input, `export key '${key}' is not a valid TS identifier`);
		}
		lines.push(`export const ${key} = ${rendered.text} as const;`);
		lines.push('');
	}
	// Single trailing newline; never two.
	while (lines.length > 1 && lines[lines.length - 1] === '' && lines[lines.length - 2] === '') {
		lines.pop();
	}
	return {
		ok: true,
		text: lines.join('\n') + (lines[lines.length - 1] === '' ? '' : '\n'),
	};
};

// -----------------------------------------------------------------------------
// Value rendering
// -----------------------------------------------------------------------------

const INDENT = '\t';

type TryRenderResult =
	| { readonly ok: true; readonly text: string }
	| { readonly ok: false; readonly detail: string };

const tryOk = (text: string): TryRenderResult => ({ ok: true, text });
const tryErr = (detail: string): TryRenderResult => ({ ok: false, detail });

const tryRender = (value: unknown, seen: Set<object>, depth = 1): TryRenderResult => {
	if (value === null) return tryOk('null');
	if (value === undefined) return tryErr('undefined is not serialisable — emit null instead');
	const t = typeof value;
	if (t === 'string') return tryOk(JSON.stringify(value));
	if (t === 'number') {
		if (!Number.isFinite(value as number)) return tryErr('non-finite number');
		return tryOk(String(value));
	}
	if (t === 'boolean') return tryOk(String(value));
	if (t === 'bigint') return tryOk(JSON.stringify(value.toString()));
	if (t === 'function' || t === 'symbol') return tryErr(`${t} is not serialisable`);
	if (Array.isArray(value)) {
		if (seen.has(value)) return tryErr('circular reference');
		seen.add(value);
		if (value.length === 0) return tryOk('[]');
		const inner: Array<string> = [];
		for (const item of value) {
			const r = tryRender(item, seen, depth + 1);
			if (!r.ok) return r;
			inner.push(INDENT.repeat(depth) + r.text);
		}
		seen.delete(value);
		return tryOk(`[\n${inner.join(',\n')},\n${INDENT.repeat(depth - 1)}]`);
	}
	if (t === 'object') {
		const obj = value as Record<string, unknown>;
		if (seen.has(obj)) return tryErr('circular reference');
		seen.add(obj);
		const keys = Object.keys(obj).sort();
		if (keys.length === 0) return tryOk('{}');
		const lines: Array<string> = [];
		for (const k of keys) {
			const v = obj[k];
			if (v === undefined) continue; // drop undefined props (distilled-doc skip-emit-explicit)
			const r = tryRender(v, seen, depth + 1);
			if (!r.ok) return r;
			const keyText = isIdentifier(k) ? k : JSON.stringify(k);
			lines.push(`${INDENT.repeat(depth)}${keyText}: ${r.text}`);
		}
		seen.delete(obj);
		if (lines.length === 0) return tryOk('{}');
		return tryOk(`{\n${lines.join(',\n')},\n${INDENT.repeat(depth - 1)}}`);
	}
	return tryErr(`unsupported value type ${t}`);
};

const IDENT_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const isIdentifier = (s: string): boolean => IDENT_RE.test(s);

const isForbiddenGeneratedImport = (line: string): boolean =>
	/\bfrom\s+["']@mysten-incubation\/devstack(?:-rewrite)?(?:\/|["'])/.test(line) ||
	/\bimport\s*\(\s*["']@mysten-incubation\/devstack(?:-rewrite)?(?:\/|["'])/.test(line) ||
	/\bfrom\s+["'][./][^"']*\/src\//.test(line) ||
	/\bimport\s*\(\s*["'][./][^"']*\/src\//.test(line);
