// .gitignore emission for the codegen output directory.
//
// The `.gitignore` policy depends on WHICH tree this is (`trackTree`):
//
//   - An EPHEMERAL tree (e.g. `.devstack/...`) is engine-managed output
//     — the pragmatic default is "ignore everything emitted here" (a
//     blanket `*`). Its id-bearing files must never land in git (the
//     `.devstack/` root is already gitignored too; this is
//     defense-in-depth + self-documentation).
//   - The COMMITTED tree at `src/generated`, written by the stack-free
//     `codegen` verb, is meant to be TRACKED: the type bindings + config
//     stubs (which carry NO on-chain ids — those are injected at app
//     build time) are committed so `tsc`/`vite build` work on a fresh
//     clone with no stack. Here the policy TRACKS everything by default
//     and only ignores the genuinely sensitive files (`sensitivePaths`).
//
// Three design points common to both:
//   1. A default policy line at the top of the file with a comment
//      explaining it (`*` for live, an all-tracked comment for committed).
//   2. Sensitive files get an explicit mention so the `.gitignore` reads
//      as documentation in addition to enforcing the policy.
//   3. User customisations land in a tracked `# user:` block — any
//      content the user adds between the `# user:` and `# /user:`
//      markers is preserved verbatim across re-emits.
//
// The `.gitignore` is emitted with the same per-file atomic writer as
// the rest of the codegen tree.

import { Effect, FileSystem } from 'effect';

import { emitOne } from './emit.ts';
import { CodegenWriteFailed } from './errors.ts';
import { NON_SENSITIVE_DIR_MODE, NON_SENSITIVE_FILE_MODE } from './permissions.ts';

const USER_BLOCK_START = '# user: customisations below preserved across re-emits';
const USER_BLOCK_END = '# /user: do not edit below this line';

const DEFAULT_USER_BLOCK = `${USER_BLOCK_START}\n${USER_BLOCK_END}`;

const ignoreAllHeader = [
	'# THIS FILE IS AUTO-GENERATED BY @mysten/devstack.',
	'# The codegen output directory is engine-managed; the whole tree is',
	'# ignored from git by default. Sensitive files have an explicit mention',
	'# below for documentation. Add user customisations inside the `# user:`',
	'# block; the rest is rewritten on every emit cycle.',
].join('\n');

const trackAllHeader = [
	'# THIS FILE IS AUTO-GENERATED BY @mysten/devstack.',
	'# This is the COMMITTED projection tree: the type bindings + sentinel-id',
	'# config stubs are tracked so `tsc`/`vite build` work on a fresh clone',
	'# with no stack running. Only genuinely sensitive files are ignored.',
	'# Add user customisations inside the `# user:` block; the rest is',
	'# rewritten on every emit cycle.',
].join('\n');

export interface GitignoreInput {
	readonly path: string;
	readonly parentMode?: number;
	/** Relative paths inside the output dir that are sensitive — get
	 *  an explicit gitignore line. Sorted lexicographically. */
	readonly sensitivePaths: ReadonlyArray<string>;
	/** When `true`, this is the COMMITTED projection tree (`src/generated`,
	 *  written by the stack-free `codegen` verb): track the stubs and only
	 *  ignore `sensitivePaths`. When `false`/omitted, this is the LIVE
	 *  ephemeral tree under `.devstack`: blanket-ignore everything. */
	readonly trackTree?: boolean;
}

/**
 * Compose the gitignore content, preserving any user customisations
 * between the `# user:` markers in any existing file at `path`.
 */
export const composeGitignore = (existing: string | null, input: GitignoreInput): string => {
	const userBlock = existing !== null ? extractUserBlock(existing) : null;
	const sortedSensitive = [...input.sensitivePaths].sort();
	const lines: Array<string> = [];
	if (input.trackTree === true) {
		// COMMITTED tree: track everything; ignore only the sensitive files.
		lines.push(trackAllHeader);
		lines.push('');
		lines.push('# default policy: track the whole committed projection tree.');
		if (sortedSensitive.length > 0) {
			lines.push('');
			lines.push('# sensitive files — never commit these even though the tree is tracked.');
			for (const p of sortedSensitive) lines.push(p);
		}
	} else {
		// LIVE tree: blanket-ignore everything.
		lines.push(ignoreAllHeader);
		lines.push('');
		lines.push('# default policy: ignore the whole output directory.');
		lines.push('*');
		lines.push('# but keep this .gitignore tracked so cloners get the policy.');
		lines.push('!.gitignore');
		if (sortedSensitive.length > 0) {
			lines.push('');
			lines.push('# sensitive files — never commit even if you override the `*` above.');
			for (const p of sortedSensitive) lines.push(p);
		}
	}
	lines.push('');
	lines.push(userBlock !== null ? userBlock : DEFAULT_USER_BLOCK);
	return lines.join('\n') + '\n';
};

/**
 * Write the gitignore. Idempotent via `emitOne`'s no-touch path.
 */
export const writeGitignore = (
	input: GitignoreInput,
): Effect.Effect<void, CodegenWriteFailed, FileSystem.FileSystem> =>
	Effect.gen(function* () {
		const fs = yield* FileSystem.FileSystem;
		const existing = yield* fs.readFileString(input.path).pipe(
			Effect.match({
				onSuccess: (text) => text,
				onFailure: () => null,
			}),
		);
		const content = composeGitignore(existing, input);
		yield* emitOne({
			path: input.path,
			content,
			mode: NON_SENSITIVE_FILE_MODE,
			parentMode: input.parentMode ?? NON_SENSITIVE_DIR_MODE,
		}).pipe(
			Effect.mapError(
				(e) =>
					new CodegenWriteFailed({
						outputPath: input.path,
						stage: 'gitignore',
						cause: e,
					}),
			),
		);
	});

const extractUserBlock = (text: string): string | null => {
	const startIdx = text.indexOf(USER_BLOCK_START);
	const endIdx = text.indexOf(USER_BLOCK_END);
	if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) return null;
	// Include both markers in the returned block.
	const endLineEnd = text.indexOf('\n', endIdx);
	const stop = endLineEnd === -1 ? text.length : endLineEnd;
	return text.slice(startIdx, stop);
};
