import { execFile } from 'node:child_process';
import { existsSync } from 'node:fs';
import { chmod, mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { describe, expect, it } from '@effect/vitest';
import { Effect, Stream } from 'effect';

import type { ContainerRuntime, OneShotSpec } from '../../../../src/contracts/container-runtime.ts';
import {
	CONTAINER_SCRUB_AWK_SCRIPT,
	containerInnerScript,
	hashMoveSources,
	parseBuildOutput,
	runMoveBuild,
	scrubLocksHost,
	stripPinnedSections,
} from '../../../../src/substrate/runtime/sui-move-build/index.ts';

const unusedRuntimeMethod = () => Effect.die('not used');

const oneShotRuntime = (runOneShot: ContainerRuntime['runOneShot']): ContainerRuntime => ({
	ensureImage: unusedRuntimeMethod,
	ensureNetwork: unusedRuntimeMethod,
	ensureContainer: unusedRuntimeMethod,
	exec: unusedRuntimeMethod,
	runOneShot,
	inspectByLabels: unusedRuntimeMethod,
	followLogs: () => Stream.empty,
	pause: unusedRuntimeMethod,
	pauseAndCommit: unusedRuntimeMethod,
	saveImage: () => Stream.empty,
	saveImages: () => Stream.empty,
	loadImage: unusedRuntimeMethod,
	tagImage: unusedRuntimeMethod,
	removeImage: unusedRuntimeMethod,
	unpause: unusedRuntimeMethod,
	stop: unusedRuntimeMethod,
	sweepOrphans: unusedRuntimeMethod,
	removeManagedContainers: unusedRuntimeMethod,
	removeManagedImages: unusedRuntimeMethod,
	removeManagedNetworks: unusedRuntimeMethod,
	removeManagedVolumes: unusedRuntimeMethod,
});

describe('sui-move-build helpers', () => {
	it('strips pinned Move.lock sections idempotently', () => {
		const input = [
			'[move]',
			'version = 3',
			'',
			'[pinned.testnet.dep]',
			'published-at = "0x1"',
			'',
			'[env]',
			'chain-id = "old"',
			'',
			'[dependencies]',
			'Foo = "local"',
			'',
		].join('\n');
		const stripped = stripPinnedSections(input);
		expect(stripped).toContain('[move]');
		expect(stripped).toContain('[dependencies]');
		expect(stripped).not.toContain('[pinned.testnet.dep]');
		expect(stripped).not.toContain('[env]');
		expect(stripPinnedSections(stripped)).toBe(stripped);
	});

	it('preserves the pre-pinned trailing blank line when pinned sections are terminal', () => {
		const unpinned = [
			'# Generated by move; do not edit',
			'# This file should be checked in.',
			'',
			'[move]',
			'version = 4',
			'',
			'',
		].join('\n');
		const pinned = [
			'# Generated by move; do not edit',
			'# This file should be checked in.',
			'',
			'[move]',
			'version = 4',
			'',
			'[pinned.testnet.dep]',
			'published-at = "0x1"',
			'',
		].join('\n');

		expect(stripPinnedSections(pinned)).toBe(unpinned);
	});

	it('copies the WHOLE mount to a scratch dir then scrubs around the build so the mount is untouched', () => {
		const script = containerInnerScript('demo');
		const buildOffset = script.indexOf('sui move build');
		expect(script).not.toContain('exec sui move build');
		expect(script).toContain('status=$?');
		// The whole bind-mounted tree is copied into the in-container scratch
		// root, never built in place at /workspace (`gawk -i inplace` would
		// corrupt the developer's checked-in Move.lock). Copying `/workspace/.`
		// (not just `/workspace/<pkg>`) materialises nested package paths and
		// carries sibling `{ local = "../x" }` deps — see the nested-package test.
		expect(script).toContain('cp -a /workspace/. /tmp/move-build-$$/');
		expect(script).not.toContain("cp -a /workspace/'demo'");
		// The package is built by its path INSIDE the scratch tree.
		expect(script).toContain("sui move build --path /tmp/move-build-$$/'demo'");
		// The scratch tree (root, so nested packages are covered) is scrubbed
		// before and after the build.
		const scratchFind = 'find /tmp/move-build-$$ -type f -name Move.lock';
		expect(script.indexOf(scratchFind)).toBeLessThan(buildOffset);
		expect(script.lastIndexOf(scratchFind)).toBeGreaterThan(buildOffset);
		expect(CONTAINER_SCRUB_AWK_SCRIPT).toContain('^\\[env');
	});

	it('stages a nested-path package and its sibling local dep without aborting under set -e', async () => {
		// Regression: the per-app exec build passes `pkgName` RELATIVE to the
		// bind-mounted app dir, so it can contain a slash (e.g. `packages/demo`),
		// and a package may reference a sibling via `{ local = "../token" }`.
		// The prior implementation copied only `/workspace/<pkgName>` into
		// `/tmp/move-build-$$/<pkgName>` without creating the intermediate dir,
		// so `set -e` aborted the whole build before `sui move build` ran AND the
		// sibling dep was dropped. We assert the emitted script's stage step is
		// well-formed for a nested pkgName by EXECUTING it against a fixture tree
		// (the real production code path is this shell string).
		const pkgName = 'packages/demo';
		const script = containerInnerScript(pkgName);

		// The stage copies the whole mount, and the build targets the nested path.
		expect(script).toContain('cp -a /workspace/. /tmp/move-build-$$/');
		expect(script).toContain("sui move build --path /tmp/move-build-$$/'packages/demo'");

		const root = await mkdtemp(join(tmpdir(), 'devstack-move-nested-'));
		try {
			// Bind-mount stand-in: appDir with a nested package referencing a sibling.
			const workspace = join(root, 'workspace');
			await mkdir(join(workspace, 'packages', 'demo', 'sources'), { recursive: true });
			await mkdir(join(workspace, 'packages', 'token', 'sources'), { recursive: true });
			await writeFile(
				join(workspace, 'packages', 'demo', 'Move.toml'),
				'[package]\nname = "demo"\n[dependencies]\ntoken = { local = "../token" }\n',
			);
			await writeFile(
				join(workspace, 'packages', 'token', 'Move.toml'),
				'[package]\nname = "token"\n',
			);

			// Drive ONLY the stage step the production script emits (the first
			// `cp -a /workspace/. <scratch>/`), rebased onto the fixture: rewrite
			// the in-container scratch root (`/tmp/move-build-$$`, `$$` and all)
			// and the `/workspace` mount to host paths. Run it under `sh -euc` so
			// a failed `cp` aborts (the script's own `set -e` semantics). If the
			// stage were the old single-subdir copy, the missing intermediate
			// `packages/` dir would make `cp` fail and reject here.
			const scratch = join(root, 'scratch');
			const stageLine = script
				.split('; ')
				.find((part) => part.startsWith('rm -rf /tmp/move-build-$$'));
			expect(stageLine).toBeDefined();
			const rebased = stageLine!
				.replaceAll('/tmp/move-build-$$', scratch)
				.replaceAll('/workspace', workspace);

			await new Promise<void>((resolveStage, rejectStage) => {
				execFile('sh', ['-euc', rebased], (err) => (err ? rejectStage(err) : resolveStage()));
			});

			// The nested package is present at its relative path in the scratch tree
			// (so `--path <scratch>/packages/demo` resolves)...
			expect(existsSync(join(scratch, 'packages', 'demo', 'Move.toml'))).toBe(true);
			// ...and the sibling `../token` dep came along (resolves from the package).
			expect(existsSync(join(scratch, 'packages', 'token', 'Move.toml'))).toBe(true);
		} finally {
			await rm(root, { recursive: true, force: true });
		}
	});

	it('hashes Move sources while normalising Move.lock pinned drift', async () => {
		const root = await mkdtemp(join(tmpdir(), 'devstack-move-build-'));
		try {
			await mkdir(join(root, 'sources'), { recursive: true });
			await mkdir(join(root, 'build'), { recursive: true });
			await writeFile(join(root, 'Move.toml'), '[package]\nname = "demo"\n');
			await writeFile(join(root, 'sources', 'demo.move'), 'module demo::demo {}\n');
			await writeFile(join(root, 'build', 'ignored.move'), 'module ignored::ignored {}\n');
			await writeFile(
				join(root, 'Move.lock'),
				'[move]\nversion = 3\n[pinned.testnet.dep]\npublished-at = "0x1"\n',
			);

			const first = await Effect.runPromise(hashMoveSources(root));
			await writeFile(
				join(root, 'Move.lock'),
				'[move]\nversion = 3\n[pinned.testnet.dep]\npublished-at = "0x2"\n',
			);
			const second = await Effect.runPromise(hashMoveSources(root));
			expect(second).toBe(first);

			await writeFile(
				join(root, 'sources', 'demo.move'),
				'module demo::demo { fun changed() {} }\n',
			);
			const third = await Effect.runPromise(hashMoveSources(root));
			expect(third).not.toBe(first);
		} finally {
			await rm(root, { recursive: true, force: true });
		}
	});

	it('scrubs the shared Move cache while leaving the source tree untouched', async () => {
		const root = await mkdtemp(join(tmpdir(), 'devstack-move-scrub-'));
		const packageLock = join(root, 'package', 'Move.lock');
		const cacheLock = join(root, 'move-home', 'git', 'dep', 'Move.lock');
		const lockedCacheLock = join(root, 'move-home', 'git', 'locked', 'Move.lock');
		try {
			await mkdir(join(root, 'package'), { recursive: true });
			await mkdir(join(root, 'move-home', 'git', 'dep'), { recursive: true });
			await mkdir(join(root, 'move-home', 'git', 'locked'), { recursive: true });
			const pinnedLock = '[move]\nversion = 3\n[pinned.testnet.dep]\npublished-at = "0x1"\n';
			await writeFile(packageLock, pinnedLock);
			await writeFile(cacheLock, pinnedLock);
			await writeFile(lockedCacheLock, pinnedLock);
			await chmod(lockedCacheLock, 0o444);

			await Effect.runPromise(
				scrubLocksHost(join(root, 'package'), join(root, 'move-home')).pipe(Effect.scoped),
			);

			// The developer's source tree is never mutated host-side; the package's
			// own Move.lock is scrubbed inside the container on a staged copy.
			expect(await readFile(packageLock, 'utf8')).toBe(pinnedLock);
			// Writable cache locks ARE scrubbed so stale pins don't leak into the build.
			expect(await readFile(cacheLock, 'utf8')).toBe('[move]\nversion = 3');
			// Unwritable cache locks are tolerated (the container scrub re-runs inside).
			expect(await readFile(lockedCacheLock, 'utf8')).toBe(pinnedLock);
		} finally {
			await chmod(lockedCacheLock, 0o644).catch(() => {});
			await rm(root, { recursive: true, force: true });
		}
	});

	it('never touches the package tree even when its Move.lock is unwritable', async () => {
		const root = await mkdtemp(join(tmpdir(), 'devstack-move-scrub-'));
		const packageLock = join(root, 'package', 'Move.lock');
		try {
			await mkdir(join(root, 'package'), { recursive: true });
			await mkdir(join(root, 'move-home'), { recursive: true });
			const pinnedLock = '[move]\nversion = 3\n[pinned.testnet.dep]\npublished-at = "0x1"\n';
			await writeFile(packageLock, pinnedLock);
			await chmod(packageLock, 0o444);

			await Effect.runPromise(
				scrubLocksHost(join(root, 'package'), join(root, 'move-home')).pipe(Effect.scoped),
			);

			expect(await readFile(packageLock, 'utf8')).toBe(pinnedLock);
		} finally {
			await chmod(packageLock, 0o644).catch(() => {});
			await rm(root, { recursive: true, force: true });
		}
	});

	it('parses trailing sui move build JSON into bytecode modules', async () => {
		const output = [
			'Compiling dependencies...',
			JSON.stringify({
				modules: [Buffer.from([1, 2, 3]).toString('base64')],
				dependencies: ['0x1', '0x2'],
			}),
		].join('\n');

		const parsed = await Effect.runPromise(parseBuildOutput(output, '/tmp/demo', 'demo'));
		expect(parsed.modules).toEqual([new Uint8Array([1, 2, 3])]);
		expect(parsed.dependencies).toEqual(['0x1', '0x2']);
	});

	it.effect('creates the Move cache mount source before one-shot docker build', () =>
		Effect.gen(function* () {
			const root = yield* Effect.promise(() => mkdtemp(join(tmpdir(), 'devstack-move-home-')));
			const previousHome = process.env.HOME;
			try {
				const home = join(root, 'home');
				const sourcePath = join(root, 'vault');
				yield* Effect.promise(() => mkdir(sourcePath, { recursive: true }));
				process.env.HOME = home;

				const capturedSpecs: OneShotSpec[] = [];
				const runtime = oneShotRuntime((spec) =>
					Effect.sync(() => {
						capturedSpecs.push(spec);
						const moveMount = spec.mounts?.find((mount) => mount.target === '/root/.move');
						expect(moveMount?.source).toBe(join(home, '.move'));
						expect(existsSync(join(home, '.move'))).toBe(true);
						return {
							exitCode: 0,
							stdout: JSON.stringify({ modules: [], dependencies: [] }),
							stderr: '',
						};
					}),
				);

				const result = yield* runMoveBuild({
					sourcePath,
					packageName: 'vault',
					chainId: 'localnet',
					runtime,
					buildImage: { digest: 'sha256:sui' },
				});

				expect(result).toEqual({ modules: [], dependencies: [] });
				expect(capturedSpecs[0]?.mounts).toContainEqual({
					source: join(home, '.move'),
					target: '/root/.move',
				});
			} finally {
				if (previousHome === undefined) {
					delete process.env.HOME;
				} else {
					process.env.HOME = previousHome;
				}
				yield* Effect.promise(() => rm(root, { recursive: true, force: true }));
			}
		}).pipe(Effect.scoped),
	);
});
