import { existsSync } from 'node:fs';
import { chmod, mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { describe, expect, it } from '@effect/vitest';
import { Effect, Stream } from 'effect';

import type { ContainerRuntime, OneShotSpec } from '../../../../src/contracts/container-runtime.ts';
import {
	CONTAINER_SCRUB_AWK_SCRIPT,
	containerInnerScript,
	hashMoveSources,
	parseBuildOutput,
	runMoveBuild,
	scrubLocksHost,
	stripPinnedSections,
} from '../../../../src/substrate/runtime/sui-move-build/index.ts';

const unusedRuntimeMethod = () => Effect.die('not used');

const oneShotRuntime = (runOneShot: ContainerRuntime['runOneShot']): ContainerRuntime => ({
	ensureImage: unusedRuntimeMethod,
	ensureNetwork: unusedRuntimeMethod,
	ensureContainer: unusedRuntimeMethod,
	exec: unusedRuntimeMethod,
	runOneShot,
	inspectByLabels: unusedRuntimeMethod,
	followLogs: () => Stream.empty,
	pause: unusedRuntimeMethod,
	pauseAndCommit: unusedRuntimeMethod,
	saveImage: () => Stream.empty,
	saveImages: () => Stream.empty,
	loadImage: unusedRuntimeMethod,
	tagImage: unusedRuntimeMethod,
	removeImage: unusedRuntimeMethod,
	unpause: unusedRuntimeMethod,
	stop: unusedRuntimeMethod,
	sweepOrphans: unusedRuntimeMethod,
	removeManagedContainers: unusedRuntimeMethod,
	removeManagedImages: unusedRuntimeMethod,
	removeManagedNetworks: unusedRuntimeMethod,
	removeManagedVolumes: unusedRuntimeMethod,
});

describe('sui-move-build helpers', () => {
	it('strips pinned Move.lock sections idempotently', () => {
		const input = [
			'[move]',
			'version = 3',
			'',
			'[pinned.testnet.dep]',
			'published-at = "0x1"',
			'',
			'[env]',
			'chain-id = "old"',
			'',
			'[dependencies]',
			'Foo = "local"',
			'',
		].join('\n');
		const stripped = stripPinnedSections(input);
		expect(stripped).toContain('[move]');
		expect(stripped).toContain('[dependencies]');
		expect(stripped).not.toContain('[pinned.testnet.dep]');
		expect(stripped).not.toContain('[env]');
		expect(stripPinnedSections(stripped)).toBe(stripped);
	});

	it('preserves the pre-pinned trailing blank line when pinned sections are terminal', () => {
		const unpinned = [
			'# Generated by move; do not edit',
			'# This file should be checked in.',
			'',
			'[move]',
			'version = 4',
			'',
			'',
		].join('\n');
		const pinned = [
			'# Generated by move; do not edit',
			'# This file should be checked in.',
			'',
			'[move]',
			'version = 4',
			'',
			'[pinned.testnet.dep]',
			'published-at = "0x1"',
			'',
		].join('\n');

		expect(stripPinnedSections(pinned)).toBe(unpinned);
	});

	it('scrubs lock files after container builds so build-generated pins do not leak', () => {
		const script = containerInnerScript('demo');
		const buildOffset = script.indexOf('sui move build');
		expect(script).not.toContain('exec sui move build');
		expect(script).toContain('status=$?');
		expect(script.indexOf('find /workspace')).toBeLessThan(buildOffset);
		expect(script.lastIndexOf('find /workspace')).toBeGreaterThan(buildOffset);
		expect(CONTAINER_SCRUB_AWK_SCRIPT).toContain('^\\[env');
	});

	it('hashes Move sources while normalising Move.lock pinned drift', async () => {
		const root = await mkdtemp(join(tmpdir(), 'devstack-move-build-'));
		try {
			await mkdir(join(root, 'sources'), { recursive: true });
			await mkdir(join(root, 'build'), { recursive: true });
			await writeFile(join(root, 'Move.toml'), '[package]\nname = "demo"\n');
			await writeFile(join(root, 'sources', 'demo.move'), 'module demo::demo {}\n');
			await writeFile(join(root, 'build', 'ignored.move'), 'module ignored::ignored {}\n');
			await writeFile(
				join(root, 'Move.lock'),
				'[move]\nversion = 3\n[pinned.testnet.dep]\npublished-at = "0x1"\n',
			);

			const first = await Effect.runPromise(hashMoveSources(root));
			await writeFile(
				join(root, 'Move.lock'),
				'[move]\nversion = 3\n[pinned.testnet.dep]\npublished-at = "0x2"\n',
			);
			const second = await Effect.runPromise(hashMoveSources(root));
			expect(second).toBe(first);

			await writeFile(
				join(root, 'sources', 'demo.move'),
				'module demo::demo { fun changed() {} }\n',
			);
			const third = await Effect.runPromise(hashMoveSources(root));
			expect(third).not.toBe(first);
		} finally {
			await rm(root, { recursive: true, force: true });
		}
	});

	it('scrubs package locks while tolerating unwritable Move cache locks', async () => {
		const root = await mkdtemp(join(tmpdir(), 'devstack-move-scrub-'));
		const packageLock = join(root, 'package', 'Move.lock');
		const cacheLock = join(root, 'move-home', 'git', 'dep', 'Move.lock');
		try {
			await mkdir(join(root, 'package'), { recursive: true });
			await mkdir(join(root, 'move-home', 'git', 'dep'), { recursive: true });
			const pinnedLock = '[move]\nversion = 3\n[pinned.testnet.dep]\npublished-at = "0x1"\n';
			await writeFile(packageLock, pinnedLock);
			await writeFile(cacheLock, pinnedLock);
			await chmod(cacheLock, 0o444);

			await Effect.runPromise(
				scrubLocksHost(join(root, 'package'), join(root, 'move-home')).pipe(Effect.scoped),
			);

			expect(await readFile(packageLock, 'utf8')).toBe('[move]\nversion = 3');
			expect(await readFile(cacheLock, 'utf8')).toBe(pinnedLock);
		} finally {
			await chmod(cacheLock, 0o644).catch(() => {});
			await rm(root, { recursive: true, force: true });
		}
	});

	it('fails when a package Move.lock cannot be scrubbed', async () => {
		const root = await mkdtemp(join(tmpdir(), 'devstack-move-scrub-'));
		const packageLock = join(root, 'package', 'Move.lock');
		try {
			await mkdir(join(root, 'package'), { recursive: true });
			await mkdir(join(root, 'move-home'), { recursive: true });
			await writeFile(
				packageLock,
				'[move]\nversion = 3\n[pinned.testnet.dep]\npublished-at = "0x1"\n',
			);
			await chmod(packageLock, 0o444);

			await expect(
				Effect.runPromise(
					scrubLocksHost(join(root, 'package'), join(root, 'move-home')).pipe(Effect.scoped),
				),
			).rejects.toMatchObject({
				_tag: 'MoveBuildError',
				phase: 'scrub',
				sourcePath: join(root, 'package'),
			});
		} finally {
			await chmod(packageLock, 0o644).catch(() => {});
			await rm(root, { recursive: true, force: true });
		}
	});

	it('tolerates unwritable package locks when container scrub will run later', async () => {
		const root = await mkdtemp(join(tmpdir(), 'devstack-move-scrub-'));
		const packageLock = join(root, 'package', 'Move.lock');
		try {
			await mkdir(join(root, 'package'), { recursive: true });
			await mkdir(join(root, 'move-home'), { recursive: true });
			const pinnedLock = '[move]\nversion = 3\n[pinned.testnet.dep]\npublished-at = "0x1"\n';
			await writeFile(packageLock, pinnedLock);
			await chmod(packageLock, 0o444);

			await Effect.runPromise(
				scrubLocksHost(join(root, 'package'), join(root, 'move-home'), {
					packageLockFailures: 'best-effort',
				}).pipe(Effect.scoped),
			);

			expect(await readFile(packageLock, 'utf8')).toBe(pinnedLock);
		} finally {
			await chmod(packageLock, 0o644).catch(() => {});
			await rm(root, { recursive: true, force: true });
		}
	});

	it('parses trailing sui move build JSON into bytecode modules', async () => {
		const output = [
			'Compiling dependencies...',
			JSON.stringify({
				modules: [Buffer.from([1, 2, 3]).toString('base64')],
				dependencies: ['0x1', '0x2'],
			}),
		].join('\n');

		const parsed = await Effect.runPromise(parseBuildOutput(output, '/tmp/demo', 'demo'));
		expect(parsed.modules).toEqual([new Uint8Array([1, 2, 3])]);
		expect(parsed.dependencies).toEqual(['0x1', '0x2']);
	});

	it.effect('creates the Move cache mount source before one-shot docker build', () =>
		Effect.gen(function* () {
			const root = yield* Effect.promise(() => mkdtemp(join(tmpdir(), 'devstack-move-home-')));
			const previousHome = process.env.HOME;
			try {
				const home = join(root, 'home');
				const sourcePath = join(root, 'vault');
				yield* Effect.promise(() => mkdir(sourcePath, { recursive: true }));
				process.env.HOME = home;

				const capturedSpecs: OneShotSpec[] = [];
				const runtime = oneShotRuntime((spec) =>
					Effect.sync(() => {
						capturedSpecs.push(spec);
						const moveMount = spec.mounts?.find((mount) => mount.target === '/root/.move');
						expect(moveMount?.source).toBe(join(home, '.move'));
						expect(existsSync(join(home, '.move'))).toBe(true);
						return {
							exitCode: 0,
							stdout: JSON.stringify({ modules: [], dependencies: [] }),
							stderr: '',
						};
					}),
				);

				const result = yield* runMoveBuild({
					sourcePath,
					packageName: 'vault',
					chainId: 'localnet',
					runtime,
					buildImage: { digest: 'sha256:sui' },
				});

				expect(result).toEqual({ modules: [], dependencies: [] });
				expect(capturedSpecs[0]?.mounts).toContainEqual({
					source: join(home, '.move'),
					target: '/root/.move',
				});
			} finally {
				if (previousHome === undefined) {
					delete process.env.HOME;
				} else {
					process.env.HOME = previousHome;
				}
				yield* Effect.promise(() => rm(root, { recursive: true, force: true }));
			}
		}).pipe(Effect.scoped),
	);
});
