// `StateStoreKeys` — typed builders for every state-store key in the
// devstack. Centralizes the `<service>/<artifact>/v<N>/<chainId>/...`
// key format root AGENTS.md mandates so:
//
//   1. The version segment is impossible to forget — each builder
//      bakes its `v<N>` into the template.
//   2. Per-key field shapes are typed (no more `${chainId}/${packageId}/...`
//      template-string ambiguity at the callsite).
//   3. A single grep against `StateStoreKeys.*` finds every persisted
//      artifact in the devstack — onboarding agents don't have to
//      crawl ten files looking for the in-flight cache keys.
//
// New keys land here, never at the callsite. The convention spelled
// out at the top of `engine/state-store.ts`:
//
//   <service>/<artifact>/v<N>/<chainId>/...
//
// `service` is the producing plugin (`coin`, `walrus`, `seal`,
// `deepbook`, `pyth`, `publishMove`, `tx`); `artifact` is the
// product (`mint`, `deploy-output`, `bls-keypair`, `pools`,
// `package`, etc.); `v<N>` is bumped whenever the JSON-encoded value
// shape changes (a bump invalidates every prior cached entry —
// state-store.ts treats decode misses as cache invalidation and
// re-derives).
//
// Phase 5.1 of `notes/api-simplification.md` formalized this — keys
// were previously inline template strings sprinkled across the
// services.

/**
 * Typed builders for every state-store key in the devstack. Each
 * function returns the canonical string key; pass it directly to
 * `stateStore.get` / `stateStore.put` / `stateStore.remove`. The
 * version segment is baked in — callers DO NOT supply a `v<N>` —
 * so bumping the on-disk shape is a one-line edit here.
 */
export const StateStoreKeys = {
	/**
	 * Per-cycle Move package publish result, keyed by package name,
	 * source-tree hash, and chainId. Source-hash changes on any Move
	 * source edit; chainId changes when the underlying chain is
	 * wiped — either invalidates the cache and the next cycle
	 * re-publishes.
	 *
	 * `publishMove/v2`. Bumped to v2 when the cached value shape
	 * gained additional fields (post-coin-plan).
	 */
	publishMove: (input: {
		readonly packageName: string;
		readonly sourceHash: string;
		readonly chainId: string;
	}): string => `publishMove/v2/${input.packageName}/${input.sourceHash}/${input.chainId}`,

	/**
	 * Idempotent coin-mint receipt — caches the digest + recipient +
	 * amount of a mint so a re-run with the same inputs short-circuits
	 * without an on-chain duplicate.
	 *
	 * `coin/mint/v1`. The coin-auto track owns this callsite —
	 * StateStoreKeys.coinMint is the canonical builder it
	 * will switch to.
	 */
	coinMint: (input: {
		readonly chainId: string;
		readonly treasuryCapId: string;
		readonly recipient: string;
		readonly amount: bigint | string;
	}): string =>
		`coin/mint/v1/${input.chainId}/${input.treasuryCapId}/${input.recipient}/${input.amount.toString()}`,

	/**
	 * Cached `Action(...)`-produced TxResult. Keyed by action name,
	 * chainId, signer address, and user-supplied `cacheKey` (which
	 * the action factory accepts as `string | Effect<string>`).
	 *
	 * `tx/v1`.
	 */
	actionTx: (input: {
		readonly actionName: string;
		readonly chainId: string;
		readonly signerAddress: string;
		readonly userKey: string;
	}): string =>
		`tx/v1/${input.actionName}/${input.chainId}/${input.signerAddress}/${input.userKey}`,

	/**
	 * Walrus on-chain deploy output (package id + system / staking
	 * object ids + epoch parameters). One per chain — the deploy
	 * surface bakes everything into a single record so the cycle
	 * after deploy can resume against it.
	 *
	 * `walrus/deploy-output/v3`. Bumped to v3 when the cached value
	 * shape changed alongside the walrus image refresh.
	 */
	walrusDeployOutput: (input: { readonly chainId: string }): string =>
		`walrus/deploy-output/v3/${input.chainId}`,

	/**
	 * Walrus seed-WAL swap receipt — caches the digest + amount of a
	 * SUI→WAL exchange against the seed wallet so a re-run with the
	 * same exchange + account inputs short-circuits.
	 *
	 * `walrus/seed-wal/v1`.
	 */
	walrusSeedWal: (input: {
		readonly chainId: string;
		readonly exchangeObjectId: string;
		readonly accountAddress: string;
	}): string =>
		`walrus/seed-wal/v1/${input.chainId}/${input.exchangeObjectId}/${input.accountAddress}`,

	/**
	 * Seal BLS keypair generated by `dockerOneShot` keygen. One per
	 * chain — re-generating after a chain wipe is intentional, but
	 * within a single chain's life the keypair is sticky so seal
	 * configs / on-chain key-server registrations stay stable.
	 *
	 * `seal/bls-keypair/v1`.
	 */
	sealBlsKeypair: (input: { readonly chainId: string }): string =>
		`seal/bls-keypair/v1/${input.chainId}`,

	/**
	 * Seal key-server object id — the result of the on-chain
	 * `KeyServer::register` transaction. Per chain.
	 *
	 * `seal/key-server-id/v1`.
	 */
	sealKeyServerId: (input: { readonly chainId: string }): string =>
		`seal/key-server-id/v1/${input.chainId}`,

	/**
	 * DeepBook pool ids, keyed by package id + a hash of the pools
	 * configuration. Re-deriving when either changes (typically when
	 * the pools config in the user's stack file is edited).
	 *
	 * `deepbook/pools/v1`.
	 */
	deepbookPools: (input: {
		readonly chainId: string;
		readonly packageId: string;
		readonly poolsHash: string;
	}): string => `deepbook/pools/v1/${input.chainId}/${input.packageId}/${input.poolsHash}`,

	/**
	 * DeepBook margin pool ids, keyed by margin package id + a hash
	 * of the per-pool config.
	 *
	 * `deepbook/margin-pools/v1`.
	 */
	deepbookMarginPools: (input: {
		readonly chainId: string;
		readonly packageId: string;
		readonly configHash: string;
	}): string =>
		`deepbook/margin-pools/v1/${input.chainId}/${input.packageId}/${input.configHash}`,

	/**
	 * DeepBook margin seed inventory — per-account funding deposits
	 * recorded so re-runs don't double-seed.
	 *
	 * `deepbook/margin-seed/v1`.
	 */
	deepbookMarginSeed: (input: {
		readonly chainId: string;
		readonly packageId: string;
		readonly trailing: string;
	}): string =>
		`deepbook/margin-seed/v1/${input.chainId}/${input.packageId}/${input.trailing}`,

	/**
	 * DeepBook market-maker balance manager id, keyed by core
	 * package id + signer address (+ optional sub-key for
	 * multi-manager market-makers).
	 *
	 * `deepbook/market-maker/balance-manager/v2`. Deepbook P6 owns
	 * this callsite — `StateStoreKeys.deepbookBalanceManager` is
	 * the canonical builder it will switch to.
	 */
	deepbookBalanceManager: (input: {
		readonly chainId: string;
		readonly packageId: string;
		readonly signerAddress: string;
		readonly subKey?: string;
	}): string => {
		const base = `deepbook/market-maker/balance-manager/v2/${input.chainId}/${input.packageId}/${input.signerAddress}`;
		return input.subKey === undefined ? base : `${base}/${input.subKey}`;
	},

	/**
	 * Pyth local-deploy package id + per-feed object ids, keyed by
	 * deploy package id + a hash of the configured feed list.
	 *
	 * `pyth/package/v1`.
	 */
	pythPackage: (input: {
		readonly chainId: string;
		readonly packageId: string;
		readonly feedsHash: string;
	}): string => `pyth/package/v1/${input.chainId}/${input.packageId}/${input.feedsHash}`,

	/**
	 * Pyth pusher object id, keyed by pyth package id + signer
	 * address.
	 *
	 * `pyth/pusher/v1`.
	 */
	pythPusher: (input: {
		readonly chainId: string;
		readonly packageId: string;
		readonly signerAddress: string;
	}): string => `pyth/pusher/v1/${input.chainId}/${input.packageId}/${input.signerAddress}`,

	/**
	 * `dockerOneShot` cached run result, keyed by the one-shot's
	 * factory `name` and a SHA-256 of its run-relevant inputs.
	 * Lives outside the `<service>/<artifact>/v<N>/<chainId>/...`
	 * shape because one-shots aren't chain-specific — the cache
	 * key encodes container image + args + env hashes directly.
	 *
	 * Used by `advanced/plugin-author/docker-one-shot.ts`.
	 */
	dockerOneShot: (input: { readonly name: string; readonly inputsHash: string }): string =>
		`dockerOneShot/${input.name}/${input.inputsHash}`,
};

/**
 * Discriminator for the typed-builder return. Useful for plugin
 * authors that want their own state-store keys to compose with
 * `StateStoreKeys` (typically by interposing a wrapper layer that
 * fans out to `stateStore.put(KEY, ...)`).
 */
export type StateStoreKey = string;
