// `StateStoreKeys` — typed builders for every state-store key in the
// devstack. Centralizes the key format so:
//
//   1. Per-key field shapes are typed (no more `${chainId}/${packageId}/...`
//      template-string ambiguity at the callsite).
//   2. A single grep against `StateStoreKeys.*` finds every persisted
//      artifact in the devstack.
//
// New keys land here, never at the callsite.

/**
 * Typed builders for every state-store key in the devstack. Each
 * function returns the canonical string key; pass it directly to
 * `stateStore.get` / `stateStore.put` / `stateStore.remove`.
 */
export const StateStoreKeys = {
	/**
	 * Per-cycle Move package publish result, keyed by package name,
	 * source-tree hash, and chainId. Source-hash changes on any Move
	 * source edit; chainId changes when the underlying chain is
	 * wiped — either invalidates the cache and the next cycle
	 * re-publishes.
	 */
	publishMove: (input: {
		readonly packageName: string;
		readonly sourceHash: string;
		readonly chainId: string;
	}): string => `publishMove/${input.packageName}/${input.sourceHash}/${input.chainId}`,

	/**
	 * Idempotent coin-mint receipt — caches the digest + recipient +
	 * amount of a mint so a re-run with the same inputs short-circuits
	 * without an on-chain duplicate.
	 */
	coinMint: (input: {
		readonly chainId: string;
		readonly treasuryCapId: string;
		readonly recipient: string;
		readonly amount: bigint | string;
	}): string =>
		`coin/mint/${input.chainId}/${input.treasuryCapId}/${input.recipient}/${input.amount.toString()}`,

	/**
	 * Cached `Action(...)`-produced TxResult. Keyed by action name,
	 * chainId, signer address, and user-supplied `cacheKey` (which
	 * the action factory accepts as `string | Effect<string>`).
	 */
	actionTx: (input: {
		readonly actionName: string;
		readonly chainId: string;
		readonly signerAddress: string;
		readonly userKey: string;
	}): string => `tx/${input.actionName}/${input.chainId}/${input.signerAddress}/${input.userKey}`,

	/**
	 * Walrus on-chain deploy output (package id + system / staking
	 * object ids + epoch parameters). One per chain — the deploy
	 * surface bakes everything into a single record so the cycle
	 * after deploy can resume against it.
	 */
	walrusDeployOutput: (input: { readonly chainId: string }): string =>
		`walrus/deploy-output/${input.chainId}`,

	/**
	 * Walrus seed-WAL swap receipt — caches the digest + amount of a
	 * SUI→WAL exchange against the seed wallet so a re-run with the
	 * same exchange + account inputs short-circuits.
	 */
	walrusSeedWal: (input: {
		readonly chainId: string;
		readonly exchangeObjectId: string;
		readonly accountAddress: string;
	}): string =>
		`walrus/seed-wal/${input.chainId}/${input.exchangeObjectId}/${input.accountAddress}`,

	/**
	 * Seal BLS keypair generated by `dockerOneShot` keygen. One per
	 * chain — re-generating after a chain wipe is intentional, but
	 * within a single chain's life the keypair is sticky so seal
	 * configs / on-chain key-server registrations stay stable.
	 */
	sealBlsKeypair: (input: { readonly chainId: string }): string =>
		`seal/bls-keypair/${input.chainId}`,

	/**
	 * Seal key-server object id — the result of the on-chain
	 * `KeyServer::register` transaction. Per chain.
	 */
	sealKeyServerId: (input: { readonly chainId: string }): string =>
		`seal/key-server-id/${input.chainId}`,

	/**
	 * DeepBook pool ids, keyed by package id + a hash of the pools
	 * configuration. Re-deriving when either changes (typically when
	 * the pools config in the user's stack file is edited).
	 */
	deepbookPools: (input: {
		readonly chainId: string;
		readonly packageId: string;
		readonly poolsHash: string;
	}): string => `deepbook/pools/${input.chainId}/${input.packageId}/${input.poolsHash}`,

	/**
	 * DeepBook margin pool ids, keyed by margin package id + a hash
	 * of the per-pool config.
	 */
	deepbookMarginPools: (input: {
		readonly chainId: string;
		readonly packageId: string;
		readonly configHash: string;
	}): string => `deepbook/margin-pools/${input.chainId}/${input.packageId}/${input.configHash}`,

	/**
	 * DeepBook margin seed inventory — per-account funding deposits
	 * recorded so re-runs don't double-seed.
	 */
	deepbookMarginSeed: (input: {
		readonly chainId: string;
		readonly packageId: string;
		readonly trailing: string;
	}): string => `deepbook/margin-seed/${input.chainId}/${input.packageId}/${input.trailing}`,

	/**
	 * DeepBook market-maker balance manager id, keyed by core
	 * package id + signer address (+ optional sub-key for
	 * multi-manager market-makers).
	 */
	deepbookBalanceManager: (input: {
		readonly chainId: string;
		readonly packageId: string;
		readonly signerAddress: string;
		readonly subKey?: string;
	}): string => {
		const base = `deepbook/market-maker/balance-manager/${input.chainId}/${input.packageId}/${input.signerAddress}`;
		return input.subKey === undefined ? base : `${base}/${input.subKey}`;
	},

	/**
	 * Pyth local-deploy package id + per-feed object ids, keyed by
	 * deploy package id + a hash of the configured feed list.
	 */
	pythPackage: (input: {
		readonly chainId: string;
		readonly packageId: string;
		readonly feedsHash: string;
	}): string => `pyth/package/${input.chainId}/${input.packageId}/${input.feedsHash}`,

	/**
	 * Pyth pusher object id, keyed by pyth package id + signer
	 * address.
	 */
	pythPusher: (input: {
		readonly chainId: string;
		readonly packageId: string;
		readonly signerAddress: string;
	}): string => `pyth/pusher/${input.chainId}/${input.packageId}/${input.signerAddress}`,

	/**
	 * `dockerOneShot` cached run result, keyed by the one-shot's
	 * factory `name` and a SHA-256 of its run-relevant inputs.
	 * One-shots aren't chain-specific — the cache key encodes
	 * container image + args + env hashes directly.
	 *
	 * Used by `advanced/plugin-author/docker-one-shot.ts`.
	 */
	dockerOneShot: (input: { readonly name: string; readonly inputsHash: string }): string =>
		`dockerOneShot/${input.name}/${input.inputsHash}`,
};

/**
 * Discriminator for the typed-builder return. Useful for plugin
 * authors that want their own state-store keys to compose with
 * `StateStoreKeys` (typically by interposing a wrapper layer that
 * fans out to `stateStore.put(KEY, ...)`).
 */
export type StateStoreKey = string;
