import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage();
const failed = [];
const errors = [];
page.on('pageerror', e => errors.push('pageerror: ' + e.message));
page.on('console', m => { if (m.type() === 'error') errors.push('console.error: ' + m.text()); });
page.on('requestfailed', r => failed.push(r.method() + ' ' + r.url() + ' — ' + r.failure()?.errorText));
await page.goto('http://localhost:5175/', { waitUntil: 'networkidle', timeout: 30000 }).catch(e => errors.push('goto: ' + e.message));
await new Promise(r => setTimeout(r, 5000));
console.log('FAILED REQUESTS:');
for (const f of failed) console.log(' -', f);
console.log('ERRORS:');
for (const e of errors) console.log(' -', e);
await browser.close();
