// .gitignore composition tests.

import { describe, expect, it } from '@effect/vitest';

import { composeGitignore } from '../../../src/orchestrators/codegen/gitignore.ts';

describe('gitignore/composeGitignore', () => {
	it('emits `*` + `!.gitignore` default policy', () => {
		const out = composeGitignore(null, {
			path: '/x/.gitignore',
			sensitivePaths: [],
		});
		expect(out).toContain('\n*\n');
		expect(out).toContain('!.gitignore');
	});

	it('lists sensitive paths explicitly, sorted', () => {
		const out = composeGitignore(null, {
			path: '/x/.gitignore',
			sensitivePaths: ['z.ts', 'a.ts', 'dapp-kit/config.ts'],
		});
		const ai = out.indexOf('a.ts');
		const di = out.indexOf('dapp-kit/config.ts');
		const zi = out.indexOf('z.ts');
		expect(ai).toBeGreaterThan(-1);
		expect(di).toBeGreaterThan(-1);
		expect(zi).toBeGreaterThan(-1);
		expect(ai).toBeLessThan(di);
		expect(di).toBeLessThan(zi);
	});

	it('preserves an existing user-block verbatim', () => {
		const existing = [
			'# old generated bytes',
			'',
			'# user: customisations below preserved across re-emits',
			'!my-tracked-file.ts',
			'!keep-this.json',
			'# /user: do not edit below this line',
		].join('\n');
		const out = composeGitignore(existing, {
			path: '/x/.gitignore',
			sensitivePaths: ['dapp-kit/config.ts'],
		});
		expect(out).toContain('!my-tracked-file.ts');
		expect(out).toContain('!keep-this.json');
	});

	it('falls back to a default empty user-block when no user block in existing', () => {
		const out = composeGitignore('# random content without markers', {
			path: '/x/.gitignore',
			sensitivePaths: [],
		});
		expect(out).toContain('# user: customisations below preserved across re-emits');
		expect(out).toContain('# /user: do not edit below this line');
	});

	it('produces byte-identical output on identical input (idempotency)', () => {
		const a = composeGitignore(null, {
			path: '/x/.gitignore',
			sensitivePaths: ['a.ts', 'b.ts'],
		});
		const b = composeGitignore(null, {
			path: '/x/.gitignore',
			sensitivePaths: ['a.ts', 'b.ts'],
		});
		expect(a).toBe(b);
	});
});
