// GENERATED by create-devstack-app: which optional plugin modules this app
// includes. Core `devstack.config.ts` spreads each module’s contribution.
//
// The authored template lists every optional plugin (the default "all plugins"
// scaffold); `create-devstack-app` rewrites this file to the subset you select.
// An empty array yields a clean core-only stack.

import { walrusModule } from './walrus.js';
import { sealModule } from './seal.js';
import { deepbookModule } from './deepbook.js';

import type { PluginModule } from './contribution.js';

export const OPTIONAL_PLUGINS: ReadonlyArray<PluginModule> = [
	walrusModule,
	sealModule,
	deepbookModule,
];
