// HTTP server logic for the wallet-server plugin. Exposes the
// resolved `ctx.accounts` so a browser-side signer adapter can
// list addresses and request transaction signatures without ever
// loading private keys into JavaScript.
//
// Endpoints (all under `/api/v1/devstack`):
//   GET  /accounts               → { accounts: [{ name, address, scheme, publicKey }] }
//   POST /sign-transaction       → { suiSignature }
//   POST /sign-personal-message  → { signature, bytes }
//
// Auth + reachability defaults are localnet-only:
//   - The listener binds 127.0.0.1, not 0.0.0.0. A coffee-shop LAN
//     attacker who knows the bearer token cannot reach the port.
//   - CORS is restricted to a per-stack allowlist (the manifest's
//     dev-server origin, plus any caller-supplied origins). `*` is
//     never the default.
//   - A 256-bit random bearer token still gates every endpoint; the
//     `?token=...` URL form is supported for the dev-wallet adapter's
//     pairing flow.
//
// These defaults can be overridden via `WalletServerOptions` for
// genuinely-remote dev rigs, but the override is opt-in.

import { type IncomingMessage, type Server, type ServerResponse, createServer } from 'node:http';
import { randomBytes, timingSafeEqual } from 'node:crypto';
import type { Signer } from '@mysten/sui/cryptography';
import { fromBase64, toBase64, isValidSuiAddress } from '@mysten/sui/utils';
import type { AccountsContext } from '../../core/types.js';

export interface WalletServerOptions {
	port: number;
	accounts: AccountsContext;
	/** Token authentication. Generated by the plugin if not supplied;
	 * exposed via the returned handle for logging. */
	token?: string;
	/** Maximum request body size in bytes. Defaults to 2 MB. */
	maxBodyBytes?: number;
	/** Bind address. Defaults to `127.0.0.1` (localhost-only) so a
	 * shared-LAN attacker who somehow learned the bearer token cannot
	 * reach the listener. Override with `'0.0.0.0'` (or a specific NIC)
	 * only for a genuinely-remote dev rig where the user understands
	 * the exposure. */
	host?: string;
	/** Allowed CORS origins. Defaults to `[]` — the server fills in the
	 * dev-server origin from the manifest at registration time. Pass
	 * extra origins for browser tooling that lives off the dev server
	 * (Storybook, a separate test harness). `'*'` is rejected: bearer
	 * tokens leak through manifests baked into the dev bundle, so an
	 * any-origin policy compounds the leak. */
	allowedOrigins?: string[];
}

export interface WalletServerHandle {
	server: Server;
	url: string;
	token: string;
}

interface AccountInfo {
	name: string;
	address: string;
	scheme: string;
	publicKey: string;
}

const DEFAULT_MAX_BODY_BYTES = 2 * 1024 * 1024;

/** Mint a fresh 256-bit bearer token. Exported so the Register action
 * can produce a deterministic token at apply-time (then write it to
 * `<stackDir>/wallet-token` for the listener to pick up). */
export function generateToken(): string {
	return randomBytes(32).toString('hex');
}

function buildAccountSnapshot(accounts: AccountsContext): {
	infos: AccountInfo[];
	signersByAddress: Map<string, Signer>;
} {
	const infos: AccountInfo[] = [];
	const signersByAddress = new Map<string, Signer>();
	for (const name of accounts.names()) {
		let signer: Signer;
		try {
			signer = accounts.get(name);
		} catch {
			// Resolver captured an error for this account (e.g. live-net
			// signer misconfigured). Skip — the rest of the API stays usable.
			continue;
		}
		const address = signer.toSuiAddress();
		signersByAddress.set(address, signer);
		infos.push({
			name,
			address,
			scheme: signer.getKeyScheme(),
			publicKey: signer.getPublicKey().toBase64(),
		});
	}
	return { infos, signersByAddress };
}

const DEFAULT_HOST = '127.0.0.1';

export async function startWalletServer(opts: WalletServerOptions): Promise<WalletServerHandle> {
	const token = opts.token ?? generateToken();
	const maxBodyBytes = opts.maxBodyBytes ?? DEFAULT_MAX_BODY_BYTES;
	const host = opts.host ?? DEFAULT_HOST;
	const allowedOrigins = sanitizeAllowedOrigins(opts.allowedOrigins ?? []);
	const snapshot = buildAccountSnapshot(opts.accounts);

	const server = createServer(async (req, res) => {
		const origin = typeof req.headers.origin === 'string' ? req.headers.origin : undefined;
		applyCorsHeaders(res, origin, allowedOrigins);
		if (req.method === 'OPTIONS') {
			// Reject preflight from a non-allowlisted origin so the browser
			// surfaces a CORS error instead of a misleading 200. Same-origin
			// requests don't carry an `Origin` header, so undefined passes.
			if (origin !== undefined && !originAllowed(origin, allowedOrigins)) {
				res.statusCode = 403;
				res.end();
				return;
			}
			res.statusCode = 204;
			res.end();
			return;
		}
		try {
			const url = new URL(req.url ?? '/', `http://${host}:${opts.port}`);
			if (req.method === 'GET' && url.pathname === '/health') {
				return sendJson(res, 200, { ok: true });
			}
			// Block any request whose Origin header doesn't match the
			// allowlist (CORS pre-checks live in the browser; this is a
			// belt-and-suspenders server-side guard against a same-machine
			// attacker who's bypassed the OPTIONS preflight).
			if (origin !== undefined && !originAllowed(origin, allowedOrigins)) {
				return sendJson(res, 403, { error: `Origin ${origin} not allowed` });
			}
			if (!isAuthorized(req, token)) {
				return sendJson(res, 401, {
					error: 'Authentication required. Pair via the URL printed at startup.',
				});
			}
			if (req.method === 'GET' && url.pathname === '/api/v1/devstack/accounts') {
				return sendJson(res, 200, { accounts: snapshot.infos });
			}
			if (req.method === 'POST' && url.pathname === '/api/v1/devstack/sign-transaction') {
				return await handleSign(req, res, snapshot.signersByAddress, maxBodyBytes);
			}
			if (req.method === 'POST' && url.pathname === '/api/v1/devstack/sign-personal-message') {
				return await handleSignPersonalMessage(req, res, snapshot.signersByAddress, maxBodyBytes);
			}
			sendJson(res, 404, { error: `No route for ${req.method} ${url.pathname}` });
		} catch (err) {
			const message = err instanceof Error ? err.message : String(err);
			sendJson(res, 500, { error: `Internal error: ${message}` });
		}
	});

	// Await the 'listening' event so the returned handle's
	// `server.address()` is immediately readable. Tests that pass
	// `port: 0` rely on this to discover the assigned port; the
	// production wallet-server flow doesn't care but the cost is one
	// microtask.
	await new Promise<void>((resolve, reject) => {
		const onError = (err: Error) => {
			server.off('listening', onListening);
			reject(err);
		};
		const onListening = () => {
			server.off('error', onError);
			resolve();
		};
		server.once('error', onError);
		server.once('listening', onListening);
		server.listen(opts.port, host);
	});
	const addr = server.address();
	const resolvedPort =
		typeof addr === 'object' && addr !== null && 'port' in addr ? addr.port : opts.port;
	const url = `http://${displayHost(host)}:${resolvedPort}`;
	return { server, url, token };
}

/** Reject `'*'` with a clear error; otherwise normalize each entry to
 * its `URL.origin` form so trailing slashes / paths don't subtly break
 * matching. */
function sanitizeAllowedOrigins(input: string[]): string[] {
	const out: string[] = [];
	for (const raw of input) {
		if (raw === '*') {
			throw new Error(
				'wallet-server: allowedOrigins cannot include "*" — bearer tokens leak through ' +
					'manifests baked into the dev bundle, so any-origin policies compound the leak. ' +
					'Pass the dev-server origin (e.g. "http://localhost:5173") explicitly.',
			);
		}
		try {
			out.push(new URL(raw).origin);
		} catch {
			throw new Error(`wallet-server: invalid origin in allowedOrigins: ${raw}`);
		}
	}
	return out;
}

function originAllowed(origin: string, allowed: string[]): boolean {
	if (allowed.length === 0) return false;
	return allowed.includes(origin);
}

function applyCorsHeaders(res: ServerResponse, origin: string | undefined, allowed: string[]): void {
	res.setHeader('Vary', 'Origin');
	if (origin !== undefined && originAllowed(origin, allowed)) {
		res.setHeader('Access-Control-Allow-Origin', origin);
	}
	res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
	res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
	res.setHeader('Access-Control-Max-Age', '86400');
}

function displayHost(host: string): string {
	if (host === '0.0.0.0' || host === '::') return 'localhost';
	return host;
}

function isAuthorized(req: IncomingMessage, token: string): boolean {
	const header = req.headers.authorization;
	if (typeof header !== 'string' || !/^bearer /i.test(header)) {
		const url = new URL(req.url ?? '/', `http://localhost`);
		const queryToken = url.searchParams.get('token');
		if (queryToken === null) return false;
		return safeEqualHex(queryToken, token);
	}
	const provided = header.slice(7);
	return safeEqualHex(provided, token);
}

function safeEqualHex(provided: string, expected: string): boolean {
	if (provided.length !== expected.length) return false;
	return timingSafeEqual(Buffer.from(provided), Buffer.from(expected));
}

async function readJsonBody(
	req: IncomingMessage,
	maxBodyBytes: number,
): Promise<Record<string, unknown>> {
	const chunks: Buffer[] = [];
	let total = 0;
	for await (const chunk of req) {
		const buf = chunk instanceof Buffer ? chunk : Buffer.from(chunk);
		total += buf.length;
		if (total > maxBodyBytes) {
			throw new RequestError(413, 'Request body too large');
		}
		chunks.push(buf);
	}
	const raw = Buffer.concat(chunks).toString('utf8');
	if (raw.length === 0) return {};
	try {
		const parsed = JSON.parse(raw) as unknown;
		if (parsed === null || typeof parsed !== 'object') {
			throw new RequestError(400, 'Body must be a JSON object');
		}
		return parsed as Record<string, unknown>;
	} catch (err) {
		if (err instanceof RequestError) throw err;
		throw new RequestError(400, 'Invalid JSON body');
	}
}

async function handleSign(
	req: IncomingMessage,
	res: ServerResponse,
	signers: Map<string, Signer>,
	maxBodyBytes: number,
): Promise<void> {
	let body: Record<string, unknown>;
	try {
		body = await readJsonBody(req, maxBodyBytes);
	} catch (err) {
		if (err instanceof RequestError) return sendJson(res, err.status, { error: err.message });
		throw err;
	}
	const address = body['address'];
	const txBytes = body['txBytes'];
	if (typeof address !== 'string' || !isValidSuiAddress(address)) {
		return sendJson(res, 400, { error: 'Invalid address; expected 0x-prefixed hex' });
	}
	if (typeof txBytes !== 'string' || txBytes.length === 0) {
		return sendJson(res, 400, { error: 'Invalid txBytes; expected non-empty base64 string' });
	}
	const signer = signers.get(address);
	if (signer === undefined) {
		return sendJson(res, 404, { error: `No signer for address ${address}` });
	}
	let bytes: Uint8Array;
	try {
		bytes = fromBase64(txBytes);
	} catch {
		return sendJson(res, 400, { error: 'txBytes is not valid base64' });
	}
	const { signature } = await signer.signTransaction(bytes);
	sendJson(res, 200, { suiSignature: signature, txBytes: toBase64(bytes) });
}

async function handleSignPersonalMessage(
	req: IncomingMessage,
	res: ServerResponse,
	signers: Map<string, Signer>,
	maxBodyBytes: number,
): Promise<void> {
	let body: Record<string, unknown>;
	try {
		body = await readJsonBody(req, maxBodyBytes);
	} catch (err) {
		if (err instanceof RequestError) return sendJson(res, err.status, { error: err.message });
		throw err;
	}
	const address = body['address'];
	const messageBytes = body['messageBytes'];
	if (typeof address !== 'string' || !isValidSuiAddress(address)) {
		return sendJson(res, 400, { error: 'Invalid address; expected 0x-prefixed hex' });
	}
	if (typeof messageBytes !== 'string' || messageBytes.length === 0) {
		return sendJson(res, 400, {
			error: 'Invalid messageBytes; expected non-empty base64 string',
		});
	}
	const signer = signers.get(address);
	if (signer === undefined) {
		return sendJson(res, 404, { error: `No signer for address ${address}` });
	}
	let bytes: Uint8Array;
	try {
		bytes = fromBase64(messageBytes);
	} catch {
		return sendJson(res, 400, { error: 'messageBytes is not valid base64' });
	}
	const { signature } = await signer.signPersonalMessage(bytes);
	sendJson(res, 200, { signature, bytes: toBase64(bytes) });
}

function sendJson(res: ServerResponse, status: number, body: unknown): void {
	res.statusCode = status;
	res.setHeader('Content-Type', 'application/json; charset=utf-8');
	res.end(JSON.stringify(body));
}

class RequestError extends Error {
	constructor(
		readonly status: number,
		message: string,
	) {
		super(message);
	}
}
