// HTTP server logic for the wallet-server plugin. Exposes the
// resolved `ctx.accounts` so a browser-side signer adapter can
// list addresses and request transaction signatures without ever
// loading private keys into JavaScript.
//
// Endpoints (all under `/api/v1/devstack`):
//   GET  /accounts               → { accounts: [{ name, address, scheme, publicKey }] }
//   POST /sign-transaction       → { suiSignature }
//   POST /sign-personal-message  → { signature, bytes }
//
// Auth model mirrors `dev-wallet/src/server/cli-signing-middleware.ts`:
// a 256-bit random token is generated at startup, printed to the
// supervisor log, and required as `Authorization: Bearer <token>`
// on every API request. CORS is open so the browser app can call
// across origins (Vite dev-server vs the wallet-server port).

import { type IncomingMessage, type Server, type ServerResponse, createServer } from 'node:http';
import { randomBytes, timingSafeEqual } from 'node:crypto';
import type { Signer } from '@mysten/sui/cryptography';
import { fromBase64, toBase64, isValidSuiAddress } from '@mysten/sui/utils';
import type { AccountsContext } from '../../core/types.js';

export interface WalletServerOptions {
	port: number;
	accounts: AccountsContext;
	/** Token authentication. Generated by the plugin if not supplied;
	 * exposed via the returned handle for logging. */
	token?: string;
	/** Maximum request body size in bytes. Defaults to 2 MB. */
	maxBodyBytes?: number;
}

export interface WalletServerHandle {
	server: Server;
	url: string;
	token: string;
}

interface AccountInfo {
	name: string;
	address: string;
	scheme: string;
	publicKey: string;
}

const DEFAULT_MAX_BODY_BYTES = 2 * 1024 * 1024;

function generateToken(): string {
	return randomBytes(32).toString('hex');
}

function buildAccountSnapshot(accounts: AccountsContext): {
	infos: AccountInfo[];
	signersByAddress: Map<string, Signer>;
} {
	const infos: AccountInfo[] = [];
	const signersByAddress = new Map<string, Signer>();
	for (const name of accounts.names()) {
		let signer: Signer;
		try {
			signer = accounts.get(name);
		} catch {
			// Resolver captured an error for this account (e.g. live-net
			// signer misconfigured). Skip — the rest of the API stays usable.
			continue;
		}
		const address = signer.toSuiAddress();
		signersByAddress.set(address, signer);
		infos.push({
			name,
			address,
			scheme: signer.getKeyScheme(),
			publicKey: signer.getPublicKey().toBase64(),
		});
	}
	return { infos, signersByAddress };
}

export function startWalletServer(opts: WalletServerOptions): WalletServerHandle {
	const token = opts.token ?? generateToken();
	const maxBodyBytes = opts.maxBodyBytes ?? DEFAULT_MAX_BODY_BYTES;
	const snapshot = buildAccountSnapshot(opts.accounts);

	const server = createServer(async (req, res) => {
		setCorsHeaders(res);
		if (req.method === 'OPTIONS') {
			res.statusCode = 204;
			res.end();
			return;
		}
		try {
			const url = new URL(req.url ?? '/', `http://localhost:${opts.port}`);
			if (req.method === 'GET' && url.pathname === '/health') {
				return sendJson(res, 200, { ok: true });
			}
			if (!isAuthorized(req, token)) {
				return sendJson(res, 401, {
					error: 'Authentication required. Pair via the URL printed at startup.',
				});
			}
			if (req.method === 'GET' && url.pathname === '/api/v1/devstack/accounts') {
				return sendJson(res, 200, { accounts: snapshot.infos });
			}
			if (req.method === 'POST' && url.pathname === '/api/v1/devstack/sign-transaction') {
				return await handleSign(req, res, snapshot.signersByAddress, maxBodyBytes);
			}
			if (req.method === 'POST' && url.pathname === '/api/v1/devstack/sign-personal-message') {
				return await handleSignPersonalMessage(
					req,
					res,
					snapshot.signersByAddress,
					maxBodyBytes,
				);
			}
			sendJson(res, 404, { error: `No route for ${req.method} ${url.pathname}` });
		} catch (err) {
			const message = err instanceof Error ? err.message : String(err);
			sendJson(res, 500, { error: `Internal error: ${message}` });
		}
	});

	server.listen(opts.port);
	const url = `http://localhost:${opts.port}`;
	return { server, url, token };
}

function setCorsHeaders(res: ServerResponse): void {
	res.setHeader('Access-Control-Allow-Origin', '*');
	res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
	res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
	res.setHeader('Access-Control-Max-Age', '86400');
}

function isAuthorized(req: IncomingMessage, token: string): boolean {
	const header = req.headers.authorization;
	if (typeof header !== 'string' || !/^bearer /i.test(header)) {
		const url = new URL(req.url ?? '/', `http://localhost`);
		const queryToken = url.searchParams.get('token');
		if (queryToken === null) return false;
		return safeEqualHex(queryToken, token);
	}
	const provided = header.slice(7);
	return safeEqualHex(provided, token);
}

function safeEqualHex(provided: string, expected: string): boolean {
	if (provided.length !== expected.length) return false;
	return timingSafeEqual(Buffer.from(provided), Buffer.from(expected));
}

async function readJsonBody(
	req: IncomingMessage,
	maxBodyBytes: number,
): Promise<Record<string, unknown>> {
	const chunks: Buffer[] = [];
	let total = 0;
	for await (const chunk of req) {
		const buf = chunk instanceof Buffer ? chunk : Buffer.from(chunk);
		total += buf.length;
		if (total > maxBodyBytes) {
			throw new RequestError(413, 'Request body too large');
		}
		chunks.push(buf);
	}
	const raw = Buffer.concat(chunks).toString('utf8');
	if (raw.length === 0) return {};
	try {
		const parsed = JSON.parse(raw) as unknown;
		if (parsed === null || typeof parsed !== 'object') {
			throw new RequestError(400, 'Body must be a JSON object');
		}
		return parsed as Record<string, unknown>;
	} catch (err) {
		if (err instanceof RequestError) throw err;
		throw new RequestError(400, 'Invalid JSON body');
	}
}

async function handleSign(
	req: IncomingMessage,
	res: ServerResponse,
	signers: Map<string, Signer>,
	maxBodyBytes: number,
): Promise<void> {
	let body: Record<string, unknown>;
	try {
		body = await readJsonBody(req, maxBodyBytes);
	} catch (err) {
		if (err instanceof RequestError) return sendJson(res, err.status, { error: err.message });
		throw err;
	}
	const address = body['address'];
	const txBytes = body['txBytes'];
	if (typeof address !== 'string' || !isValidSuiAddress(address)) {
		return sendJson(res, 400, { error: 'Invalid address; expected 0x-prefixed hex' });
	}
	if (typeof txBytes !== 'string' || txBytes.length === 0) {
		return sendJson(res, 400, { error: 'Invalid txBytes; expected non-empty base64 string' });
	}
	const signer = signers.get(address);
	if (signer === undefined) {
		return sendJson(res, 404, { error: `No signer for address ${address}` });
	}
	let bytes: Uint8Array;
	try {
		bytes = fromBase64(txBytes);
	} catch {
		return sendJson(res, 400, { error: 'txBytes is not valid base64' });
	}
	const { signature } = await signer.signTransaction(bytes);
	sendJson(res, 200, { suiSignature: signature, txBytes: toBase64(bytes) });
}

async function handleSignPersonalMessage(
	req: IncomingMessage,
	res: ServerResponse,
	signers: Map<string, Signer>,
	maxBodyBytes: number,
): Promise<void> {
	let body: Record<string, unknown>;
	try {
		body = await readJsonBody(req, maxBodyBytes);
	} catch (err) {
		if (err instanceof RequestError) return sendJson(res, err.status, { error: err.message });
		throw err;
	}
	const address = body['address'];
	const messageBytes = body['messageBytes'];
	if (typeof address !== 'string' || !isValidSuiAddress(address)) {
		return sendJson(res, 400, { error: 'Invalid address; expected 0x-prefixed hex' });
	}
	if (typeof messageBytes !== 'string' || messageBytes.length === 0) {
		return sendJson(res, 400, {
			error: 'Invalid messageBytes; expected non-empty base64 string',
		});
	}
	const signer = signers.get(address);
	if (signer === undefined) {
		return sendJson(res, 404, { error: `No signer for address ${address}` });
	}
	let bytes: Uint8Array;
	try {
		bytes = fromBase64(messageBytes);
	} catch {
		return sendJson(res, 400, { error: 'messageBytes is not valid base64' });
	}
	const { signature } = await signer.signPersonalMessage(bytes);
	sendJson(res, 200, { signature, bytes: toBase64(bytes) });
}

function sendJson(res: ServerResponse, status: number, body: unknown): void {
	res.statusCode = status;
	res.setHeader('Content-Type', 'application/json; charset=utf-8');
	res.end(JSON.stringify(body));
}

class RequestError extends Error {
	constructor(
		readonly status: number,
		message: string,
	) {
		super(message);
	}
}
