// GENERATED by create-devstack-app: which demo panels this app renders.
// Core CounterPanel is always present; optional plugin panels follow.
//
// The authored template lists every panel (the default "all plugins" scaffold);
// `create-devstack-app` rewrites this file to the subset you select. `App.tsx`
// maps over `PANELS` and never references a specific plugin.

import type { ComponentType } from 'react';

import { CounterPanel } from './panels/CounterPanel.js';
import { WalrusPanel } from './panels/WalrusPanel.js';
import { SealPanel } from './panels/SealPanel.js';
import { DeepbookPanel } from './panels/DeepbookPanel.js';

/** Each panel takes a single `connected` prop. */
export const PANELS: ReadonlyArray<ComponentType<{ connected: boolean }>> = [
	CounterPanel,
	WalrusPanel,
	SealPanel,
	DeepbookPanel,
];
